Repository geonetwork/core-geonetwork, pull requests merged in 2018-07, with the labels that each got.

#2903 Accessibility for the Search page
  web-ui/src/main/resources/catalog/components/common/savedselections/partials/action.html
  web-ui/src/main/resources/catalog/components/search/pagination/partials/pagination.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/geocat.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/titlewithselection.html
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/templates/editor/directory.html
Labels: enhancement

#2880 WMTS was not parsed on Online Resource wizard on the editor
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Labels: enhancement, good first issue

#2933 Update en-admin.json
  web-ui/src/main/resources/catalog/locales/en-admin.json
Labels: bug

#2945 Editor / Topic category / + should not be displayed #2940.
  schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
Labels: enhancement

#2948 Workflow / Fix invalid links in email.
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
  services/src/main/resources/org/fao/geonet/api/Messages.properties
  services/src/main/resources/org/fao/geonet/api/Messages_fre.properties
Labels: bug

#2944 ISO19110 / producer does not use directory #2942.
  schemas/iso19110/src/main/plugin/iso19110/layout/config-editor.xml
  web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
Labels: bug

#2949 Workflow / Fix invalid links in email.
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
  services/src/main/resources/org/fao/geonet/api/Messages.properties
  services/src/main/resources/org/fao/geonet/api/Messages_fre.properties
Labels: bug

#2968 The doc in the website looks to have moved to some new folder.
  web-ui/src/main/resources/catalog/components/common/needhelp/NeedHelpDirective.js
Labels: bug

#2966 Editor / inspire view / thesaurus renamed
  schemas-test/src/test/java/iso19139/UpdateFixedInfoTest.java
  schemas-test/src/test/resources/iso19139/descriptiveKeywordsUpdateFixedInfoXLinked.xml
  schemas/config-editor.xsd
  schemas/iso19139/doc/tpl.xml
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
  schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/editorconfig/config-editor.xsd
Labels: bug

#2979 Formatter / Schema resources are not properly loaded
  services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java
Labels: bug

#2972 Editor / CRS search is case sensitive #2971.
  services/src/main/java/org/fao/geonet/api/registries/CrsUtils.java
Labels: enhancement

#2975 Rating / When off, should not be displayed in search results #2974.
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
  web-ui/src/main/resources/catalog/components/search/mdview/partials/rate.html
Labels: enhancement

#2980 GeoPublisher / wrong html metadatalink posted to geoserver
  services/src/main/java/org/fao/geonet/api/mapservers/GeoServerRest.java
  services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java
  services/src/main/java/org/fao/geonet/services/publisher/Do.java
Labels: bug

#2961 Formatter / XSLT / Break work with some hardcoded rules
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  web/src/main/webapp/xslt/common/utility-tpl.xsl
Labels: enhancement

#2960 Formatter / XSLT / Break work with some hardcoded rules #2959.
  web/src/main/webapp/xslt/common/utility-tpl.xsl
Labels: enhancement

#2939 Fix deploy as root folder
  core/src/main/java/jeeves/monitor/MonitorManager.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
  web-ui/src/main/resources/catalog/components/common/languageswitcher/LanguageSwitcherDirective.js
  web-ui/src/main/resources/catalog/js/CatController.js
  web/src/main/java/org/fao/geonet/Geonetwork.java
  web/src/main/webResources/WEB-INF/config-db/database_migration.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v350/UrlComponentsDetectorsRegexMigration.java
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v350/migrate-default.sql
  web/src/test/java/v350/UrlComponentsDetectorsRegexMigrationTest.java
Labels: enhancement

#3000 Update en-editor.json
  web-ui/src/main/resources/catalog/locales/en-editor.json
Labels: enhancement
