Repository geonetwork/core-geonetwork, pull requests merged in 2018-11, with the labels that each got.

#3144 fix map loading in non-google projection
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
Labels: backport-3.4.4

#3236 PDF export/full view fails if ISO19139 has several publication dates. Fixes #3219
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Labels: backport-3.4.4

#3191 API / Formatter / Add JSON and text responses support.
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatType.java
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/XsltFormatter.java
Labels: enhancement

#3182 ISO19139 / Editor / Add possibility to customize field label for fileIdentifier and date stamp
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
Labels: enhancement

#3188 API / Standard / Codelist not properly retrieved when multiple defined.
  services/src/main/java/org/fao/geonet/api/standards/StandardsApi.java
  services/src/main/java/org/fao/geonet/api/standards/StandardsUtils.java
  services/src/main/java/org/fao/geonet/services/schema/Info.java
  services/src/main/java/org/fao/geonet/services/subtemplate/GetTypes.java
  web-ui/src/main/resources/catalog/components/common/schemamanager/SchemaManagerService.js
  web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
Labels: bug

#3242 Utility method to retrieve the thesaurus dir from xsl processes.
  core/src/main/java/org/fao/geonet/util/XslUtil.java
Labels: enhancement

#3243 Utility method to retrieve the thesaurus dir from xsl processes.
  core/src/main/java/org/fao/geonet/util/XslUtil.java
Labels: backport-3.4.4, enhancement

#3238 Batch edit / Add link to record
  web-ui/src/main/resources/catalog/templates/editor/batchedit.html
Labels: enhancement

#3222 Formatter / XSL / Remove hardcoded sample title
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
Labels: bug

#3256 API / Delete metadata record API endpoint doesn't work when a UUID is provided
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Labels: bug

#3266 Open cron help in a new window
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/schedule.html
Labels: bug

#3267 Opens cron help in a new window
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/schedule.html
Labels: backport-3.4.5

#3264 Support custom titles for metadata editor tables
  schemas/config-editor.xsd
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl
Labels: enhancement, schema plugin change

#3270 Add support for xpath in the metadata editor fields configuration
  schemas/config-editor.xsd
  schemas/dublin-core/src/main/plugin/dublin-core/layout/layout.xsl
  schemas/iso19110/src/main/plugin/iso19110/layout/layout-custom-fields.xsl
  schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
  schemas/iso19110/src/main/plugin/iso19110/layout/utility-fn.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
  web/src/main/webapp/xslt/common/functions-metadata.xsl
Labels: enhancement, schema plugin change

#3272 Disable browser autocomplete in the editor form
  web/src/main/webapp/xslt/ui-metadata/edit/edit.xsl
Labels: enhancement

#3268 Fix `gn.project.version` property in schemas module
  schemas/pom.xml
Labels: bug

#3269 Update versions release script
  update-version.sh
Labels: bug

#3215 Thesaurus tests fix
  core/src/main/java/org/fao/geonet/kernel/KeywordBean.java
  core/src/main/java/org/fao/geonet/kernel/search/keyword/KeywordSearchParams.java
  core/src/main/java/org/fao/geonet/kernel/search/keyword/KeywordSearchParamsBuilder.java
  core/src/test/java/org/fao/geonet/kernel/AbstractThesaurusBasedTest.java
  core/src/test/java/org/fao/geonet/kernel/AllThesaurusTest.java
  core/src/test/java/org/fao/geonet/kernel/ThesaurusTest.java
  core/src/test/java/org/fao/geonet/kernel/search/KeywordsSearcherTest.java
Labels: bug, enhancement

#3274 GeoNetwork harvester doesn't add new files when reharvesting using MEF format. Fixes #3273
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
Labels: bug

#3263 Small improvements to the scrollspy
  web-ui/src/main/resources/catalog/components/common/scrollspy/partials/scrollspy.html
  web-ui/src/main/resources/catalog/style/gn.less
Labels: enhancement

#3275 GeoNetwork harvester doesn't add new files when reharvesting using MEF format. Fixes #3273
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
Labels: backport-3.4.5, bug

#3232 Shell script to add a metadata schema in GeoNetwork for development
  add-schema.sh
Labels: enhancement

#3279 Editor / Fix alignement of field using div directive eg. topicCategory and duration.
  web-ui/src/main/resources/catalog/components/edit/fieldduration/partials/fieldduration.html
  web-ui/src/main/resources/catalog/components/edit/topiccategory/partials/topiccategory.html
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: bug

#3284 Adding datasets to a service metadata and saving the metadata corrupts the service metadata #3283
  schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java
  schemas/iso19139/src/main/resources/config-spring-geonetwork.xml
  schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/SchemaPlugin.java
Labels: bug, schema plugin change

#3289 Small bug in harvester creation
  web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
Labels: bug

#3128 ES / More robust indexing and update to ES6.4.2
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  es/es-core/src/main/java/org/fao/geonet/es/EsClient.java
  es/utility/skos2essynonyms.xsl
  pom.xml
  schemas/dublin-core/src/main/plugin/dublin-core/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  web-ui/src/main/resources/catalog/templates/editor/accessManager.html
  web/src/main/webapp/xslt/common/index-utils.xsl
Labels: enhancement

#3205 WFS indexing / Align with sextant
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  core/src/main/java/org/fao/geonet/kernel/search/log/QueryRequest.java
  core/src/main/java/org/fao/geonet/kernel/search/log/SearcherLogger.java
  core/src/main/java/org/fao/geonet/web/SearchStatisticsDatabaseMigration.java
  es/README.md
  es/config/records.json
  es/es-core/src/main/java/org/fao/geonet/es/EsClient.java
  pom.xml
  schemas/iso19139/src/main/resources/config-spring-geonetwork.xml
  web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
  web-ui/src/main/resources/catalog/components/index/IndexRequest.js
  web-ui/src/main/resources/catalog/components/index/IndexRequestConfig.js
  web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js
  web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterService.js
  web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html
  web-ui/src/main/resources/catalog/js/edit/AccessManagerController.js
  web/src/main/webResources/WEB-INF/config.properties
  web/src/main/webResources/WEB-INF/web.xml
  web/src/main/webapp/WEB-INF/classes/log4j-dev.xml
  web/src/main/webapp/WEB-INF/classes/log4j.xml
  workers/wfsfeature-harvester/pom.xml
  workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/WFSHarvesterApi.java
  workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/model/WFSHarvesterParameter.java
  workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
  workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/WFSHarvesterExchangeState.java
  workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/WFSHarvesterRouteBuilder.java
  workers/wfsfeature-harvester/src/main/resources/config-spring-geonetwork-jms.xml
  workers/wfsfeature-harvester/src/main/resources/config-spring-geonetwork.xml
Labels: enhancement

#3197 Editor board / Init search based on URL
  web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
  web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
  web-ui/src/main/resources/catalog/templates/editor/editorboard.html
Labels: enhancement

#3183 Editor / Add directive to hide a prefix or a suffix
  web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
Labels: enhancement

#3252 Thesaurus / Czech Republic geographical short name is now Czechia
  web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/place/regions.rdf
Labels: enhancement

#3248 Editor / Region selection.
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Labels: enhancement

#3262 Bug fix: Editing privileges acting as view privileges
  core/src/main/java/org/fao/geonet/kernel/search/LuceneQueryBuilder.java
  core/src/main/java/org/fao/geonet/kernel/search/LuceneQueryInput.java
  core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
  core/src/main/java/org/fao/geonet/kernel/search/SearchParameter.java
  core/src/main/java/org/fao/geonet/kernel/search/UserQueryInput.java
Labels: bug

#2866 Css style import function
  pom.xml
  services/src/main/java/org/fao/geonet/api/cssstyle/CssStyleSettingsService.java
  web-ui/src/main/resources/catalog/js/admin/CssStyleSettingsController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/settings/cssstyle.html
Labels: enhancement

#3259 Load projection definitions before creating maps
  web-ui/src/main/resources/catalog/components/common/map/mapsManager.js
Labels: bug
