Repository geonetwork/core-geonetwork, pull requests merged in 2018-12, with the labels that each got.

#3313 Fix: Close a modal (#3310)
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
Labels: bug

#3314 Map / Specific error message for GetCapabilities returning 401
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
  web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
  web-ui/src/main/resources/catalog/locales/en-core.json
Labels: enhancement

#3302 ID's added Import, Harvester and Online Resource pages
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/account.html
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/identification.html
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/privileges.html
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/schedule.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/arcsde.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geoPREST.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork20.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/ogcwxs.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/thredds.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/wfsfeatures.html
  web-ui/src/main/resources/catalog/templates/editor/import.html
Labels: enhancement

#3240 Utility method to change metadata schema identifier
  services/src/main/java/org/fao/geonet/api/processing/XslProcessUtils.java
Labels: backport-3.4.4, enhancement

#2894 ArcSDE harvester - Allow SQLXML type
  core/src/main/java/org/fao/geonet/arcgis/ArcSDEJdbcConnection.java
Labels: enhancement

#3336 TemplatesUriLocator.locate assumes file system path separator is uri path separator
  wro4j/src/main/java/org/fao/geonet/wro4j/TemplatesUriLocator.java
Labels: bug

#3332 Patches typeahead.bundle.js to fix an error in results shown
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/typeahead.js/typeahead.bundle.js
Labels: bug

#3340 [BP] Patches typeahead.bundle.js to fix an error in results shown
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/typeahead.js/typeahead.bundle.js
Labels: backport-3.4.5, bug

#3345 Display users of a group in the group maintenance #3341
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
Labels: enhancement

#3349 Fixes a bug when checking the waitForUse attribute in SearchFormDirective
  web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
Labels: bug

#3356 [BP] Fixes a bug when checking the waitForUse attribute in SearchFormDiretive
  web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
Labels: backport-3.4.5, bug

#3306 Logo position in header (#3261)
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/settings/cssstyle.html
  web-ui/src/main/resources/catalog/templates/top-toolbar.html
  web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
  web-ui/src/main/resources/catalog/views/default/templates/index.html
  web/src/main/webResources/WEB-INF/config-db/database_migration.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v350/LogoPositionInHeaderMigration.java
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v350/migrate-default.sql
Labels: enhancement

#3365 [BP] Add surname and username to user list
  web-ui/src/main/resources/catalog/components/search/formfields/partials/usersCombo.html
Labels: backport-3.4.5, bug

#3357 Avoid GN crashes when a projection is not correctly defined
  web-ui/src/main/resources/catalog/components/common/map/mapsManager.js
Labels: bug

#3304 Workflow / Email not in correct language
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
Labels: bug

#3353 Map is blank in non debug mode when opening the map tab
  web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
Labels: bug

#3355 [BP] Resolve behaviour of add button in editor #3010
  web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
  web-ui/src/main/resources/catalog/js/edit/EditorController.js
Labels: backport-3.4.5, bug

#3330 Improvements in projectionSwitcher configuration
  web-ui/src/main/resources/catalog/components/admin/uiconfig/UiConfigDirective.js
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/projectionSwitcher.html
Labels: bug

#3373 WFS Indexing / Admin panel does not display correct information
  web-ui/src/main/resources/catalog/js/admin/DashboardWfsIndexingController.js
Labels: bug

#3376 Small Improved styling for the metadata editor
  schemas/config-editor.xsd
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/js/edit/EditorController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v330/migrate-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v340/migrate-default.sql
  web/src/main/webapp/xslt/ui-metadata/edit/edit.xsl
Labels: enhancement

#3315 Update translations
  web-ui/src/main/resources/catalog/locales/ca-admin.json
  web-ui/src/main/resources/catalog/locales/ca-core.json
  web-ui/src/main/resources/catalog/locales/ca-editor.json
  web-ui/src/main/resources/catalog/locales/ca-search.json
  web-ui/src/main/resources/catalog/locales/es-admin.json
  web-ui/src/main/resources/catalog/locales/es-core.json
  web-ui/src/main/resources/catalog/locales/es-editor.json
  web-ui/src/main/resources/catalog/locales/es-search.json
  web-ui/src/main/resources/catalog/locales/fi-admin.json
  web-ui/src/main/resources/catalog/locales/fi-core.json
  web-ui/src/main/resources/catalog/locales/fi-editor.json
  web-ui/src/main/resources/catalog/locales/fi-search.json
  web-ui/src/main/resources/catalog/locales/fr-admin.json
  web-ui/src/main/resources/catalog/locales/fr-core.json
  web-ui/src/main/resources/catalog/locales/fr-editor.json
  web-ui/src/main/resources/catalog/locales/fr-search.json
  web-ui/src/main/resources/catalog/locales/is-admin.json
  web-ui/src/main/resources/catalog/locales/is-core.json
  web-ui/src/main/resources/catalog/locales/is-editor.json
  web-ui/src/main/resources/catalog/locales/is-search.json
  web-ui/src/main/resources/catalog/locales/it-admin.json
  web-ui/src/main/resources/catalog/locales/it-core.json
  web-ui/src/main/resources/catalog/locales/it-editor.json
  web-ui/src/main/resources/catalog/locales/it-search.json
  web-ui/src/main/resources/catalog/locales/ko-admin.json
  web-ui/src/main/resources/catalog/locales/ko-core.json
  web-ui/src/main/resources/catalog/locales/ko-editor.json
  web-ui/src/main/resources/catalog/locales/ko-search.json
  web-ui/src/main/resources/catalog/locales/nl-admin.json
  web-ui/src/main/resources/catalog/locales/nl-core.json
  web-ui/src/main/resources/catalog/locales/nl-editor.json
  web-ui/src/main/resources/catalog/locales/nl-search.json
  web-ui/src/main/resources/catalog/locales/ru-admin.json
  web-ui/src/main/resources/catalog/locales/ru-core.json
  web-ui/src/main/resources/catalog/locales/ru-editor.json
  web-ui/src/main/resources/catalog/locales/ru-search.json
  web-ui/src/main/resources/catalog/locales/sk-admin.json
  web-ui/src/main/resources/catalog/locales/sk-core.json
  web-ui/src/main/resources/catalog/locales/sk-editor.json
  web-ui/src/main/resources/catalog/locales/sk-search.json
Labels: enhancement

#3170 Editor / Simple overview manager
  schemas/config-editor.xsd
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/overview-manager.html
  web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
  web-ui/src/main/resources/catalog/locales/en-core.json
Labels: enhancement

#3381 Improve display of `tables` and `listviews` of Detail page on small screens
  web-ui/src/main/resources/catalog/components/viewer/wfs/partials/download.html
  web-ui/src/main/resources/catalog/style/gn_metadata.less
Labels: enhancement

#3362 Fixes harvester type names not translated
  web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
Labels: bug

#3280 ISO19139 / Schematron INSPIRE / Check at least one lineage is defined
  schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-inspire.disabled.sch
Labels: bug

#3320 ISO19139 / Formatter / Advanced view / Display link on keyword using Anchor
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Labels: enhancement

#3379 Fix back to search button.
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
  web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
Labels: bug

#3369 Editor / Month date / When saving year is reset to current year
  web-ui/src/main/resources/catalog/components/edit/datepicker/DatePickerDirective.js
Labels: bug

#3371 ES / Configure ES only when the profil is set.
  es/es-core/src/main/java/org/fao/geonet/es/EsClient.java
  healthmonitor/src/main/java/org/fao/geonet/monitor/health/DashboardAppHealthCheck.java
  healthmonitor/src/main/java/org/fao/geonet/monitor/health/IndexHealthCheck.java
  pom.xml
  web/pom.xml
  web/src/main/webResources/WEB-INF/config.properties
Labels: enhancement

#3311 WRO4J / Properly handle new lines for HTML templates (#3040)
  wro4j/src/main/java/org/fao/geonet/wro4j/TemplatesUriLocator.java
Labels: bug

#3378 UI configuration improvement.
  core/src/main/java/org/fao/geonet/migration/JsonDatabaseMigration.java
  web-ui/src/main/resources/catalog/components/admin/uiconfig/UiConfigDirective.js
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
  web-ui/src/main/resources/catalog/lib/ace/mode-json.js
  web-ui/src/main/resources/catalog/lib/ace/worker-json.js
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
Labels: enhancement

#3383 NullPointerException in metadata notifications management
  core/src/main/java/org/fao/geonet/notifier/MetadataNotifierManager.java
Labels: bug
