Repository geonetwork/core-geonetwork, pull requests merged in 2018-10, with the labels that each got.

#3135 Upload thesaurus error - permission denied #3131
  services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
Labels: backport-3.4.4

#3125 Remote index / Health check / Better warning.
  healthmonitor/src/main/java/org/fao/geonet/monitor/health/IndexHealthCheck.java
Labels: enhancement

#3143 MapServers configuration - Reset password option sends the password in the url. Fixes #3140
  web-ui/src/main/resources/catalog/js/admin/MapServerController.js
Labels: backport-3.4.4

#3138 ISO19139 - Lost of view hideTimeInCalendar attribute to hide the time part in date xslt templates. Fixes #3136
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-date.xsl
Labels: backport-3.4.4

#3114 More uniform styling for Detail Page
  web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
  web-ui/src/main/resources/catalog/components/viewer/atom/partials/atomDownload.html
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/style/gn_metadata.less
  web-ui/src/main/resources/catalog/style/gn_search.less
  web-ui/src/main/resources/catalog/views/default/directives/partials/attributetable.html
  web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
  web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
  web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Labels: enhancement

#3110 [WIP] Log a warning on duplicate UUID
  services/src/main/java/org/fao/geonet/api/ApiUtils.java
Labels: enhancement

#3145 wfs in online resource should be displayed as a 'layer protocol'
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
Labels: backport-3.4.4

#3096 New map tool: Projection switcher
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/projectionSwitcher.html
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
  web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
  web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
  web-ui/src/main/resources/catalog/components/viewer/ViewerModule.js
  web-ui/src/main/resources/catalog/components/viewer/baselayerswitcher/BaseLayerSwitcherDirective.js
  web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
  web-ui/src/main/resources/catalog/components/viewer/projectionSwitcher/ProjectionSwitcher.js
  web-ui/src/main/resources/catalog/components/viewer/projectionSwitcher/partials/projectionSwitcher.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/views/default/config.js
Labels: enhancement

#3150 Thesaurus / import form Registry / Set INSPIRE theme thesaurus date
  web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl
Labels: bug

#3158 Fix record removal when having feedbacks (#3122).
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
  domain/src/main/java/org/fao/geonet/domain/Metadata.java
  domain/src/main/java/org/fao/geonet/repository/userfeedback/UserFeedbackRepository.java
Labels: bug

#3126 Harvester / OGC WxS / Remove space causing match to fails #2823
  web/src/main/webapp/xsl/conversion/OGCWxSGetCapabilitiesto19119/OGCWxSGetCapabilitiesLayer-to-19139.xsl
Labels: bug

#3163 Update registry-to-skos.xsl
  web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl
Labels: bug

#3162 Fix record removal when having feedbacks (#3122). Similar to #3123 wi…
  core/src/main/java/org/fao/geonet/kernel/DataManager.java
  domain/src/main/java/org/fao/geonet/domain/Metadata.java
  domain/src/main/java/org/fao/geonet/repository/userfeedback/UserFeedbackRepository.java
Labels: bug

#3169 backport - Multiselect directive bug
  web-ui/src/main/resources/catalog/components/common/multiselect/MultiselectDirective.js
Labels: backport-3.4.4

#3161 Fix: Show name + surname in harvester users dropdown (#3083)
  web-ui/src/main/resources/catalog/components/search/formfields/partials/usersCombo.html
Labels: enhancement

#3112 compared the schema label strings between english and dutch
  schemas/iso19139/src/main/plugin/iso19139/loc/dut/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml
Labels: enhancement

#3141 Map / Context contains layer URL with proxy
  web-ui/src/main/resources/catalog/components/common/map/print/PrintMapService.js
  web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
  web-ui/src/main/resources/catalog/js/CatController.js
Labels: bug

#3185 Schema / Doc on displayIf for helper.
  schemas/schema-labels.xsd
Labels: enhancement

#3201 Updated jackson dependencies
  pom.xml
Labels: enhancement

#3189 typo and missing translation
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/logopicker.html
Labels: enhancement

#3221 remove capabilities parsing from wmts-links in metadata view
  web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
  web-ui/src/main/resources/catalog/locales/en-search.json
Labels: bug

#3218 Thesaurus / Import from registry / Fix date for INSPIRE classification of services
  web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl
Labels: bug

#3217 Harvester / Fix duplicated override UUID parameter.
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  web/src/main/webapp/xsl/xml/harvesting/common.xsl
Labels: bug
