Repository geonetwork/core-geonetwork, pull requests merged in 2018-09, with the labels that each got.

#3046 Record creation / Set title with 'Copy of' record or template title ' created at' date
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
  core/src/main/resources/org/fao/geonet/api/Messages.properties
  core/src/main/resources/org/fao/geonet/api/Messages_fre.properties
  schemas/dublin-core/src/main/resources/config-spring-geonetwork.xml
  schemas/iso19110/src/main/resources/config-spring-geonetwork.xml
  schemas/iso19139/src/main/resources/config-spring-geonetwork.xml
  schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/SchemaPlugin.java
Labels: enhancement, schema plugin change

#2990 RSS / Fix XSLT error when a DC record contains more than one extent.
  schemas/dublin-core/src/main/plugin/dublin-core/layout/tpl-brief.xsl
  web/src/main/webapp/xslt/services/rss/rss-utils.xsl
Labels: bug

#2883 XSLT / Formatter / Create thesaurus block only if one or more keyword is set
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Labels: enhancement

#3047 Formatter / XSLT / Enable tab mode or not.
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-variables.xsl
Labels: enhancement

#2890 Added missing translation for cancelMetadataEditor
  web-ui/src/main/resources/catalog/locales/en-editor.json
Labels: bug

#3075 Only index INSPIRE related fields if thesaurus is present
  schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
Labels: bug

#3081 Standard / Add API to reload standards
  core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
  services/src/main/java/org/fao/geonet/api/standards/StandardsApi.java
Labels: enhancement

#3032 Harvester / OGC WxS / When using template mode, always synch records.
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
  schemas/iso19139/src/main/plugin/iso19139/convert/ogcwxs-info-injection.xsl
Labels: enhancement

#3080 Editor / Properly close editor tab when a new window is opened.
  web-ui/src/main/resources/catalog/js/edit/EditorController.js
Labels: bug

#3069 Throws a more legible exception when region is not found
  core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
Labels: enhancement

#3079 OutOfMemoryError when listing groups using service admin.group.list
  domain/src/main/java/org/fao/geonet/domain/MetadataCategory.java
  services/src/main/java/org/fao/geonet/api/categories/TagsApi.java
Labels: bug

#2958 Support geosticker approach (embedded iso19139 in esri metadata) in sde harvester. Fixes #2914
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/arcsde/ArcSDEHarvester.java
Labels: enhancement

#2878 Formatter / XSLT / Display temporal extent properly based on config editor
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
Labels: bug

#3087 Editor configuration / Add class attribute to action element.
  schemas/config-editor.xsd
  schemas/dublin-core/src/main/plugin/dublin-core/layout/layout.xsl
  schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
  web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
Labels: enhancement

#3089 Fixes #1554
  web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
Labels: bug, enhancement

#3059 Accessibility and styling changes to the editor sidepanel
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
  web-ui/src/main/resources/catalog/components/edit/suggestion/partials/list.html
  web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/style/gn_editor.less
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_view.less
Labels: enhancement

#3093 Add WMS layer doesn't work fine when url ends with ? the proxy adds an extra ? character and the GetMap requests fail. Fixes #3088
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
Labels: bug

#2868 Formatter / XSLT / Display temporal extent properly based on config editor
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
Labels: bug

#3105 Fixes an error related to thesaurus encoding when uploading from a registry
  services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
Labels: bug

#3095 add capability to add to map for tms protocol
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
  web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Labels: enhancement, good first issue, new feature
