Repository geonetwork/core-geonetwork, pull requests merged in 2018-06, with the labels that each got.

#2822 Problem with map in IE
  web-ui/src/main/resources/catalog/style/gn_viewer.less
  web-ui/src/main/resources/catalog/views/default/less/gn_footer_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
Labels: bug

#2798 Behavior of delete buttons in User and Groups tools
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: enhancement

#2808 Refactor JsonDatabaseMigration to make easier to implement future JSON setting migrations
  core/src/main/java/org/fao/geonet/migration/JsonDatabaseMigration.java
  web/src/main/java/org/fao/geonet/DatabaseMigration.java
  web/src/main/webResources/WEB-INF/config-db/database_migration.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v343/AdvancedSearchFormMigration.java
  web/src/test/java/v343/AdvancedSearchFormMigrationTest.java
Labels: bug, enhancement

#2664 option to add selected layer from wmts to onlinesrcdirective
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Labels: enhancement

#2678 remove xml view in md view options
  core/src/main/java/org/fao/geonet/kernel/EditLib.java
  core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
  core/src/main/java/org/fao/geonet/kernel/schema/MetadataType.java
  core/src/test/java/org/fao/geonet/kernel/EditLibIntegrationTest.java
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
  services/src/main/java/org/fao/geonet/api/records/editing/EditUtils.java
  web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentryselector.html
  web-ui/src/main/resources/catalog/components/edit/recordfragmentselector/partials/rfselector.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Labels: enhancement

#2793 Remove minor version number from schema artifacts
  common/src/main/java/org/fao/geonet/utils/Version.java
  core/pom.xml
  core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
  core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchema.java
  pom.xml
  schemas-test/pom.xml
  schemas/csw-record/pom.xml
  schemas/csw-record/src/main/plugin/csw-record/schema-ident.xml
  schemas/dublin-core/pom.xml
  schemas/dublin-core/src/main/plugin/dublin-core/schema-ident.xml
  schemas/iso19110/pom.xml
  schemas/iso19110/src/main/plugin/iso19110/schema-ident.xml
  schemas/iso19139/pom.xml
  schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml
  schemas/pom.xml
  schemas/schema-core/pom.xml
  web/pom.xml
  web/src/main/java/org/fao/geonet/DatabaseMigration.java
  web/src/main/webapp/xml/validation/schemaPlugins/schema-ident.xsd
Labels: enhancement, schema plugin change

#2840 a generic error is displayed if full view fails due to xslt error
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
  web-ui/src/main/resources/catalog/locales/en-core.json
Labels: bug

#2835 <html> element must have a valid value for the lang attribute
  core/src/main/java/jeeves/constants/Jeeves.java
  core/src/main/java/jeeves/server/dispatchers/ServiceManager.java
  web/src/main/webapp/xslt/base-layout.xsl
  web/src/main/webapp/xslt/common/base-variables.xsl
Labels: bug

#2865 Metadata editor (ISO19139) - Bounding box in full view displays before the map, the content of labels.xml, fixes #2864
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
Labels: bug

#2885 wildcard attribute in PropertyIsLike must be wildCard (CSW harvester)
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
Labels: bug

#2896 Search results / Restore the possibility to switch template used for rendering results based on the UI config. Make the list mode looks like the grid mode.
  web-ui/src/main/resources/catalog/components/search/resultsview/ResultsviewDirective.js
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/templateswitcher.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
  web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
  web-ui/src/main/resources/catalog/views/default/module.js
  web-ui/src/main/resources/catalog/views/default/templates/results.html
Labels: enhancement

#2895 Metadata import / Select first group by default (instead of the empty one added if optional is true).
  web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
Labels: enhancement

#2900 Map / Add legend panel.
  web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
  web-ui/src/main/resources/catalog/components/viewer/ViewerModule.js
  web-ui/src/main/resources/catalog/components/viewer/legendpanel/partials/legendpanel.html
  web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/locales/en-search.json
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
Labels: enhancement
