Repository geonetwork/core-geonetwork, pull requests merged in 2019-06, with the labels that each got.

#3853 [BP 3.6.x] Fix thubmnail-add parameter names for ISO 19115-3
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Labels: backport-3.4.5, bug

#3852 Fix thumbnail-add.xsl parameter names for ISO 19115-3
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Labels: bug

#3815 Adds an id to add attribute button
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: enhancement

#3809 Improvements in transfer ownership dialog usability
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
  web-ui/src/main/resources/catalog/components/metadataactions/partials/transferownership.html
Labels: bug

#3822 Uses function validateUrl in linked-data-checker.xsl process
  schemas/iso19139/src/main/plugin/iso19139/process/linked-data-checker.xsl
Labels: bug

#3851 Map / Add map or layer from records / Search on focus and info when none found
  web-ui/src/main/resources/catalog/components/viewer/searchlayerformap/partials/searchlayerformap.html
  web-ui/src/main/resources/catalog/locales/en-search.json
Labels: enhancement

#3844 Editor - extend template to apply angularjs directives to fields to send 'required' flag. Update directives for topic categories and field duration to use 'required' flag
  web-ui/src/main/resources/catalog/components/edit/fieldduration/FieldDurationDirective.js
  web-ui/src/main/resources/catalog/components/edit/fieldduration/partials/fieldduration.html
  web-ui/src/main/resources/catalog/components/edit/topiccategory/TopicCategoryDirective.js
  web-ui/src/main/resources/catalog/components/edit/topiccategory/partials/topiccategory.html
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: enhancement

#3829 Editor / Configuration / Add support for `@del` in codelist element
  schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
Labels: enhancement

#3824 Associated panel / When there is no layer, coupledResource should not be added
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
Labels: bug

#3823 WFS / Download improvements
  web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
  web-ui/src/main/resources/catalog/components/viewer/wfs/WfsDirective.js
  web-ui/src/main/resources/catalog/components/viewer/wfs/WfsService.js
  web-ui/src/main/resources/catalog/components/viewer/wfs/partials/download.html
  web-ui/src/main/resources/catalog/locales/en-core.json
Labels: bug, enhancement

#3654 #3653: Allow using siteId from MEF when importing records (GUI)
  web-ui/src/main/resources/catalog/templates/editor/import.html
Labels: backport-3.6.x, bug

#3628 User / Delete / When user own some records and can't be deleted, report records owned by the user in the error message
  services/src/main/java/org/fao/geonet/api/users/UsersApi.java
  web-ui/src/main/resources/catalog/components/search/searchmanager/partials/searchresults.html
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/style/gn_editor.less
Labels: enhancement

#3576 [BP] Fixes link to XML in editor
  web-ui/src/main/resources/catalog/locales/ca-editor.json
  web-ui/src/main/resources/catalog/locales/cs-editor.json
  web-ui/src/main/resources/catalog/locales/de-editor.json
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/locales/es-editor.json
  web-ui/src/main/resources/catalog/locales/fi-editor.json
  web-ui/src/main/resources/catalog/locales/fr-editor.json
  web-ui/src/main/resources/catalog/locales/is-editor.json
  web-ui/src/main/resources/catalog/locales/it-editor.json
  web-ui/src/main/resources/catalog/locales/ko-editor.json
  web-ui/src/main/resources/catalog/locales/nl-editor.json
  web-ui/src/main/resources/catalog/locales/ru-editor.json
  web-ui/src/main/resources/catalog/locales/sk-editor.json
  web-ui/src/main/resources/catalog/locales/zh-editor.json
Labels: backport-3.6.x, bug

#3577 [BP] Fixes link to XML in editor
  web-ui/src/main/resources/catalog/locales/ca-editor.json
  web-ui/src/main/resources/catalog/locales/cs-editor.json
  web-ui/src/main/resources/catalog/locales/de-editor.json
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/locales/es-editor.json
  web-ui/src/main/resources/catalog/locales/fi-editor.json
  web-ui/src/main/resources/catalog/locales/fr-editor.json
  web-ui/src/main/resources/catalog/locales/is-editor.json
  web-ui/src/main/resources/catalog/locales/it-editor.json
  web-ui/src/main/resources/catalog/locales/ko-editor.json
  web-ui/src/main/resources/catalog/locales/nl-editor.json
  web-ui/src/main/resources/catalog/locales/ru-editor.json
  web-ui/src/main/resources/catalog/locales/sk-editor.json
  web-ui/src/main/resources/catalog/locales/zh-editor.json
Labels: backport-3.4.5, bug

#3810 Improvements in transfer ownership dialog usability
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
  web-ui/src/main/resources/catalog/components/metadataactions/partials/transferownership.html
Labels: backport-3.6.x, bug

#3856 Add thesaurus title as an Anchor when adding iso19139 in Anchor mode
  schemas/iso19139/src/main/plugin/iso19139/convert/thesaurus-transformation.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
  schemas/iso19139/src/main/plugin/iso19139/update-fixed-info-keywords.xsl
Labels: schema plugin change

#3817 Editor / Link to dataset / Init uuid correctly, Add support for WFS and ATOM services
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Labels: bug

#3656 #3655: Use siteId when importing MEF files
  core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
Labels: backport-3.6.x, bug

#3766 INSPIRE / Validation / Convert non ISO19139 records in order to do remote validation
  services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
  web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js
Labels: enhancement

#3714 ISO19139 / Formatter / JSON-LD
  schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  services/src/test/java/org/fao/geonet/api/records/formatters/ListFormattersIntegrationTest.java
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-variables.xsl
Labels: enhancement

#3736 [BP 3.6.x] Editor / Missing asterisk on + action when cardinality is 1..n
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-date.xsl
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: backport-3.6.x

#3738 [BP 3.6.x] 3452 - Hide remove button from mandatory fields: fix for children of not mad…
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: backport-3.6.x

#3804 Editor / Associated resources / Online source
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/style/gn_editor.less
Labels: enhancement

#3863 ES / Update to 7.1.1
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  core/src/main/java/org/fao/geonet/kernel/search/log/QueryRequest.java
  es/config/features.json
  es/config/records.json
  es/config/searchlogs.json
  es/es-core/src/main/java/org/fao/geonet/es/EsClient.java
  es/es-dashboards/README.md
  es/es-dashboards/data/export.json
  es/es-dashboards/data/index-dashboards-mapping.json
  es/es-dashboards/data/index-dashboards.json
  es/es-dashboards/pom.xml
  es/pom.xml
  pom.xml
  web-ui/src/main/resources/catalog/components/index/IndexRequest.js
  web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js
  web-ui/src/main/resources/catalog/js/admin/DashboardController.js
  workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
Labels: enhancement

#3864 ISO19110 / Populate columns and codelist values from CSV
  schemas/config-editor.xsd
  schemas/iso19110/src/main/plugin/iso19110/layout/config-editor.xml
  schemas/iso19110/src/main/plugin/iso19110/process/add-columns-from-csv.xsl
  schemas/iso19110/src/main/plugin/iso19110/process/add-values-from-csv.xsl
  schemas/iso19110/src/main/plugin/iso19110/suggest.xsl
  web-ui/src/main/resources/catalog/components/edit/suggestion/SuggestionDirective.js
  web-ui/src/main/resources/catalog/components/edit/suggestion/partials/runprocess.html
  web-ui/src/main/resources/catalog/components/edit/suggestion/partials/suggestbutton.html
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
  web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
Labels: enhancement

#3841 Update JDK 8 instructions
  software_development/README.md
Labels: enhancement

#3890 add validation panel to sidepanel in all iso19110 views
  schemas/iso19110/src/main/plugin/iso19110/layout/config-editor.xml
Labels: enhancement

#3888 fixes loading of wmts, if wmts layer has no style object
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
Labels: bug

#3855 Add support for anchors in protocol
  schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
Labels: enhancement

#3758 Metadata editor - associated panel - allow configuration of required flag for the form fields
  schemas/iso19139/src/main/plugin/iso19139/config/associated-panel/default.json
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
Labels: enhancement

#3622 Optimisation attempts
  common/src/main/java/org/fao/geonet/utils/Xml.java
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
Labels: enhancement
