Repository geonetwork/core-geonetwork, pull requests merged in 2019-01, with the labels that each got.

#3390 Larger map for editor on small screens
  web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Labels: enhancement

#3392 Fix a bug handling initial value of `ui/config` setting
  web-ui/src/main/resources/catalog/components/admin/uiconfig/UiConfigDirective.js
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
Labels: bug

#3395 Library / Moment.js / Update to 2.23.0.
  web-ui/src/main/resources/catalog/lib/moment+langs.min.js
Labels: enhancement

#3397 Record history and tasks / Misc fix
  domain/src/main/java/org/fao/geonet/repository/MetadataStatusRepositoryImpl.java
  web-ui/src/main/resources/catalog/components/history/GnHistoryDirective.js
  web-ui/src/main/resources/catalog/components/history/partials/historyStep.html
  web-ui/src/main/resources/catalog/components/history/partials/recordHistory.html
Labels: bug

#3405 Fixes harvester type names not translated (#3362) / Fix missing label
  web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
Labels: bug

#3403 UI Improvements to the admin interface
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/admin.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-report.html
  web-ui/src/main/resources/catalog/templates/admin/page-layout.html
  web-ui/src/main/resources/catalog/templates/admin/settings/cssstyle.html
  web-ui/src/main/resources/catalog/templates/admin/settings/logo.html
  web-ui/src/main/resources/catalog/templates/admin/settings/mapservers.html
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
  web-ui/src/main/resources/catalog/templates/admin/settings/ui.html
  web-ui/src/main/resources/catalog/templates/admin/tools/transferownership.html
  web-ui/src/main/resources/catalog/templates/top-toolbar.html
  web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
  web/src/main/webapp/xslt/ui-admin/admin.xsl
Labels: enhancement

#3402 added dutch translation to iso19139 processes
  schemas/iso19139/src/main/plugin/iso19139/process/add-extent-from-geokeywords.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/add-info-from-wms.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/add-resource-id.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/add-service-info-from-wxs.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/inspire-add-conformity.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/inspire-add-dq-toporeport.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/inspire-themes-and-topiccategory.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/keywords-comma-exploder.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/linked-data-checker.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/related-metadata-checker.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/vacuum.xsl
Labels: enhancement

#3401 Map / Restore layer style.
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
  web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
Labels: enhancement

#3410 Editor / Link list / Remove duplicated protocol icon
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
Labels: bug

#3411 Fix for too small maps in the editor
  web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Labels: bug

#3420 ISO19139 / ISO website is now available with HTTPs
  schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml
Labels: enhancement

#3417 Build / Fix maven warning
  workers/wfsfeature-harvester/pom.xml
Labels: enhancement

#3416 Map viewer not zooming to context extent
  web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
Labels: bug

#3414 Fix: Decrease the `z-index` of the draw map elements in the editor
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/style/gn_editor.less
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Labels: enhancement

#3428 Wro4j / Add a resource processor to remove sourceMappingURL annotations
  web/src/main/webResources/WEB-INF/wro.properties
  wro4j/src/main/java/org/fao/geonet/wro4j/GeonetworkWrojModelFactoryProvider.java
  wro4j/src/main/java/org/fao/geonet/wro4j/RemoveSourceMapUrlProcessor.java
  wro4j/src/test/java/org/fao/geonet/wro4j/RemoveSourceMapUrlProcessorTest.java
Labels: enhancement

#3429 Editor / Region selector / Add an optional attribute to set the default
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Labels: enhancement

#3430 Admin console / Move standard 1st level tab to metadata section.
  web-ui/src/main/resources/catalog/js/GnAdminMenu.js
  web-ui/src/main/resources/catalog/js/admin/AdminController.js
  web-ui/src/main/resources/catalog/js/admin/AdminMetadataController.js
  web-ui/src/main/resources/catalog/js/admin/StandardsController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/metadata/metadata-and-template.html
  web-ui/src/main/resources/catalog/templates/admin/metadata/standards.html
Labels: enhancement

#3438 Broken Thesaurus page in the admin #3436
  web-ui/src/main/resources/catalog/js/admin/ThesaurusController.js
Labels: bug

#3439 Admin console / Restore message suggesting to load samples & template when empty the catalogue is.
  web-ui/src/main/resources/catalog/templates/admin/admin.html
Labels: bug

#3431 Editor / Codelist / Hide in edit mode when configured
  web-ui/src/main/resources/catalog/components/search/formfields/partials/schemainfocombo.html
Labels: enhancement

#3418 Batch editing / List of selected record is invalid
  web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/templates/editor/batchedit.html
Labels: bug

#3427 Editor / Bbox / Do not show projection selector if there is only one.
  web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html
Labels: enhancement

#3424 No JS mode / update html-only header/footer to match more closely the ng-header.
  web-ui/src/main/resources/catalog/style/gn_search.less
  web/src/main/webapp/xslt/base-layout.xsl
  web/src/main/webapp/xslt/common/render-html.xsl
  web/src/main/webapp/xslt/skin/default/skin.xsl
Labels: enhancement

#3426 Editor / When label are placed above field, the offset of action button should be removed to keep all aligned left
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Labels: enhancement

#3446 Match the dropdown menu colours in the admin with the sidebar colours
  web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
Labels: enhancement

#3447 Align facet toggle buttons to the left
  web-ui/src/main/resources/catalog/components/search/facets/partials/dimension-facet-list.html
Labels: enhancement

#3450 Re-arrange the elements in the advanced search form
  web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
  web-ui/src/main/resources/catalog/views/default/templates/advancedSearchForm/defaultAdvancedSearchForm.html
Labels: enhancement

#3449 Harvester / Runtime exception on startup with non escaped character
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswParams.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/GeoPRESTParams.java
Labels: bug

#3453 Small improvements to the mini map on the search results page
  web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
  web-ui/src/main/resources/catalog/views/default/templates/results.html
Labels: enhancement

#3285 Load static pages into GeoNetwork
  domain/src/main/java/org/fao/geonet/domain/page/Page.java
  domain/src/main/java/org/fao/geonet/domain/page/PageIdentity.java
  domain/src/main/java/org/fao/geonet/repository/page/PageRepository.java
  services/src/main/java/org/fao/geonet/api/pages/PageJSONWrapper.java
  services/src/main/java/org/fao/geonet/api/pages/PagesAPI.java
  web-ui/src/main/resources/catalog/components/pages/GnStaticPagesDirective.js
  web-ui/src/main/resources/catalog/components/pages/GnStaticPagesModule.js
  web-ui/src/main/resources/catalog/components/pages/partials/content.html
  web-ui/src/main/resources/catalog/components/pages/partials/footer.html
  web-ui/src/main/resources/catalog/components/pages/partials/menu.html
  web-ui/src/main/resources/catalog/components/pages/partials/top.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/js/search/SearchController.js
  web-ui/src/main/resources/catalog/templates/top-toolbar.html
  web-ui/src/main/resources/catalog/views/default/templates/footer.html
  web-ui/src/main/resources/catalog/views/default/templates/index.html
  web-ui/src/main/resources/catalog/views/default/templates/page.html
  web/src/main/webResources/WEB-INF/urlrewrite.xml
Labels: enhancement

#3298 Editor / Inline validation errors
  common/src/main/java/org/fao/geonet/utils/Xml.java
  common/src/main/java/org/fao/geonet/utils/XmlErrorHandler.java
  core/src/main/java/org/fao/geonet/constants/Edit.java
  core/src/main/java/org/fao/geonet/kernel/DataManager.java
  core/src/main/java/org/fao/geonet/kernel/EditLib.java
  core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
  core/src/main/java/org/fao/geonet/kernel/SchematronValidator.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataValidator.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseErrorHandlerAttachingErrorToElem.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
  installer/installer-config.xml
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/schematron-rules-iso.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/schematron-rules-inspire-strict.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/schematron-rules-inspire.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/schematron-rules-iso.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/schematron-rules-url-check.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ger/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-geonetwork.sch
  schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-inspire-sds.sch
  schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-inspire-strict.sch
  schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-inspire.sch
  schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-iso.sch
  schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-url-check.sch
  services/src/main/java/org/fao/geonet/api/processing/ValidateApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
  services/src/main/java/org/fao/geonet/api/records/editing/AjaxEditUtils.java
  services/src/main/java/org/fao/geonet/api/records/editing/EditUtils.java
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
  services/src/main/java/org/fao/geonet/services/metadata/Publish.java
  services/src/main/java/org/fao/geonet/services/metadata/Update.java
  services/src/main/java/org/fao/geonet/services/metadata/UpdateAdminOper.java
  services/src/main/java/org/fao/geonet/services/metadata/ValidationService.java
  web-ui/src/main/resources/catalog/components/edit/validationreport/ValidationReportDirective.js
  web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
  web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
  web-ui/src/main/resources/catalog/components/utility/UtilityService.js
  web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js
  web-ui/src/main/resources/catalog/components/validationtools/partials/mdValidationTools.html
  web-ui/src/main/resources/catalog/js/edit/EditorController.js
  web-ui/src/main/resources/catalog/locales/fr-editor.json
  web-ui/src/main/resources/catalog/templates/editor/top-toolbar.html
  web/src/main/webapp/WEB-INF/classes/schematron/iso_svrl_for_xslt2.xsl
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v350/migrate-default.sql
  web/src/main/webapp/xslt/common/functions-metadata.xsl
  web/src/main/webapp/xslt/common/utility-tpl-metadata.xsl
  web/src/main/webapp/xslt/services/metadata/validate-fn.xsl
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
  web/src/test/java/org/fao/geonet/kernel/schema/BasicInspireTest.java
  web/src/test/java/org/fao/geonet/kernel/schema/StrictInspireTest.java
  web/src/test/resources/org/fao/geonet/kernel/schema/inspire-valid-iso19139.xml
Labels: enhancement, schema plugin change

#3462 Update from transifex
  web-ui/src/main/resources/catalog/locales/ca-admin.json
  web-ui/src/main/resources/catalog/locales/ca-editor.json
  web-ui/src/main/resources/catalog/locales/es-admin.json
  web-ui/src/main/resources/catalog/locales/es-core.json
  web-ui/src/main/resources/catalog/locales/es-editor.json
  web-ui/src/main/resources/catalog/locales/fi-admin.json
  web-ui/src/main/resources/catalog/locales/fi-editor.json
  web-ui/src/main/resources/catalog/locales/fr-admin.json
  web-ui/src/main/resources/catalog/locales/fr-editor.json
  web-ui/src/main/resources/catalog/locales/is-admin.json
  web-ui/src/main/resources/catalog/locales/is-editor.json
  web-ui/src/main/resources/catalog/locales/is-search.json
  web-ui/src/main/resources/catalog/locales/it-admin.json
  web-ui/src/main/resources/catalog/locales/it-editor.json
  web-ui/src/main/resources/catalog/locales/ko-admin.json
  web-ui/src/main/resources/catalog/locales/ko-core.json
  web-ui/src/main/resources/catalog/locales/ko-editor.json
  web-ui/src/main/resources/catalog/locales/nl-admin.json
  web-ui/src/main/resources/catalog/locales/nl-editor.json
  web-ui/src/main/resources/catalog/locales/ru-admin.json
  web-ui/src/main/resources/catalog/locales/ru-editor.json
  web-ui/src/main/resources/catalog/locales/sk-admin.json
  web-ui/src/main/resources/catalog/locales/sk-editor.json
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: enhancement

#3465 Language selector is not displayed
  web-ui/src/main/resources/catalog/js/CatController.js
Labels: bug

#3470 Batch editor / Display all type of updates when selection is too big
  web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
Labels: bug

#3476 User administrator can delete his own group
  services/src/main/java/org/fao/geonet/api/groups/GroupsApi.java
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
  web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
Labels: enhancement

#3504 Metadata editor - Create metadata with custom uuid from template gets an autogenerated uuid #3502
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Labels: backport-3.6.x

#3200 Updated avalon-framework dependencies
  pom.xml
Labels: enhancement
