Repository geonetwork/core-geonetwork, pull requests merged in 2019-04, with the labels that each got.

#3706 ISO19139 / Geometry object count is not multilingual
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
Labels: enhancement

#3716 Missing tooltip icon for date fields in templates
  web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
Labels: bug

#3724 [BP 3.6.x] - 3723 - Use correct siteURL in sitemap urls
  web/src/main/webapp/xslt/services/sitemap/sitemap.xsl
Labels: backport-3.6.x

#3730 Migration API - NullPointerException when executing a database migration task. Fixes #3729
  services/src/main/java/org/fao/geonet/api/tools/migration/MigrationApi.java
Labels: bug

#3731 [BP] Migration API - NullPointerException when executing a database migration task. Fixes #3729
  services/src/main/java/org/fao/geonet/api/tools/migration/MigrationApi.java
Labels: backport-3.6.x

#3720 Externalise metadata editor associated resources panel configuration in schemas and display fields in the dialog using the order defined in the configuration file
  core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
  core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchema.java
  schemas/dublin-core/src/main/plugin/dublin-core/config/associated-panel/default.json
  schemas/iso19110/src/main/plugin/iso19110/config/associated-panel/default.json
  schemas/iso19139/src/main/plugin/iso19139/config/associated-panel/default.json
  services/src/main/java/org/fao/geonet/api/standards/StandardsApi.java
  web-ui/src/main/resources/catalog/components/common/schemamanager/SchemaManagerService.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
  web-ui/src/main/resources/catalog/js/edit/EditorController.js
Labels: enhancement, schema plugin change

#3733 DatabaseMigration tasks doesn't save changes in the database. Fixes #3732
  services/src/main/java/org/fao/geonet/api/tools/migration/MigrationApi.java
Labels: bug

#3734 [BP] DatabaseMigration tasks doesn't save changes in the database. Fixes #3732
  services/src/main/java/org/fao/geonet/api/tools/migration/MigrationApi.java
Labels: backport-3.6.x

#3717 Directive for switching between Anchor and CharacterString
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
  web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
  web-ui/src/main/resources/catalog/components/edit/FieldsModule.js
  web-ui/src/main/resources/catalog/components/edit/anchorswitcher/AnchorSwitcher.js
  web-ui/src/main/resources/catalog/components/edit/anchorswitcher/partials/anchorswitcher.html
  web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: enhancement

#3692 Schematron / Add criteria to filter on user main profile.
  domain/src/main/java/org/fao/geonet/domain/SchematronCriteriaType.java
  schemas/iso19139/src/main/plugin/iso19139/schematron/criteria-type.xml
Labels: enhancement

#3726 A11y upgrade for the header and footer
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/templates/top-toolbar.html
  web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
  web-ui/src/main/resources/catalog/views/default/templates/footer.html
Labels: enhancement

#3697 Small styling changes for the alert messages
  web-ui/src/main/resources/catalog/views/default/less/gn_alerts_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_login_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
Labels: enhancement

#3728 A11y upgrade for the Search Result and Detail page
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
  web-ui/src/main/resources/catalog/components/viewer/owscontext/partials/owscontext.html
  web-ui/src/main/resources/catalog/style/gn_search.less
  web-ui/src/main/resources/catalog/views/default/directives/partials/linksbtn.html
  web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
  web-ui/src/main/resources/catalog/views/default/templates/home.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Labels: enhancement

#3575 Fixes link to XML tab in editor error message.
  web-ui/src/main/resources/catalog/locales/ca-editor.json
  web-ui/src/main/resources/catalog/locales/cs-editor.json
  web-ui/src/main/resources/catalog/locales/de-editor.json
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/locales/es-editor.json
  web-ui/src/main/resources/catalog/locales/fi-editor.json
  web-ui/src/main/resources/catalog/locales/fr-editor.json
  web-ui/src/main/resources/catalog/locales/is-editor.json
  web-ui/src/main/resources/catalog/locales/it-editor.json
  web-ui/src/main/resources/catalog/locales/ko-editor.json
  web-ui/src/main/resources/catalog/locales/nl-editor.json
  web-ui/src/main/resources/catalog/locales/ru-editor.json
  web-ui/src/main/resources/catalog/locales/sk-editor.json
  web-ui/src/main/resources/catalog/locales/zh-editor.json
Labels: bug

#3718 User custom searches
  domain/src/main/java/org/fao/geonet/domain/UserSearch.java
  domain/src/main/java/org/fao/geonet/domain/UserSearchFeaturedType.java
  domain/src/main/java/org/fao/geonet/domain/converter/UserSearchFeaturedTypeConverter.java
  domain/src/main/java/org/fao/geonet/entitylistener/UserSearchEntityListenerManager.java
  domain/src/main/java/org/fao/geonet/repository/UserSearchRepository.java
  domain/src/main/java/org/fao/geonet/repository/specification/UserSearchSpecs.java
  domain/src/test/java/org/fao/geonet/repository/UserSearchRepositoryTest.java
  services/src/main/java/org/fao/geonet/api/usersearches/UserSearchesApi.java
  services/src/main/java/org/fao/geonet/api/usersearches/model/PaginatedUserSearchResponse.java
  services/src/main/java/org/fao/geonet/api/usersearches/model/UserSearchDto.java
  services/src/test/java/org/fao/geonet/api/usersearches/UserSearchesApiTest.java
  web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
  web-ui/src/main/resources/catalog/components/usersearches/UserSearchesDirective.js
  web-ui/src/main/resources/catalog/components/usersearches/UserSearchesModule.js
  web-ui/src/main/resources/catalog/components/usersearches/UserSearchesService.js
  web-ui/src/main/resources/catalog/components/usersearches/partials/featuredusersearcheshome.html
  web-ui/src/main/resources/catalog/components/usersearches/partials/saveusersearch.html
  web-ui/src/main/resources/catalog/components/usersearches/partials/usersearchesmanager.html
  web-ui/src/main/resources/catalog/components/usersearches/partials/usersearchespanel.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/js/search/SearchController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
  web-ui/src/main/resources/catalog/views/default/templates/home.html
  web-ui/src/main/resources/catalog/views/default/templates/results.html
  web/src/main/webResources/WEB-INF/config-db/database_migration.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v370/UserCustomSearchesMigration.java
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
  web/src/test/java/v370/UserCustomSearchesMigrationTest.java
Labels: enhancement

#3761 Fixes empty owner select in admin's batch process
  web-ui/src/main/resources/catalog/js/admin/AdminToolsController.js
  web-ui/src/main/resources/catalog/templates/admin/tools/batch.html
Labels: bug

#3739 Settings to switch between fluid and fixed width container/layout
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/editor/editor.html
  web-ui/src/main/resources/catalog/templates/editor/editorboard.html
  web-ui/src/main/resources/catalog/views/default/module.js
  web-ui/src/main/resources/catalog/views/default/templates/home.html
  web-ui/src/main/resources/catalog/views/default/templates/results.html
  web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Labels: enhancement

#3768 Fixes test for additional criteria type
  services/src/test/java/org/fao/geonet/services/metadata/schema/SchematronCriteriaTypeServiceTest.java
Labels: bug

#3767 Option for updating the modified date in batch edits
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
  services/src/main/java/org/fao/geonet/api/ApiParams.java
  services/src/main/java/org/fao/geonet/api/records/editing/BatchEditsApi.java
  web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/templates/editor/batchedit.html
Labels: enhancement

#3779 WFS Feature indexer / Tokenized field may contains CDATA
  workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
Labels: bug

#3777 ISO19139 / Schematron / Check only http urls
  schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-url-check.sch
Labels: enhancement

#3745 Access manager / Intranet group not found when using canDownload/Dynamic
  core/src/main/java/org/fao/geonet/kernel/AccessManager.java
Labels: bug
