Repository geonetwork/core-geonetwork, pull requests merged in 2019-08, with the labels that each got.

#3953 Editing / Update-fixed-info applies to template
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
Labels: enhancement

#3955 Fix NullPointerException when server doesn't redirect
  core/src/main/java/jeeves/config/springutil/JeevesDispatcherServlet.java
Labels: bug

#3958 Remove duplicated element entries in Dutch labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/dut/labels.xml
Labels: bug

#3960 ES / Update to 7.3.0.
  pom.xml
Labels: enhancement

#3959 [BP] Remove duplicated element entries in Dutch labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/dut/labels.xml
Labels: bug

#3957 Portal / Add portal filter to CSW queries.
  core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
  csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/CatalogSearcher.java
Labels: bug

#3956 Import record / Generate UUID return ResourceNotFoundException
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Labels: bug

#3868 Link checker
  core/src/main/java/org/fao/geonet/kernel/url/UrlAnalyzer.java
  core/src/main/java/org/fao/geonet/kernel/url/UrlChecker.java
  core/src/main/resources/config-spring-geonetwork.xml
  core/src/test/java/org/fao/geonet/kernel/url/LinkPresenterTest.java
  core/src/test/java/org/fao/geonet/kernel/url/UrlAnalyzerTest.java
  core/src/test/java/org/fao/geonet/kernel/url/UrlCheckerTest.java
  domain/src/main/java/org/fao/geonet/domain/Link.java
  domain/src/main/java/org/fao/geonet/domain/LinkStatus.java
  domain/src/main/java/org/fao/geonet/domain/LinkType.java
  domain/src/main/java/org/fao/geonet/domain/MetadataLink.java
  domain/src/main/java/org/fao/geonet/domain/MetadataLinkId.java
  domain/src/main/java/org/fao/geonet/domain/converter/LinkTypeConverter.java
  domain/src/main/java/org/fao/geonet/entitylistener/LinkEntityListenerManager.java
  domain/src/main/java/org/fao/geonet/entitylistener/LinkStatusEntityListenerManager.java
  domain/src/main/java/org/fao/geonet/entitylistener/MetadataLinkEntityListenerManager.java
  domain/src/main/java/org/fao/geonet/repository/LinkRepository.java
  domain/src/main/java/org/fao/geonet/repository/LinkRepositoryCustom.java
  domain/src/main/java/org/fao/geonet/repository/LinkRepositoryImpl.java
  domain/src/main/java/org/fao/geonet/repository/LinkStatusRepository.java
  domain/src/main/java/org/fao/geonet/repository/LinkStatusRepositoryCustom.java
  domain/src/main/java/org/fao/geonet/repository/LinkStatusRepositoryImpl.java
  domain/src/main/java/org/fao/geonet/repository/MetadataLinkRepository.java
  domain/src/main/java/org/fao/geonet/repository/MetadataLinkRepositoryCustom.java
  domain/src/main/java/org/fao/geonet/repository/MetadataLinkRepositoryImpl.java
  schemas/iso19139/pom.xml
  schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java
  schemas/iso19139/src/main/resources/config-spring-geonetwork.xml
  schemas/iso19139/src/test/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPluginTest.java
  schemas/iso19139/src/test/java/org/fao/geonet/schemas/ExtractLinksTest.java
  schemas/iso19139/src/test/java/org/fao/geonet/schemas/OnlineSrcAddProcessTest.java
  schemas/iso19139/src/test/resources/org/fao/geonet/schemas/xsl/process/input_with_url.xml
  schemas/schema-core/pom.xml
  schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/HttpLink.java
  schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/LinkAwareSchemaPlugin.java
  schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/LinkPatternStreamer/ILinkBuilder.java
  schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/LinkPatternStreamer/RawLinkPatternStreamer.java
  schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/SchemaPlugin.java
  schemas/schema-core/src/test/java/org/fao/geonet/schemas/XslProcessTest.java
  services/src/main/java/org/fao/geonet/api/links/LinksApi.java
  services/src/main/java/org/fao/geonet/api/links/model/LinkDto.java
  services/src/main/java/org/fao/geonet/api/links/model/PaginatedLinksResponse.java
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
  services/src/main/java/org/fao/geonet/api/registries/DirectoryApi.java
  services/src/test/java/org/fao/geonet/api/links/LinksApiTest.java
  web-ui/src/main/resources/catalog/js/admin/DashboardController.js
  web-ui/src/main/resources/catalog/js/admin/DashboardRecordLinkController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/style/gn_admin.less
  web-ui/src/main/resources/catalog/templates/admin/dashboard/record-links.html
Labels: enhancement, schema plugin change

#3951 ISO19110 : display information about feature types in default view (recordView.html)
  schemas/iso19110/src/main/plugin/iso19110/index-fields/default.xsl
  web-ui/src/main/resources/catalog/locales/ca-core.json
  web-ui/src/main/resources/catalog/locales/cs-core.json
  web-ui/src/main/resources/catalog/locales/de-core.json
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/locales/es-core.json
  web-ui/src/main/resources/catalog/locales/fi-core.json
  web-ui/src/main/resources/catalog/locales/fr-core.json
  web-ui/src/main/resources/catalog/locales/is-core.json
  web-ui/src/main/resources/catalog/locales/it-core.json
  web-ui/src/main/resources/catalog/locales/ko-core.json
  web-ui/src/main/resources/catalog/locales/nl-core.json
  web-ui/src/main/resources/catalog/locales/ru-core.json
  web-ui/src/main/resources/catalog/locales/sk-core.json
  web-ui/src/main/resources/catalog/locales/zh-core.json
  web-ui/src/main/resources/catalog/views/default/directives/partials/attributetable.html
  web-ui/src/main/resources/catalog/views/default/less/gn_view.less
  web-ui/src/main/resources/catalog/views/default/templates/recordView.html
  web/src/main/webapp/WEB-INF/config-lucene.xml
Labels: schema plugin change

#3962 Editor / Using thesaurus on element with same name does not work.
  schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
  web/src/main/webapp/xslt/common/functions-metadata.xsl
Labels: bug

#3971 Record view / Angular view increase popularity.
  services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
Labels: enhancement

#3972 Fix rating issue
  core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
Labels: bug

#3980 Draft copy - As a reviewer or an Editor, it is impossible to open the editor on a record with a draft copy attached to it Fixes #3896
  core/src/main/resources/config-spring-geonetwork.xml
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
Labels: bug

#3978 Editor / Table mode / Add option to not to have a fieldset around the table
  schemas/config-editor.xsd
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl
Labels: enhancement, schema plugin change

#3987 Map / Print / Translate layout
  web-ui/src/main/resources/catalog/components/common/map/print/partials/printmap.html
  web-ui/src/main/resources/catalog/locales/en-search.json
Labels: enhancement

#3986 WFS harvester / SLD / Send GetStyle request with direct httpClient
  core/src/main/java/org/geonetwork/map/wms/SLDUtil.java
  core/src/test/java/org/geonetwork/map/wms/SLDUtilTest.java
  services/src/main/java/org/fao/geonet/api/sld/SldApi.java
Labels: enhancement

#3988 Map / Cache getcapabilities parsing.
  web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
Labels: enhancement

#3989 Editor / Documentation / How to customize associated panel list of link types ?
  schemas/config-editor.xsd
Labels: enhancement

#3981 Editor / Associated resources / Set default value to action
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
  web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
Labels: enhancement
