Repository geonetwork/core-geonetwork, pull requests merged in 2019-07, with the labels that each got.

#3906 Disable InspireValidatorUtilsTest#testLifeCycle test
  services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
Labels: bug

#3903 remove microdata,
  schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
Labels: enhancement

#3905 Editing / Cancel / Restore the change date as it was before the editing
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
Labels: bug

#3908 Search results / Add template to display related record as list instead of dropdown
  web-ui/src/main/resources/catalog/components/search/resultsview/gridRelated.js
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/style/gn_search.less
  web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
  web-ui/src/main/resources/catalog/views/default/templates/gridRelatedList.html
Labels: enhancement

#3917 Editor / Field with autocompletion / Multilingual record
  web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
Labels: bug

#3915 Editor / Validation / INSPIRE / Add support for TG2
  services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
  services/src/main/java/org/fao/geonet/api/records/editing/InspireValidatorUtils.java
  services/src/main/resources/config-spring-geonetwork.xml
  services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
  web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js
  web-ui/src/main/resources/catalog/components/validationtools/partials/mdValidationTools.html
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
Labels: enhancement

#3927 Paginate GeoNetwork type harvester
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/RecordInfo.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Search.java
Labels: bug

#3928 [BP] Paginate GeoNetwork type harvester
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/RecordInfo.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Search.java
Labels: bug

#3929 Fix NullPointerException in InspireValidatorUtilsTest
  services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
Labels: bug

#3932 [BUG] - Load schema related oasis-catalog in Resolver
  common/src/main/java/org/fao/geonet/utils/Resolver.java
  common/src/main/java/org/fao/geonet/utils/ResolverWrapper.java
  common/src/main/java/org/fao/geonet/utils/Xml.java
  core/src/main/java/jeeves/server/JeevesProxyInfo.java
  core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
Labels: bug

#3925 ISO19139 / Format / nilReason is set to unknown when missing
  schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v370/migrate-default.sql
Labels: enhancement

#3937 Allow subtemplates to specify uuid and title as attributes on root element
  services/src/main/java/org/fao/geonet/api/records/MetadataSampleApi.java
Labels: enhancement

#3936 Modernise and Simplify THREDDS Harvester
  core/pom.xml
  core/src/main/java/org/fao/geonet/constants/Geonet.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/ThreddsHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/ThreddsParams.java
  harvesters/src/main/java/org/fao/geonet/services/harvesting/Info.java
  pom.xml
  schemas/iso19139/src/main/plugin/iso19139/convert/ThreddsCatalogto19119/ThreddsCatalog-to-19119.xsl
  schemas/iso19139/src/main/plugin/iso19139/convert/ThreddsCatalogto19119/ThreddsCatalog-to-19139.xsl
  schemas/iso19139/src/main/plugin/iso19139/convert/ThreddsCatalogto19119/identification.xsl
  schemas/iso19139/src/main/plugin/iso19139/convert/ThreddsCatalogto19119/ref-system.xsl
  schemas/iso19139/src/main/plugin/iso19139/convert/ThreddsCatalogto19119/resp-party.xsl
  schemas/iso19139/src/main/plugin/iso19139/convert/ThreddsDIFToISO/CDMCoords-to-ISO19139Keywords.xsl
  schemas/iso19139/src/main/plugin/iso19139/convert/ThreddsDIFToISO/DIFToISO.xsl
  schemas/iso19139/src/main/plugin/iso19139/convert/ThreddsToFragments/netcdf-attributes.xsl
  schemas/iso19139/src/main/plugin/iso19139/convert/ThreddsToFragments/thredds-metadata.xsl
  schemas/iso19139/src/main/plugin/iso19139/convert/ThreddsToFragments/thredds/utils.xsl
  schemas/iso19139/src/main/plugin/iso19139/templates/thredds-harvester-unidata-data-discovery.xml
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/thredds.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/thredds.js
  web/pom.xml
  web/src/main/webapp/xsl/xml/harvesting/thredds.xsl
Labels: enhancement

#3939 Fix error when sch:assert/@see attribute contains a URL
  web/src/main/webapp/WEB-INF/classes/schematron/iso_svrl_for_xslt2.xsl
Labels: bug

#3911 Editor / Anchor support / Improve layout
  schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
  web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: enhancement

#3909 Record view / Use location when setting a formatter
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/geocat.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/sextant.html
  web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/js/GnFormatterViewerModule.js
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/templates/formatter-viewer.html
  web-ui/src/main/resources/catalog/views/default/directives/directive.js
  web-ui/src/main/resources/catalog/views/default/directives/partials/infolist.html
  web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
  web-ui/src/main/resources/catalog/views/default/module.js
  web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Labels: enhancement

#3940 [BP] Fix error when sch:assert/@see attribute contains a URL
  web/src/main/webapp/WEB-INF/classes/schematron/iso_svrl_for_xslt2.xsl
Labels: backport-3.6.x, bug

#3944 WFS Feature Harvester BUG fix
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/WfsFeaturesParams.java
Labels: bug

#3950 Privileges / Avoid NPE if status is not yet set
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Labels: bug

#3952 Inspire Validator calls now use directly GeonetHttpRequestFactory
  services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
  services/src/main/java/org/fao/geonet/api/records/editing/InspireValidatorUtils.java
  services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
Labels: bug
