Repository geonetwork/core-geonetwork, pull requests merged in 2019-03, with the labels that each got.

#3606 Keyword picker directive values are not sorted by id when using the related configuration. Fixes #3604
  web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusService.js
Labels: backport-3.6.x

#3636 Editor / Topic Category / Support extension of non ISO19139 standards
  web-ui/src/main/resources/catalog/components/edit/topiccategory/TopicCategoryDirective.js
Labels: enhancement

#3458 Multiple UI config support
  core/src/main/java/org/fao/geonet/util/XslUtil.java
  domain/src/main/java/org/fao/geonet/domain/UiSetting.java
  domain/src/main/java/org/fao/geonet/repository/UiSettingsRepository.java
  services/src/main/java/org/fao/geonet/api/uisetting/UiSettingApi.java
  services/src/test/java/org/fao/geonet/api/uisetting/UiApiTest.java
  web-ui/src/main/resources/catalog/components/admin/uiconfig/UiConfigDirective.js
  web-ui/src/main/resources/catalog/js/admin/AdminToolsController.js
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
  web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
  web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/settings/ui.html
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v330/migrate-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v340/migrate-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v370/migrate-default.sql
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
  web/src/main/webapp/xslt/common/base-variables.xsl
Labels: enhancement

#3641 Admin / User / User admin can see all groups
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
Labels: bug

#3629 ISO19139 / Avoid XSL error in case of a language is declared more than once in other locale section.
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl-multilingual.xsl
Labels: enhancement

#3620 Editor / Missing asterisk on + action when cardinality is 1..n.
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-date.xsl
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: bug

#3556 ISO19139 / Directory entry API xlink MUST contains languages in the order defined in the record.
  schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java
  schemas/iso19139/src/main/plugin/iso19139/process/empty.xsl
  schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Labels: bug

#3559 Editor / Tabled mode / Elements children of an xlink must be disabled.
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: bug

#3649 Transfer ownership / Display report at the end of the process.
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
Labels: enhancement

#3647 Translate true/false values on xslt formatter. Fixes #3045
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/loc/ara/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/cat/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/chi/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/dut/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fin/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ger/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ita/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/nor/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/pol/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/por/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/rus/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/slo/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/spa/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/tur/strings.xml
Labels: enhancement

#3505 Bug fix: Info Formats for WMS were not correctly selected.
  web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
Labels: bug

#3670 Mail send fails with java.lang.UnsupportedOperationException: Method not yet implemented. Fixes #3669
  pom.xml
Labels: bug

#3644 Editor board / Fix only my record filter affected by location changes.
  web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
  web-ui/src/main/resources/catalog/templates/editor/editorboard.html
Labels: bug

#3672 [BP] Editor board / Fix only my record filter affected by location changes
  web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
  web-ui/src/main/resources/catalog/templates/editor/editorboard.html
Labels: backport-3.6.x, bug

#3643 Improve memory handling on CSW harvesters
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/AbstractAligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
Labels: CSW, critical, enhancement, good first issue

#3671 Small UI changes to Projection Switcher
  web-ui/src/main/resources/catalog/components/viewer/projectionSwitcher/partials/projectionSwitcher.html
  web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
Labels: enhancement

#3506 fix for #3500 + partial #2688 add kml & geojson link to map
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
Labels: backport-3.6.x, enhancement

#3561 Fix thumbnail remove button
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
Labels: bug

#3220 add warning when layer not in capabilities
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
  web-ui/src/main/resources/catalog/components/viewer/ViewerService.js
  web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
  web-ui/src/main/resources/catalog/locales/en-core.json
Labels: enhancement

#3679 Fixes compile error
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
Labels: bug

#3553 Enable paging and other filters on the DCAT RDF endpoint
  core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
  core/src/main/java/org/fao/geonet/kernel/search/MetaSearcher.java
  core/src/main/java/org/fao/geonet/kernel/search/UnusedSearcher.java
  services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
  services/src/main/java/org/fao/geonet/api/records/rdf/RdfOutputManager.java
  services/src/main/java/org/fao/geonet/api/records/rdf/RdfSearcher.java
Labels: enhancement

#3433 [BUG] - Map background, use default parameter defined in settings
  schemas/iso19139/src/main/plugin/iso19139/formatter/groovy/iso19139/Handlers.groovy
  web/src/main/webapp/WEB-INF/data/data/formatter/html/bbox.html
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
Labels: bug

#3565 improve schema-org mapping
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
  web/src/main/webapp/xslt/ui-search/search-nojs.xsl
Labels: enhancement

#3691 gnMeasure directive removes the value when it's 0 #3689
  web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
Labels: backport-3.6.x

#3683 Search / Add support to negative query on any fields
  core/src/main/java/org/fao/geonet/kernel/search/LuceneQueryBuilder.java
Labels: enhancement

#3686 Upgrade commons-fileupload to 1.3.3
  pom.xml
Labels: backport-3.6.x

#3688 Upgrade jackson dependencies to 2.9.8
  pom.xml
Labels: backport-3.6.x

#3693 Report about failed schematron executions
  core/src/main/java/org/fao/geonet/kernel/SchematronValidator.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
  services/src/main/java/org/fao/geonet/api/records/model/validation/Report.java
  web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
  web-ui/src/main/resources/catalog/components/utility/partials/batchreport.html
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/templates/admin/tools/batch-replacer-report.html
  web/src/main/webapp/xslt/services/metadata/validate.xsl
Labels: bug

#3702 [BP] Report about failed schematron executions
  core/src/main/java/org/fao/geonet/kernel/SchematronValidator.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
  services/src/main/java/org/fao/geonet/api/records/model/validation/Report.java
  web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
  web-ui/src/main/resources/catalog/components/utility/partials/batchreport.html
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/templates/admin/tools/batch-replacer-report.html
  web/src/main/webapp/xslt/services/metadata/validate.xsl
Labels: backport-3.6.x, bug

#3707 [BP] Report about failed schematron executions (#3693)
  core/src/main/java/org/fao/geonet/kernel/DataManager.java
  core/src/main/java/org/fao/geonet/kernel/SchematronValidator.java
  services/src/main/java/org/fao/geonet/api/records/model/validation/Report.java
  web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
  web-ui/src/main/resources/catalog/components/utility/partials/batchreport.html
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/templates/admin/tools/batch-replacer-report.html
  web/src/main/webapp/xslt/services/metadata/validate.xsl
Labels: backport-3.4.5, bug
