Repository geonetwork/core-geonetwork, pull requests merged in 2019-02, with the labels that each got.

#3514 Support year and year/month date formats in ISODate class. Fixes #3511
  domain/src/main/java/org/fao/geonet/domain/ISODate.java
  domain/src/test/java/org/fao/geonet/domain/ISODateTest.java
Labels: backport-3.6.x

#3509 System proxy properties not updated when updating the proxy server in the settings #3507
  core/src/main/java/org/fao/geonet/lib/NetLib.java
  services/src/main/java/org/fao/geonet/api/site/SiteApi.java
Labels: backport-3.6.x

#3523 Enable the DistributedSearch configuration in CSW harvester UI. Fixes #3521
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswParams.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.js
Labels: backport-3.6.x

#3547 Editor / Associated resource / List WMS layer group having name
  web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Labels: enhancement

#3546 Editor / Associated resources / Indicate that association type is mandatory
  web-ui/src/main/resources/catalog/components/edit/datepicker/partials/datepicker.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linktosibling.html
  web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
Labels: enhancement

#3545 Search form / Avoid today to be incremented on each click on the button
  web-ui/src/main/resources/catalog/views/default/directives/directive.js
Labels: bug

#3542 Editor / Associated resource / Protocol might be null and trigger JS error
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
Labels: bug

#3533 ISO19139 / Multilingual record / Preserve order of languages
  schemas/iso19139/src/main/plugin/iso19139/templates/vector-multilingual.xml
  schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: enhancement, schema plugin change

#3557 Associated resource / Sibling / Disable button
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linktosibling.html
Labels: enhancement

#3554 ISO19139 / Other keyword should be displayed in last position in the record view
  schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
  web-ui/src/main/resources/catalog/locales/en-search.json
Labels: enhancement

#3550 Wrap text on button
  web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Labels: enhancement

#3527 Small changes to the history panel styles
  web-ui/src/main/resources/catalog/components/history/partials/history.html
  web-ui/src/main/resources/catalog/components/history/partials/historyStep.html
  web-ui/src/main/resources/catalog/components/history/partials/recordHistory.html
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/style/timeline.less
Labels: enhancement

#3567 Adds a parameter to resetSearch to preserve the geometry on facet filter changes
  web-ui/src/main/resources/catalog/components/search/facets/FacetsConfigService.js
  web-ui/src/main/resources/catalog/components/search/facets/FacetsDirective.js
  web-ui/src/main/resources/catalog/components/search/map/MapFieldDirective.js
  web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
Labels: bug

#3570 [BP] Adds a parameter to resetSearch to preserve the geometry
  web-ui/src/main/resources/catalog/components/search/facets/FacetsConfigService.js
  web-ui/src/main/resources/catalog/components/search/facets/FacetsDirective.js
  web-ui/src/main/resources/catalog/components/search/map/MapFieldDirective.js
  web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
Labels: backport-3.4.5, bug

#3580 Update german translation
  schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml
Labels: enhancement

#3584 Editor / Table / Add support to set header class to customize styling.
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl
  web-ui/src/main/resources/catalog/style/gn_editor.less
Labels: enhancement

#3560 Editor / Associated resource / Display name and description for OGC resources
  web-ui/src/main/resources/catalog/components/common/ows/partials/layersGrid.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
Labels: enhancement

#3571 Makes thesaurus of searchFilterTags configurable
  web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
Labels: bug

#3572 [BP] Makes thesaurus of searchFilterTags configurable
  web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
Labels: backport-3.6.x, bug

#3573 [BP] Makes thesaurus of searchFilterTags configurable
  web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
Labels: backport-3.4.5, bug

#3454 Inspire atom opensearch fixes
  core/src/main/java/org/fao/geonet/constants/Geonet.java
  core/src/main/java/org/fao/geonet/kernel/DataManager.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataUtils.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
  inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java
  inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomPredefinedFeed.java
  inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomSearch.java
  schemas/iso19139/src/main/plugin/iso19139/convert/ATOM/inspire-atom-feed.xsl
  schemas/iso19139/src/main/plugin/iso19139/extract-default-language.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml
  web/src/main/webResources/WEB-INF/urlrewrite.xml
  web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
  web/src/main/webapp/xslt/services/inspire-atom/opensearchdescription.xsl
Labels: enhancement

#3548 Admin / User / Add info on how to add an avatar. Fix alignement.
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: enhancement

#3568 [BP] Adds a parameter to resetSearch to preserve the geometry
  web-ui/src/main/resources/catalog/components/search/facets/FacetsConfigService.js
  web-ui/src/main/resources/catalog/components/search/facets/FacetsDirective.js
  web-ui/src/main/resources/catalog/components/search/map/MapFieldDirective.js
  web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
Labels: backport-3.6.x, bug

#3609 Improve visualisation of projection if codespace is undefined
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
Labels: bug

#3611 [BP] Improve visualisation of projection if codespace is undefined (#3609)
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
Labels: backport-3.6.x

#3562 Search / Advanced form / Dates not updated when using input directly
  web-ui/src/main/resources/catalog/views/default/directives/partials/periodchooser.html
Labels: bug

#3623 before to retrieve validation report from session, have to set it
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
Labels: enhancement

#3608 Better documentation on how to use database listeners
  events/Readme.md
Labels: good first issue

#3558 Search / Sort can't define direction for default value
  web-ui/src/main/resources/catalog/views/default/module.js
Labels: bug
