Repository geonetwork/core-geonetwork, pull requests merged in 2019-10, with the labels that each got.

#4069 Portal list / Force content type to text/html
  services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
Labels: bug

#4073 Admin / Logo / Improve styling
  web-ui/src/main/resources/catalog/style/gn_admin.less
  web-ui/src/main/resources/catalog/templates/admin/settings/logo.html
Labels: enhancement

#4067 Portal / Add message when a portal is empty.
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/admin.html
  web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
  web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
Labels: enhancement

#4063 API / Related / Errors in case a feature catalogue is linked but not found
  services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
Labels: bug, critical

#4066 Harvester / CSW / Add XPath filter
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/HarvestResult.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswParams.java
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.js
  web/src/main/webapp/xsl/xml/harvesting/csw.xsl
Labels: enhancement

#4085 ES / Index health check / Fix due to incompatibility between JEST 6.3.1 and ES 7.x
  healthmonitor/src/main/java/org/fao/geonet/monitor/health/IndexHealthCheck.java
Labels: bug

#4087 Admin console / Move WFS feature harvester to the harvester section (instead of status & information).
  web-ui/src/main/resources/catalog/js/admin/DashboardController.js
  web-ui/src/main/resources/catalog/js/admin/HarvestController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/harvest/wfs-indexing.html
Labels: enhancement

#4102 Subtemplates - support Anchor for title in gmd:DQ_DomainConsistency
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl
Labels: backport-3.8.x

#4038 Warn user if harvester or userid is already taken
  domain/src/main/java/org/fao/geonet/repository/specification/UserSpecs.java
  services/src/main/java/org/fao/geonet/api/harvesting/HarvestersApi.java
  services/src/main/java/org/fao/geonet/api/users/UsersApi.java
  web-ui/src/main/resources/catalog/components/admin/harvester/HarvesterDirective.js
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/identification.html
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/arcsde.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geoPREST.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork20.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/ogcwxs.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/thredds.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/wfsfeatures.html
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: enhancement

#4097 Dashboard / Record links / Fix link url
  web-ui/src/main/resources/catalog/templates/admin/dashboard/record-links.html
Labels: bug

#4104 Update legacy services mapping
  core/src/main/java/org/fao/geonet/services/thumbnail/Set.java
  healthmonitor/src/main/java/org/fao/geonet/monitor/service/LogConfig.java
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/ListFormatters.java
  services/src/main/java/org/fao/geonet/api/records/formatters/Register.java
  services/src/main/java/org/fao/geonet/api/records/formatters/Resource.java
  services/src/main/java/org/fao/geonet/guiservices/csw/virtual/Delete.java
  services/src/main/java/org/fao/geonet/guiservices/csw/virtual/Get.java
  services/src/main/java/org/fao/geonet/guiservices/csw/virtual/List.java
  services/src/main/java/org/fao/geonet/guiservices/csw/virtual/Update.java
  services/src/main/java/org/fao/geonet/guiservices/metadata/GetRelated.java
  services/src/main/java/org/fao/geonet/services/category/Remove.java
  services/src/main/java/org/fao/geonet/services/category/Update.java
  services/src/main/java/org/fao/geonet/services/category/XmlUpdate.java
  services/src/main/java/org/fao/geonet/services/log/List.java
  services/src/main/java/org/fao/geonet/services/logo/Add.java
  services/src/main/java/org/fao/geonet/services/main/Select.java
  services/src/main/java/org/fao/geonet/services/metadata/BatchNewOwner.java
  services/src/main/java/org/fao/geonet/services/metadata/ExtractServicesLayers.java
  services/src/main/java/org/fao/geonet/services/metadata/MetadataIdentifierTemplatesController.java
  services/src/main/java/org/fao/geonet/services/metadata/Publish.java
  services/src/main/java/org/fao/geonet/services/metadata/ValidationService.java
  services/src/main/java/org/fao/geonet/services/metadata/XslProcessing.java
  services/src/main/java/org/fao/geonet/services/metadata/XslProcessingReportGet.java
  services/src/main/java/org/fao/geonet/services/region/List.java
  services/src/main/java/org/fao/geonet/services/resources/Download.java
  services/src/main/java/org/fao/geonet/services/resources/RemoveAndProcess.java
  services/src/main/java/org/fao/geonet/services/resources/UploadAndProcess.java
  services/src/main/java/org/fao/geonet/services/sources/SourcesController.java
  services/src/main/java/org/fao/geonet/services/system/UpdateSystemInfo.java
  services/src/main/java/org/fao/geonet/services/user/List.java
  services/src/main/java/org/fao/geonet/services/user/Remove.java
  services/src/main/java/org/fao/geonet/services/user/Update.java
Labels: bug

#4117 Logo picker / Order by file name & allow filtering when more than 10 logos
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/logopicker.html
Labels: enhancement

#4119 Record link / Disable analyze button (only allowed for admin user)
  web-ui/src/main/resources/catalog/templates/admin/dashboard/record-links.html
Labels: enhancement

#4070 Harvester / Add option to append privileges in case of override
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/BaseAligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractParams.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/HarvestResult.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/arcsde/ArcSDEHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/fragment/FragmentHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetParams.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/privileges.html
  web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.js
  web/src/main/webapp/xsl/xml/harvesting/common.xsl
  web/src/main/webapp/xsl/xml/harvesting/geonetwork.xsl
Labels: enhancement

#4076 Harvester / CSW / Bbox filter.
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
  web-ui/src/main/resources/catalog/components/common/map/mapDirective.js
  web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/style/gn_editor.less
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Labels: enhancement

#4098 Portal / Add link to group
  domain/src/main/java/org/fao/geonet/domain/Source.java
  domain/src/main/java/org/fao/geonet/repository/SourceRepository.java
  services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
  services/src/main/java/org/fao/geonet/api/uisetting/UiSettingApi.java
  services/src/test/java/org/fao/geonet/api/uisetting/UiApiTest.java
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/identification.html
  web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
  web-ui/src/main/resources/catalog/components/search/formfields/partials/groupsCombo.html
  web-ui/src/main/resources/catalog/js/GnAdminMenu.js
  web-ui/src/main/resources/catalog/js/admin/AdminController.js
  web-ui/src/main/resources/catalog/js/admin/SettingsController.js
  web-ui/src/main/resources/catalog/js/admin/SourcesController.js
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
Labels: enhancement

#4100 Editor / Flat mode / When adding free text keyword, insert keyword in existing one or create a new block if not.
  schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
  web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
  web-ui/src/main/resources/catalog/components/thesaurus/partials/thesaurusselector.html
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
Labels: enhancement, schema plugin change

#4103 Set threads in maven-surefire-plugin based on number of cores.
  domain/pom.xml
  pom.xml
Labels: enhancement

#4108 Keyword encoding / Add multilingual anchor support.
  schemas/iso19139/src/main/plugin/iso19139/convert/thesaurus-transformation.xsl
Labels: enhancement, schema plugin change

#4131 API / Translation should never be null
  services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java
Labels: bug, critical

#4138 Editor / Add confirmation before removal.
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/overview-manager.html
  web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
  web-ui/src/main/resources/catalog/locales/en-editor.json
Labels: enhancement

#4135 Inspire validator proxy geonet
  services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
  services/src/main/java/org/fao/geonet/api/records/editing/InspireValidatorUtils.java
  services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
Labels: bug

#4146 Map viewer / Save map as metadata / Options to choose group and publication status
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
  web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextDirective.js
  web-ui/src/main/resources/catalog/components/viewer/owscontext/partials/owscontext.html
  web-ui/src/main/resources/catalog/locales/en-search.json
Labels: enhancement

#4075 Editor / Thumbnail creation fails due to PDF box update and conflict with mapfish print
  pom.xml
  web-ui/src/main/resources/catalog/components/common/map/print/partials/print.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
  web-ui/src/main/resources/catalog/locales/en-search.json
  web/src/main/webapp/WEB-INF/config-print/print-config.yaml
Labels: bug
