Repository geonetwork/core-geonetwork, pull requests merged in 2019-11, with the labels that each got.

#4152 Update en-search.json
  web-ui/src/main/resources/catalog/locales/en-search.json
Labels: enhancement

#4188 ISO19139 / 2007 schema contains duplicated (unused) files for codelist.
  schemas/iso19139/src/main/plugin/iso19139/schema2007/resources/codelist/ML_gmxCodelists.xml
  schemas/iso19139/src/main/plugin/iso19139/schema2007/resources/codelist/gmxCodelists.xml
  schemas/iso19139/src/main/plugin/iso19139/schema2007/resources/codelist/tcCodelists.xml
Labels: enhancement

#4170 Directory / Fix error when opening editor.
  web/src/main/webapp/xslt/common/functions-metadata.xsl
Labels: bug, critical

#4171 Facet / Add record owner name to easily search by username.
  core/src/main/java/org/fao/geonet/constants/Geonet.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/templates/editor/directory.html
  web/src/main/webapp/WEB-INF/config-lucene.xml
  web/src/main/webapp/WEB-INF/config-summary.xml
Labels: enhancement

#4176 Update attachment records on import
  core/src/main/java/org/fao/geonet/MetadataResourceDatabaseMigration.java
Labels: bug

#4186 UI Config / Facet / Order facet according to configuration
  web-ui/src/main/resources/catalog/components/search/facets/FacetDimensionDirective.js
Labels: enhancement

#4194 ISO19139 / Support for applicationProfile as anchor
  schemas/iso19139/src/main/plugin/iso19139/convert/ATOM/iso19119ToAtomFeed.xsl
  schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl
Labels: enhancement

#4201 Fix check on permissions
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Labels: bug

#4195 Admin / User / List not loaded in non debug mode
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
Labels: bug

#4211 Documentation / Add link when a page exist in the doc
  web-ui/src/main/resources/catalog/templates/admin/classification/categories.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
  web-ui/src/main/resources/catalog/templates/admin/settings/csw-virtual.html
  web-ui/src/main/resources/catalog/templates/admin/settings/csw.html
  web-ui/src/main/resources/catalog/templates/admin/settings/mapservers.html
  web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
  web-ui/src/main/resources/catalog/templates/admin/settings/ui.html
  web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
  web-ui/src/main/resources/catalog/templates/editor/batchedit.html
  web-ui/src/main/resources/catalog/templates/editor/import.html
  web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html
  web-ui/src/main/resources/catalog/templates/editor/new-metadata-vertical.html
Labels: enhancement

#4203 Don't create PT_FreeText on main language if the CharacterString is null
  schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Labels: schema plugin change

#4198 improve operateson link remove+resource constraint subtemplate option
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/datasets-remove.xsl
Labels: schema plugin change

#4113 Fix legends for map layers
  web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
Labels: question

#4229 API / XSL Process / Preview should not save in db.
  services/src/main/java/org/fao/geonet/api/processing/XslProcessApi.java
Labels: bug

#4232 Elements targeted by operation filters can be removed on processing.
  core/src/main/java/org/fao/geonet/kernel/DataManager.java
  core/src/main/java/org/fao/geonet/kernel/XmlSerializer.java
  core/src/main/java/org/fao/geonet/kernel/XmlSerializerDb.java
  core/src/main/java/org/fao/geonet/kernel/XmlSerializerSvn.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataManager.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
  core/src/test/java/org/fao/geonet/kernel/XmlSerializerIntegrationTest.java
  services/src/main/java/org/fao/geonet/api/processing/XslProcessUtils.java
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
Labels: bug
