Repository geonetwork/core-geonetwork, pull requests merged in 2019-12, with the labels that each got.

#4157 Set context as thread local when it is created in ApiUtils
  services/src/main/java/org/fao/geonet/api/ApiUtils.java
  services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java
Labels: bug

#4158 [BP] Set context as thread local when it is created in ApiUtils
  services/src/main/java/org/fao/geonet/api/ApiUtils.java
  services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java
Labels: backport-3.8.x, bug

#4293 improve delete draft first message
  core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataManager.java
Labels: enhancement

#4313 remove the last comma
  web/src/main/webapp/xslt/services/csv/csv-search.xsl
Labels: bug
