Repository geonetwork/core-geonetwork, pull requests merged in 2019-09, with the labels that each got.

#4000 Home page / Add link to open record when clicking the thumbnail (and …
  web-ui/src/main/resources/catalog/views/default/directives/partials/infolist.html
Labels: enhancement

#3999 ISO19139 / Add migration to ISO19115-3.2018
  schemas/iso19139/src/main/plugin/iso19139/process/iso19115-3.2018-schemaupgrade.xsl
Labels: enhancement

#4022 Added extra classes to related resources
  web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
  web-ui/src/main/resources/catalog/style/gn_metadata.less
  web-ui/src/main/resources/catalog/views/default/less/gn_view.less
Labels: enhancement

#3983 ISO19139 / Multilingual record / Fix online source name editing
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
  schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Labels: bug, schema plugin change

#3985 ES / Add option to populate an index with only public records.
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  pom.xml
  web/pom.xml
  web/src/main/webResources/WEB-INF/config.properties
  web/src/main/webResources/WEB-INF/web.xml
Labels: enhancement

#3991 Formatter improvements
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/style/gn_metadata.less
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-variables.xsl
Labels: enhancement

#4024 i18n / Add Portuguesa
  web-ui/download-from-transifex.sh
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/locales/pt-admin.json
  web-ui/src/main/resources/catalog/locales/pt-core.json
  web-ui/src/main/resources/catalog/locales/pt-editor.json
  web-ui/src/main/resources/catalog/locales/pt-search.json
  web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
Labels: enhancement

#4047 Harvester / GeoNetwork 2.x / Fix
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet20/Geonet20Harvester.java
Labels: bug

#4044 Splitting the large GN stylesheet into smaller ones and speed up loading
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/style/gn_editor.less
  web-ui/src/main/resources/catalog/style/gn_fonts.less
  web-ui/src/main/resources/catalog/style/gn_inspire.less
  web-ui/src/main/resources/catalog/style/gn_pickers.less
  web-ui/src/main/resources/catalog/style/gn_search.less
  web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
Labels: enhancement

#4052 if nextrecord=numrecords, nextrecord should not be set to 0
  csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
Labels: bug

#4059 [BP] CSW harverster if count=numrecords, nextrecord should not be 0
  csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
Labels: backport-3.6.x, bug
