Repository geonetwork/core-geonetwork, pull requests merged in 2020-02, with the labels that each got.

#4412 Increase length of Validation.valType column
  domain/src/main/java/org/fao/geonet/domain/MetadataValidationId.java
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/migrate-default.sql
Labels: enhancement

#4439 [BP] Address glitch with duplicate or missing logfiles
  .gitignore
  domain/src/main/java/org/fao/geonet/domain/HarvestHistory.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  web-ui/src/main/resources/catalog/components/utility/UtilityModule.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
Labels: backport-3.10.x

#4440 [BP] Address glitch with duplicate or missing logfiles
  .gitignore
  domain/src/main/java/org/fao/geonet/domain/HarvestHistory.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  web-ui/src/main/resources/catalog/components/utility/UtilityModule.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
Labels: backport-3.8.x

#4441 [BP] Address glitch with duplicate or missing logfiles
  .gitignore
  domain/src/main/java/org/fao/geonet/domain/HarvestHistory.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  web-ui/src/main/resources/catalog/components/utility/UtilityModule.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
Labels: backport-3.6.x

#4429 Attachements / type is now visibility and values are uppercase on GET.
  web-ui/src/main/resources/catalog/components/filestore/FileStoreService.js
  web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
Labels: bug, critical

#4435 ISO19139 / Multilingual / Add Anchor and fallback to non empty value
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl-multilingual.xsl
Labels: schema plugin change

#4443 Stop infinite CSW harvester loop if start > nextRecord
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
Labels: bug

#4446 [BP] Stop infinite harvester loop if start > nextRecord
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
Labels: backport-3.10.x

#4447 [BP] Stop infinite harvester loop if start > nextRecord
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
Labels: backport-3.8.x

#4448 [BP] Stop infinite harvester loop if start > nextRecord
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
Labels: backport-3.6.x

#4449 Index gmd:otherConstraints with gmx:Anchor
  schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
Labels: schema plugin change

#4455 Remove unused namespaces from OAI records
  schemas/csw-record/src/main/plugin/csw-record/convert/oai_dc.xsl
  schemas/iso19110/src/main/plugin/iso19110/convert/oai_dc.xsl
  schemas/iso19139/src/main/plugin/iso19139/convert/oai_dc.xsl
Labels: bug

#4453 Add override and random UUID options to OAI-PMH harvester
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/extras.html
Labels: bug, enhancement
