Repository geonetwork/core-geonetwork, pull requests merged in 2020-03, with the labels that each got.

#4473 Use system property to customise the parent directory of the log folder
  web/src/main/webapp/WEB-INF/classes/log4j-dev.xml
  web/src/main/webapp/WEB-INF/classes/log4j-index.xml
  web/src/main/webapp/WEB-INF/classes/log4j-search.xml
  web/src/main/webapp/WEB-INF/classes/log4j.xml
Labels: enhancement

#4491 Region API / Move to /api
  core/src/main/java/org/fao/geonet/kernel/region/Region.java
  core/src/main/java/org/fao/geonet/kernel/search/spatial/ErrorHandler.java
  core/src/main/java/org/fao/geonet/kernel/search/spatial/SpatialIndexWriter.java
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
  services/src/main/java/org/fao/geonet/api/records/extent/ExpandFactor.java
  services/src/main/java/org/fao/geonet/api/records/extent/MapRenderer.java
  services/src/main/java/org/fao/geonet/api/records/extent/MetadataExtentApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/ImageReplacedElementFactory.java
  services/src/main/java/org/fao/geonet/api/records/formatters/PDF.java
  services/src/main/java/org/fao/geonet/api/records/formatters/groovy/MapConfig.java
  services/src/main/java/org/fao/geonet/api/regions/GeomFormat.java
  services/src/main/java/org/fao/geonet/api/regions/MetadataRegion.java
  services/src/main/java/org/fao/geonet/api/regions/MetadataRegionDAO.java
  services/src/main/java/org/fao/geonet/api/regions/RegionsApi.java
  services/src/main/java/org/fao/geonet/api/regions/ThesaurusBasedRegionsDAO.java
  services/src/main/java/org/fao/geonet/api/regions/ThesaurusRequest.java
  services/src/main/java/org/fao/geonet/api/regions/metadata/MetadataRegionSearchRequest.java
  services/src/main/java/org/fao/geonet/services/region/Get.java
  services/src/main/java/org/fao/geonet/services/region/GetGeom.java
  services/src/main/java/org/fao/geonet/services/region/GetMap.java
  services/src/main/java/org/fao/geonet/services/region/ListCategories.java
  services/src/main/resources/config-spring-geonetwork.xml
  services/src/test/java/org/fao/geonet/api/records/extent/MapRendererTest.java
  services/src/test/java/org/fao/geonet/api/regions/GeomFormatTest.java
  services/src/test/java/org/fao/geonet/api/regions/ListRegionsTest.java
  services/src/test/java/org/fao/geonet/api/regions/MetadataRegionDAOTest.java
  web-ui/src/main/resources/catalog/style/gn_metadata.less
  web-ui/src/main/resources/catalog/style/gn_metadata_pdf.less
  web-ui/src/main/resources/catalog/views/default/templates/recordView.html
  web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
  web/src/main/webapp/WEB-INF/config-lucene.xml
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
Labels: schema plugin change

#4512 Update portuguese strings.xml file. Fixes #4510
  schemas/iso19139/src/main/plugin/iso19139/loc/por/strings.xml
Labels: bug, enhancement

#4484 in map geocoder, only pan to presumed coordinates if they start the input
  web-ui/src/main/resources/catalog/components/viewer/localisation/LocalisationService.js
Labels: bug

#4509 Improve cookie warning message
  web-ui/src/main/resources/catalog/components/cookieWarning/CookieWarningDirective.js
  web-ui/src/main/resources/catalog/components/cookieWarning/CookieWarningModule.js
  web-ui/src/main/resources/catalog/components/cookieWarning/partials/cookieWarning.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/js/CookieWarningController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
Labels: bug, enhancement

#4542 Multi portal mode / Fix shared NodeInfo
  common/src/main/java/org/fao/geonet/NodeInfo.java
  core/src/main/java/jeeves/config/springutil/JeevesAuthenticationDetailSource.java
  core/src/main/java/jeeves/config/springutil/JeevesAuthenticationDetails.java
  core/src/main/java/jeeves/config/springutil/JeevesContextLoaderListener.java
  core/src/main/java/org/fao/geonet/GeonetContext.java
  core/src/main/java/org/fao/geonet/kernel/GeonetworkDataDirectory.java
  core/src/main/java/org/fao/geonet/kernel/SpringLocalServiceInvoker.java
  core/src/main/java/org/fao/geonet/kernel/security/GeonetworkAuthenticationProvider.java
  core/src/main/java/org/fao/geonet/kernel/setting/SettingManager.java
  core/src/test/java/org/fao/geonet/kernel/GeonetworkDataDirectoryMultiNodeServiceConfigOnlySystemDataDirSetTest.java
  core/src/test/java/org/fao/geonet/kernel/GeonetworkDataDirectoryMultiNodeSystemPropertyOnlySystemDataDirSetTest.java
  domain/src/main/java/org/fao/geonet/entitylistener/UserNodeIdSetter.java
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/templates/top-toolbar.html
  web/src/main/webResources/WEB-INF/config-node/srv.xml
  web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
  web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
Labels: bug
