Repository geonetwork/core-geonetwork, pull requests merged in 2020-01, with the labels that each got.

#4271 Fixes arcsde harvesting master
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/AbstractAligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/arcsde/ArcSDEHarvester.java
  harvesters/src/main/resources/config-spring-geonetwork.xml
Labels: bug

#4358 Fix an error when GN is deployed as ROOT context ("/")
  web/src/main/java/org/fao/geonet/i18n/UrlLocaleChangeInterceptor.java
  web/src/main/webResources/WEB-INF/spring-servlet.xml
Labels: bug

#4366 [BP] Fix an error when GN is deployed as ROOT context ("/")
  web/src/main/java/org/fao/geonet/i18n/UrlLocaleChangeInterceptor.java
  web/src/main/webResources/WEB-INF/spring-servlet.xml
Labels: backport-3.8.x, bug

#4363 Improve CSW harvester error message when the host is not valid
  common/src/main/java/org/fao/geonet/exceptions/UnknownHostEx.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
Labels: enhancement

#4365 Add process in Dublin Core schema that can be used in OAI-PMH harvester to o convert from DC to ISO19139 if the remote server only provides DC format
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
  schemas/dublin-core/src/main/plugin/dublin-core/process/dc-to-iso19139.xsl
Labels: enhancement

#4332 import conversion that extracts md_metadata from esri geosticker
  web/src/main/webapp/xsl/conversion/import/EsriGeosticker-to-ISO19139.xsl
Labels: enhancement

#4384 Uniform view for related records in the Metadata view - Backport of #4345 to 3.8.x branch
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
  web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
  web-ui/src/main/resources/catalog/components/metadataactions/partials/relatedObserverTemplate.html
  web-ui/src/main/resources/catalog/components/viewer/wfs/partials/download.html
  web-ui/src/main/resources/catalog/components/viewer/wmts/partials/wmtsDownload.html
Labels: backport-3.8.x

#4388 INSPIRE validation / Add last validation state.
  core/src/main/java/org/fao/geonet/constants/Geonet.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
  web-ui/src/main/resources/catalog/components/utility/partials/typeinspirevalidationwidget.html
  web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js
  web-ui/src/main/resources/catalog/components/validationtools/partials/mdValidationTools.html
  web-ui/src/main/resources/catalog/locales/en-core.json
  web/src/main/webapp/WEB-INF/config-lucene.xml
Labels: enhancement

#4398 MEF / Move back attachment folders in the record folder
  core/src/main/java/org/fao/geonet/kernel/mef/MEF2Exporter.java
Labels: bug, critical

#4381 Search / Improve the search active filters display
  web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
  web-ui/src/main/resources/catalog/components/search/searchfiltertag/partials/searchFilterTagsTemplate.html
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/style/gn_search.less
  web-ui/src/main/resources/catalog/templates/editor/batchedit.html
  web-ui/src/main/resources/catalog/templates/editor/editorboard.html
  web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
  web-ui/src/main/resources/catalog/views/default/templates/results.html
Labels: enhancement

#4390 CSW / Configuration of the capabilities is now done using a service metadata record
  core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
  csw-server/src/main/java/org/fao/geonet/component/csw/GetCapabilities.java
  domain/src/main/java/org/fao/geonet/domain/Source.java
  domain/src/main/java/org/fao/geonet/domain/responses/CswConfigurationResponse.java
  services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
  services/src/main/java/org/fao/geonet/guiservices/csw/Get.java
  services/src/main/java/org/fao/geonet/guiservices/csw/Set.java
  services/src/test/java/org/fao/geonet/guiservices/csw/SetTest.java
  services/src/test/java/org/fao/geonet/services/config/GetTest.java
  web-ui/src/main/resources/catalog/js/admin/CSWSettingsController.js
  web-ui/src/main/resources/catalog/js/admin/SourcesController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/settings/csw.html
  web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3101/migrate-default.sql
  web/src/main/webapp/xml/csw/capabilities.xml
  web/src/main/webapp/xml/csw/capabilities_inspire.xml
  web/src/main/webapp/xml/csw/record-to-csw-capabilities.xsl
Labels: enhancement

#4414 Styling improvements to the full metadata view
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html
  web-ui/src/main/resources/catalog/style/gn_metadata.less
  web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
  web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Labels: schema plugin change
