Repository geonetwork/core-geonetwork, pull requests merged in 2020-09, with the labels that each got.

#4969 [a11y] Fix for aligning logo and GN name
  web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
Labels: backport-3.10.x

#4924 Landing page / Improve multilingual support
  schemas/dublin-core/src/main/plugin/dublin-core/formatter/xsl-view/view.xsl
  schemas/dublin-core/src/main/plugin/dublin-core/layout/layout.xsl
  schemas/dublin-core/src/main/plugin/dublin-core/layout/utility-tpl.xsl
  schemas/iso19110/src/main/plugin/iso19110/formatter/xsl-view/view.xsl
  schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
  schemas/iso19110/src/main/plugin/iso19110/layout/utility-tpl.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/utility-tpl-multilingual.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/utility-fn.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl-multilingual.xsl
  services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java
  web-ui/src/main/resources/catalog/js/GnLandingPageLib.js
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-variables.xsl
  web/src/main/webapp/xslt/common/render-html.xsl
  web/src/main/webapp/xslt/common/utility-tpl.xsl
  web/src/main/webapp/xslt/services/sitemap/sitemap.xsl
Labels: schema plugin change

#5018 INSPIRE Atom feeds parsing - handle optional elements / attributes and update xslt to extract feed url and dataset id to work with Anchor elements
  domain/src/main/java/org/fao/geonet/domain/InspireAtomFeed.java
  schemas/iso19139/src/main/plugin/iso19139/extract-atom-feed.xsl
  schemas/iso19139/src/main/plugin/iso19139/extract-datasetid.xsl
Labels: backport-3.10.x

#5024 Don't rotate harvester log files if a harvester is running during midnight
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
Labels: backport-3.10.x, enhancement

#4849 Remove closure from production scripts (fix ie11 incompatibility)
  web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
  web-ui/src/main/resources/catalog/components/common/openlayers/olDecorateLayerLoading.js
Labels: backport-3.10.x

#5028 [a11y] Improve the cookie message
  web-ui/src/main/resources/catalog/components/cookieWarning/partials/cookieWarning.html
  web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
Labels: backport-3.10.x

#5032 Metadata editor - ignore elements with geonet namespace for render-element value parameter
  schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
Labels: backport-3.10.x

#4061 Field upload directive for metadata editor
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
  web-ui/src/main/resources/catalog/components/edit/FieldsModule.js
  web-ui/src/main/resources/catalog/components/edit/fieldupload/FieldUploadDirective.js
  web-ui/src/main/resources/catalog/components/edit/fieldupload/partials/fieldupload.html
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: backport-3.10.x

#5031 Angular view / Fix missing maintenanceAndUpdateFrequency
  web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Labels: backport-3.10.x

#5052 Fixes #5047 - close input stream after copying attachments
  core/src/main/java/org/fao/geonet/api/records/attachments/StoreUtils.java
Labels: backport-3.10.x

#5063 Get related datasets - ignore if the dataset uuid is empty. Related to #4844
  services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
Labels: backport-3.10.x

#5062 INSPIRE Atom feeds improvements, related to #5043
  inspire-atom/src/main/java/org/fao/geonet/inspireatom/harvester/InspireAtomHarvester.java
  inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java
  web/src/main/webapp/WEB-INF/classes/log4j-dev.xml
  web/src/main/webapp/WEB-INF/classes/log4j-index.xml
  web/src/main/webapp/WEB-INF/classes/log4j-search.xml
  web/src/main/webapp/WEB-INF/classes/log4j.xml
Labels: backport-3.10.x
