Repository geonetwork/core-geonetwork, pull requests merged in 2021-04, with the labels that each got.

#5551 Fixes embedded Cross-Site Scripting issues in #5536
  web-ui/src/main/resources/catalog/components/utility/UtilityService.js
  web-ui/src/main/resources/catalog/js/admin/AdminToolsController.js
  web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
  web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
  web-ui/src/main/resources/catalog/templates/admin/settings/csw-virtual.html
  web-ui/src/main/resources/catalog/templates/admin/tools/batch.html
  web-ui/src/main/resources/catalog/templates/editor/batchedit.html
  web-ui/src/main/resources/catalog/templates/editor/editorboard.html
  web-ui/src/main/resources/catalog/templates/gn-typeahead-match.html
  web-ui/src/main/resources/catalog/views/default/templates/home.html
  web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Labels: backport-3.10.x

#5542 Fix time offset when CatalogUiTimezone is Browser
  web-ui/src/main/resources/catalog/components/edit/datepicker/DatePickerDirective.js
Labels: bug

#5566 Translation of roles when a contact is listed with multiple roles - fix dependency injection, related to #5541
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
Labels: backport-3.12.x

#5476 Encrypt passwords stored in the database
  core/pom.xml
  core/src/main/java/jeeves/server/JeevesEngine.java
  core/src/main/java/org/fao/geonet/constants/Geonet.java
  core/src/main/java/org/fao/geonet/kernel/GeonetworkDataDirectory.java
  core/src/main/java/org/fao/geonet/kernel/setting/HarvesterSettingsManager.java
  domain/pom.xml
  domain/src/main/java/org/fao/geonet/domain/HarvesterSetting.java
  domain/src/main/java/org/fao/geonet/domain/MapServer.java
  domain/src/main/java/org/fao/geonet/domain/Setting.java
  domain/src/main/java/org/fao/geonet/domain/package-info.java
  domain/src/main/java/org/fao/geonet/entitylistener/HarvesterSettingValueSetter.java
  domain/src/main/java/org/fao/geonet/entitylistener/SettingValueSetter.java
  domain/src/main/java/org/fao/geonet/repository/HarvesterSettingRepository.java
  domain/src/main/resources/config-spring-geonetwork.xml
  domain/src/test/java/org/fao/geonet/repository/HarvesterSettingRepositoryTest.java
  domain/src/test/java/org/fao/geonet/repository/MapServerTest.java
  domain/src/test/resources/domain-repository-test-context.xml
  domain/src/test/resources/issue1876-context.xml
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  pom.xml
  services/src/test/java/org/fao/geonet/api/mapservers/MapServersApiTest.java
  services/src/test/resources/services-repository-test-context.xml
  web/src/main/java/org/fao/geonet/EncryptorInitializer.java
  web/src/main/java/org/fao/geonet/Geonetwork.java
  web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
  web/src/main/webapp/WEB-INF/classes/log4j-dev.xml
  web/src/main/webapp/WEB-INF/classes/log4j-index.xml
  web/src/main/webapp/WEB-INF/classes/log4j-search.xml
  web/src/main/webapp/WEB-INF/classes/log4j.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v404/migrate-default.sql
  web/src/main/webapp/WEB-INF/data/config/encryptor/encryptor.properties
Labels: backport-3.12.x

#5550 Insecure password change function. Fixes #5538
  services/src/main/java/org/fao/geonet/api/users/UsersApi.java
  services/src/test/java/org/fao/geonet/api/users/UsersApiTest.java
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: backport-3.12.x

#5267 Improvements fc editor
  schemas/iso19110/src/main/plugin/iso19110/formatter/xsl-view/view.xsl
  schemas/iso19110/src/main/plugin/iso19110/layout/config-editor.xml
  schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
  schemas/iso19110/src/main/plugin/iso19110/loc/eng/labels.xml
  schemas/iso19110/src/main/plugin/iso19110/present/metadata-view.xsl
  schemas/iso19110/src/main/plugin/iso19110/schema-suggestions.xml
  schemas/iso19110/src/main/plugin/iso19110/templates/metadata.xml
Labels: backport-3.12.x

#5203 Add a logout option for a logged-in user
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/templates/signin.html
Labels: backport-3.10.x

#5068 Build / Fix path for web.xml for maven Jetty plugin
  web/pom.xml
Labels: backport-3.10.x

#5549 in csw-full xml, record crs should not be linked to bounds crs
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/csw-brief.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/csw-full.xsl
  schemas/iso19139/src/main/plugin/iso19139/present/csw/csw-brief.xsl
  schemas/iso19139/src/main/plugin/iso19139/present/csw/csw-full.xsl
Labels: backport-3.10.x, backport-3.12.x, enhancement

#5389 Fix the privileges value before the update for RecordPrivilegesChangeEvent in metadata sharing API
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Labels: backport-3.10.x, backport-3.12.x

#5618 Update main references in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#5625 Fix autocommit error when using a JNDI connection
  web/src/main/java/org/fao/geonet/DatabaseMigration.java
Labels: bug

#5613 Fix add-schema script
  add-schema.sh
Labels: backport-3.12.x
