Repository geonetwork/core-geonetwork, pull requests merged in 2021-09, with the labels that each got.

#5934 Remove metadata online resource - fix resource name comparison
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/onlinesrc-remove.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl
Labels: backport-3.10.x, backport-3.12.x

#5935 Display topic categories tooltips in the metadata editor when tooltips are enabled
  web-ui/src/main/resources/catalog/components/edit/topiccategory/TopicCategoryDirective.js
  web-ui/src/main/resources/catalog/components/edit/topiccategory/partials/topiccategory.html
Labels: backport-3.10.x, backport-3.12.x

#5937 Fix editing of directory entries templates. Fixes #5936
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
Labels: backport-3.10.x

#5948 Rollback exceptions handled in GlobalExceptionController. Fixes #5944
  core/src/main/java/jeeves/transaction/TransactionManager.java
  services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
Labels: backport-3.10.x, backport-3.12.x

#5916 "padding-bottom: 150px" for ".gn-editor-sidebar" CSS class.
  web-ui/src/main/resources/catalog/style/gn_editor.less
Labels: backport-3.12.x
