Repository geonetwork/core-geonetwork, pull requests merged in 2021-03, with the labels that each got.

#5440 Fix issue using custom UUIDs
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Labels: backport-3.10.x

#5434 INSPIRE geometry fields lead to 0 results in opensearch. Fixes #4218
  web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
Labels: backport-3.10.x

#5472 INSPIRE Atom fixes
  domain/src/main/java/org/fao/geonet/domain/InspireAtomFeed.java
  domain/src/main/java/org/fao/geonet/repository/specification/MetadataSpecs.java
Labels: backport-3.10.x

#5462 Stream attachments to the browser without loading them in memory
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: enhancement

#5478 Use button to recover the password
  web-ui/src/main/resources/catalog/templates/signin.html
Labels: backport-3.10.x

#5504 fix typo in thesaurus manager
  web-ui/src/main/resources/catalog/js/admin/ThesaurusController.js
Labels: backport-3.10.x

#5292 Add a WMTS error message when the URL can't be parsed
  web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
  web-ui/src/main/resources/catalog/locales/en-core.json
Labels: backport-3.10.x

#5485 Index temporal extent period, fix multiple temporal extent display inthe metadata detail page. Fixes #5483
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/common.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl
  web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
  web-ui/src/main/resources/catalog/views/default/templates/recordView.html
  web/src/main/webapp/WEB-INF/config-lucene.xml
Labels: backport-3.10.x

#5497 Enable preemptive for csw requests with credentials
  csw-server/src/main/java/org/fao/geonet/csw/common/requests/CatalogRequest.java
Labels: backport-3.10.x

#5512 Manage url redirects with URL.openConnection
  core/src/main/java/org/fao/geonet/lib/NetLib.java
  core/src/main/java/org/fao/geonet/util/XslUtil.java
  services/src/main/java/org/fao/geonet/api/records/extent/MapRenderer.java
Labels: backport-3.10.x

#5490 Remove non required data-translate directive usage in gnMetadataGroupUpdater directive
  web-ui/src/main/resources/catalog/components/metadataactions/partials/metadatagroupupdater.html
Labels: backport-3.10.x

#5491 Check for redirect parameter
  web-ui/src/main/resources/catalog/js/LoginController.js
Labels: backport-3.10.x

#5433 Full view doesn't work in a draft version of a metadata record. Fixes #5373
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
  web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
  web-ui/src/main/resources/catalog/views/default/templates/index.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Labels: backport-3.10.x

#5470 Fix draft metadata manager update method to check if should be applied to the draft metadata or the published metadata.
  core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataManager.java
Labels: backport-3.10.x

#5554 Add WMS layer - use layer name if the layer title is empty
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
Labels: backport-3.10.x, backport-3.12.x

#5541 Fix translation of roles when a contact is listed with multiple roles
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
  web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html
Labels: backport-3.12.x

#5553 Generic error message in 'Upload a file from URL'. Fixes #5535
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Labels: backport-3.10.x, backport-3.12.x
