Repository geonetwork/core-geonetwork, pull requests merged in 2021-10, with the labels that each got.

#5981 Updated default language so that is comes from common java location.
  core/src/main/java/org/fao/geonet/util/XslUtil.java
  schemas/iso19139/src/main/plugin/iso19139/convert/functions.xsl
Labels: enhancement, backport-3.12.x

#5978 [BP] INSPIRE / Validation / Add API Key. (#5975)
  core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
  services/src/main/java/org/fao/geonet/api/records/editing/InspireValidatorUtils.java
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3122/migrate-default.sql
Labels: backport-3.10.x

#5865 Add logic to only run encryptor once on password during the migration.
  web/src/main/java/org/fao/geonet/EncryptorInitializer.java
  web/src/main/java/org/fao/geonet/Geonetwork.java
  web/src/main/webResources/WEB-INF/config-db/database_migration.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/MigrateEncryptor.java
Labels: backport-3.12.x

#5987 Configure how to extract the WMS layer name from metadata online resources to add them to the map viewer
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/views/api/index_debug.html
  web-ui/src/main/resources/catalog/views/default/module.js
Labels: backport-3.10.x, backport-3.12.x
