Repository geonetwork/core-geonetwork, pull requests merged in 2021-01, with the labels that each got.

#5067 [a11y] Make the subbar on the record view accessible (by keyboard)
  web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
  web-ui/src/main/resources/catalog/views/default/less/gn_view.less
  web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Labels: backport-3.10.x

#4870 [#4865] Add option setting for changing the background color of the search block
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/settings/cssstyle.html
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
Labels: backport-3.10.x

#5073 [a11y] Accessibility improvements for the footer
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/templates/admin/settings/cssstyle.html
  web-ui/src/main/resources/catalog/views/default/less/gn_footer_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
  web-ui/src/main/resources/catalog/views/default/templates/footer.html
  web-ui/src/main/resources/catalog/views/default/templates/index.html
Labels: backport-3.10.x

#5112 java 8 only
  core/src/main/java/jeeves/config/springutil/JeevesContextLoaderListener.java
  pom.xml
  software_development/BUILDING.md
Labels: backport-3.10.x

#5301 Hide workflow option in versioning page when the workflow is not enabled
  web-ui/src/main/resources/catalog/components/history/GnHistoryDirective.js
Labels: backport-3.10.x

#5300 ISO19139 / ISO19115-3.2018 - Force gco:DateTime on elements that doesn't support gco:Date
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
  schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Labels: backport-3.10.x

#5299 Fix working copy resource display
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/overview-manager.html
  web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
  web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Labels: backport-3.10.x

#5317 Add clean:clean@reset target for web module
  schemas/README.md
  software_development/BUILDING.md
  web/README.md
  web/pom.xml
Labels: enhancement

#5325 release cleanup
  release/README.md
  release/build.xml
  release/pom.xml
  web/src/main/webapp/WEB-INF/server.prop
Labels: backport-3.10.x

#5326 Update installer zip package name to geonetwork-bundle-VERSION.zip
  release/build.xml
  web/src/main/webapp/WEB-INF/server.prop
Labels: backport-3.10.x

#5327 Remove unused file server.prop
  release/build.xml
  release/pom.xml
  web/src/main/webapp/WEB-INF/server.prop
Labels: backport-3.10.x

#5293 ISO19139 - Preserve locale codes in metadata. Fixes #5060
  core/src/test/java/org/fao/geonet/kernel/DataManagerIntegrationTest.java
  schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
  services/src/main/java/org/fao/geonet/api/registries/DirectoryEntriesApi.java
Labels: backport-3.10.x

#5342 Fixed broken site logo image on fresh installation.
  services/src/main/java/org/fao/geonet/api/site/SiteApi.java
Labels: backport-3.10.x

#5347 Fixed another broken image related to #5299
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
Labels: backport-3.10.x

#5371 Reset password service fixes/improvements
  core/src/main/resources/org/fao/geonet/api/Messages.properties
  core/src/main/resources/org/fao/geonet/api/Messages_fre.properties
  services/src/main/java/org/fao/geonet/api/users/PasswordApi.java
  web-ui/src/main/resources/catalog/js/LoginController.js
  web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
Labels: backport-3.12.x
