Repository geonetwork/core-geonetwork, pull requests merged in 2021-12, with the labels that each got.

#6071 Fix coordinate order in jsonld GeoShape element
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/jsonld/iso19115-3.2018-to-jsonld.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
Labels: backport-3.10.x, backport-3.12.x

#6074 Metadata get status service - return the status change date for all types of statuses
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
Labels: backport-3.12.x

#6075 Update log4j2 from from 2.7 to 2.15.0
  pom.xml
Labels: backport-3.12.x

#6078 INSPIRE Atom feed - update retrieve dataset uuid to handle multiple atom feed entries for the same dataset
  domain/src/main/java/org/fao/geonet/repository/InspireAtomFeedRepositoryCustomImpl.java
Labels: backport-3.10.x, backport-3.12.x

#6079 Bump log4j-core and log4j-api from 2.15.0 to 2.16.0
  pom.xml
Labels: dependencies, backport-3.10.x, backport-3.12.x

#6065 Add the doi-get query for ISO19115-3.2018 standard
  schemas/iso19115-3.2018/src/main/resources/config-spring-geonetwork.xml
Labels: backport-3.10.x, backport-3.12.x
