Repository geonetwork/core-geonetwork, pull requests merged in 2021-11, with the labels that each got.

#6011 Fix credentials autocomplete in harvesters
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/account.html
Labels: backport-3.10.x, backport-3.12.x

#5993 Remove username from forgot password service url
  services/src/main/java/org/fao/geonet/api/users/PasswordApi.java
  web-ui/src/main/resources/catalog/js/LoginController.js
Labels: backport-3.10.x, backport-3.12.x

#5954 MetadataPreRemove before backup operation.
  events/src/main/java/org/fao/geonet/events/md/MetadataPreRemove.java
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Labels: backport-3.12.x

#6009 option for duplicate API to copy attachments or not
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Labels: backport-3.12.x

#5811 Update XslProcessApi to process the draft copies for the metadata in a workflow
  services/src/main/java/org/fao/geonet/api/processing/XslProcessApi.java
Labels: backport-3.10.x, backport-3.12.x

#6024 Convert iso639_2T to iso639_2B in form-builder
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: backport-3.12.x

#6037 Change the links to buttons so ngClickAndSpin is actually disabled in DOI widget html template
  web-ui/src/main/resources/catalog/components/doi/partials/doiwidget.html
Labels: bug, backport-3.10.x, backport-3.12.x

#6035 Fixed token refresh issue with keycloakSecurityContextRequestFilter
  web/src/main/webapp/WEB-INF/config-security/config-security-keycloak.xml
Labels: backport-3.12.x

#6039 Datacite formatter - process for creators only point of contacts with roles pointOfContact and custodian
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/datacite/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/datacite/view.xsl
Labels: backport-3.10.x, backport-3.12.x

#6033 Fix feedback email with multiple recipients
  services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
Labels: bug, backport-3.10.x, backport-3.12.x

#6042 Allow to reset the users / groups filters
  web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: backport-3.12.x

#6031 Fix check for layer already in map
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
Labels: backport-3.10.x, backport-3.12.x

#6017 Fix the list of elements to process in CSW ElementSet strategy 'context'
  csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
Labels: backport-3.10.x, backport-3.12.x

#5943 Metadata retired status support
  listeners/src/main/java/org/fao/geonet/listener/metadata/draft/RetireRecord.java
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
  web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
Labels: backport-3.12.x

#6044 Add support for UI settings migrations. Migration for mods.header.isMenubarAccessible
  core/src/main/java/org/fao/geonet/migration/JsonUISettingDatabaseMigration.java
  web/src/main/webResources/WEB-INF/config-db/database_migration.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/UpdateUISettingsMigration.java
  web/src/test/java/v3110/UpdateUISettingsMigrationTest.java
Labels: backport-3.12.x

#6046 Fix method signature in HttpServiceRequest, Related to #5534
  core/src/main/java/jeeves/server/dispatchers/ServiceManager.java
  core/src/main/java/jeeves/server/local/LocalServiceRequest.java
  core/src/main/java/jeeves/server/sources/http/HttpServiceRequest.java
Labels: bug

#6030 Encode view parameter
  web/src/main/webapp/xslt/common/base-variables.xsl
Labels: backport-3.10.x, backport-3.12.x

#6010 Metadata status migration - add FK for relatedMetadataStatusId
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/UpdateMetadataStatus.java
Labels: backport-3.12.x

#6050 Use the Map projection Region API setting in Regions/geometry related services
  services/src/main/java/org/fao/geonet/api/records/extent/MetadataExtentApi.java
  services/src/main/java/org/fao/geonet/api/regions/RegionsApi.java
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
Labels: bug, backport-3.10.x, backport-3.12.x

#6041 Don't display the reset password button when creating a new user
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
Labels: backport-3.10.x, backport-3.12.x

#6040 Don't display the delete button when creating a new group
  web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
Labels: backport-3.12.x

#6060 Fix the registration of the `surname` and `country` for the 'self' registration process
  services/src/main/java/org/fao/geonet/api/users/RegisterApi.java
  web-ui/src/main/resources/catalog/templates/new-account.html
Labels: backport-3.12.x

#6045 Configuration option to restrict the map services supported in map extent API (geom.png) the usage of non-predefined map services.
  services/src/main/java/org/fao/geonet/api/regions/RegionsApi.java
Labels: backport-3.10.x, backport-3.12.x

#5840 Update label texts for workflow dialog / actions. Fixes #4992
  web-ui/src/main/resources/catalog/locales/en-core.json
Labels: backport-3.12.x

#6063 Fix MetadataServiceApiTest tests
  services/src/test/java/org/fao/geonet/api/records/extent/MetadataExtentApiTest.java
Labels: bug
