Repository geonetwork/core-geonetwork, pull requests merged in 2021-07, with the labels that each got.

#5799 Add a scrollbar to the privileges popup when group names are too long
  web-ui/src/main/resources/catalog/style/gn_search.less
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
Labels: backport-3.10.x, backport-3.12.x

#5798 Users without groups assigned are listed in the users lists for any UserAdmin
  services/src/main/java/org/fao/geonet/api/users/UsersApi.java
Labels: backport-3.10.x, backport-3.12.x

#5793 iso19139 full view - codelist elements - display the codelistValue translation only if the element has a text also
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Labels: backport-3.10.x, backport-3.12.x

#5804 Create user form issues 2 requests to userselection api that return status code 400. Fixes #4545
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: backport-3.12.x

#5805 Search results - metadata with a working copy display a label 'Working copy' if the metadata has a draft copy, even for public users.
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
Labels: backport-3.12.x

#5757 Fix Thumbnail generator
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Labels: backport-3.10.x, backport-3.12.x, bug

#5813 Add confirm to delete Category and Cancel edits to metadata
  web-ui/src/main/resources/catalog/js/admin/CategoriesController.js
  web-ui/src/main/resources/catalog/js/edit/EditorController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/style/gn_admin.less
  web-ui/src/main/resources/catalog/templates/admin/classification/categories.html
Labels: backport-3.10.x, backport-3.12.x

#5769 User Profile Readonly for keycloak users
  core/src/main/java/org/fao/geonet/kernel/security/SecurityProviderConfiguration.java
  core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakConfiguration.java
  core/src/main/java/org/fao/geonet/kernel/security/shibboleth/ShibbolethUserConfiguration.java
  core/src/main/java/org/fao/geonet/util/XslUtil.java
  core/src/main/resources/org/fao/geonet/api/Messages.properties
  core/src/main/resources/org/fao/geonet/api/Messages_fre.properties
  services/src/main/java/org/fao/geonet/api/users/PasswordApi.java
  services/src/main/java/org/fao/geonet/api/users/RegisterApi.java
  services/src/main/java/org/fao/geonet/api/users/UsersApi.java
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/js/LoginController.js
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
  web-ui/src/main/resources/catalog/templates/signin.html
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
  web/src/main/webapp/xslt/common/base-variables.xsl
Labels: backport-3.12.x

#5815 Local INSPIRE Atom feed xslt fix for resource constraints with multiple gmd:otherConstraints elements.
  schemas/iso19139/src/main/plugin/iso19139/convert/ATOM/inspire-atom-feed.xsl
Labels: backport-3.10.x, backport-3.12.x

#5816 Update the filter for INSPIRE Atom dataset feed to support the remote operatesOn indexing format
  inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java
Labels: backport-3.10.x

#5829 Escape login redirect url for keycloak
  web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
  web-ui/src/main/resources/catalog/templates/top-toolbar.html
Labels: backport-3.12.x

#5872 Fix related to #5804: replace ng-if with ng-show, as ng-if creates a child scope that causes a side effect with ngSearchForm directive.
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: backport-3.12.x
