Repository geonetwork/core-geonetwork, pull requests merged in 2021-05, with the labels that each got.

#5559 Add a new directive for combining add online resource fields
  web-ui/src/main/resources/catalog/components/edit/FieldsModule.js
  web-ui/src/main/resources/catalog/components/edit/multientrycombiner/MultiEntryCombinerOnlineResourcesDescription.js
  web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner_onlineresourcesdescription.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
  web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Labels: enhancement

#5671 DOI / Improvements
  core/src/main/java/org/fao/geonet/kernel/ApplicableSchematron.java
  core/src/main/java/org/fao/geonet/kernel/SchematronValidator.java
  doi/src/main/java/org/fao/geonet/doi/client/DoiClient.java
  doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/schematron-rules-datacite.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/schematron-rules-datacite.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/doi-add.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schematron/schematron-rules-datacite.sch
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/schematron-rules-datacite.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/schematron-rules-datacite.xml
  schemas/iso19139/src/main/plugin/iso19139/process/doi-add.xsl
  schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-datacite.sch
  web-ui/src/main/resources/catalog/components/history/partials/historyStep.html
Labels: schema plugin change

#5700 Fix retrieval of settings during the application startup if the encryptor is not initialised
  core/src/main/java/org/fao/geonet/kernel/setting/SettingManager.java
Labels: backport-3.12.x, bug
