Repository geonetwork/core-geonetwork, pull requests merged in 2022-01, with the labels that each got.

#6092 Confirmation dialog to delete an UI configuration
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/style/gn_admin.less
  web-ui/src/main/resources/catalog/templates/admin/settings/ui.html
Labels: backport-3.12.x

#6072 Don't allow to delete a group if owns metadata
  services/src/main/java/org/fao/geonet/api/groups/GroupsApi.java
Labels: backport-3.12.x

#6094 Update UI configuration selected by default:
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
Labels: backport-3.12.x

#6081 Service record for CSW capabilities - INSPIRE improvements
  web/src/main/webapp/xml/csw/record-to-csw-capabilities.xsl
Labels: backport-3.10.x, backport-3.12.x

#6082 Metadata update and internal reports updates
  domain/src/main/java/org/fao/geonet/repository/reports/MetadataReportsQueries.java
  services/src/main/java/org/fao/geonet/api/reports/ReportInternalMetadata.java
  services/src/main/java/org/fao/geonet/api/reports/ReportUpdatedMetadata.java
Labels: backport-3.10.x, backport-3.12.x

#6093 Sort groups and users in transfer ownership
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
  web-ui/src/main/resources/catalog/js/admin/AdminToolsController.js
  web-ui/src/main/resources/catalog/templates/admin/tools/transferownership.html
Labels: backport-3.12.x

#6090 Fix check for layer already in map - case insensitive check of the url
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
Labels: backport-3.10.x, backport-3.12.x

#6110 Bump log4j2 from 2.17.0 to 2.17.1
  pom.xml
Labels: dependencies, backport-3.10.x, backport-3.12.x

#5557 Metadata workflow - publish an approved record with a draft copy, publishes the draft copy. Fixes #5556
  listeners/src/main/java/org/fao/geonet/listener/metadata/draft/ApprovePublishedRecord.java
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Labels: backport-3.10.x

#6102 Harvester results - filter by harvester uuid instead of site id. Fixes #5530
  core/src/main/java/org/fao/geonet/constants/Geonet.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
  web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
Labels: bug

#6127 Formatter - remove debug mode
  services/src/main/java/org/fao/geonet/api/records/formatters/XsltFormatter.java
Labels: backport-3.10.x, backport-3.12.x

#6123 Fix to display the role translation instead of the role code in the iso19139 full view formatter
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Labels: backport-3.12.x

#6100 Avoid NullPointerException if the thesaurus doesn't exist in GetTopCo…
  services/src/main/java/org/fao/geonet/services/thesaurus/GetTopConcept.java
Labels: backport-3.10.x

#6091 Fix removal of sort by and hits per page elements in the UI configuration
  web-ui/src/main/resources/catalog/js/CatController.js
Labels: backport-3.10.x, backport-3.12.x

#6124 DOI - add identifier / online resource url using the DOI proxy url
  doi/src/main/java/org/fao/geonet/doi/client/DoiClient.java
  doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
  doi/src/main/java/org/fao/geonet/doi/client/DoiSettings.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/doi-add.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/doi-add.xsl
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v406/migrate-default.sql
Labels: backport-3.12.x

#6120 [BP] Update libs reported by github security. See 6aecf968
  pom.xml
  services/src/main/java/org/fao/geonet/services/metadata/BatchOpsMetadataReindexer.java
  services/src/main/java/org/fao/geonet/services/metadata/Publish.java
Labels: dependencies

#6106 Fix issue with CMIS connection during startup
  core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
Labels: backport-3.12.x

#6134 Updated keycloak to use the correct granted authority
  core/src/main/java/jeeves/server/UserSession.java
  core/src/main/java/org/fao/geonet/kernel/security/SecurityProviderUtil.java
  core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakAuthenticationProcessingFilter.java
  core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakAuthenticationProvider.java
  core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakLogoutHandler.java
  core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakUserUtils.java
  core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakUtil.java
  web/src/main/webapp/WEB-INF/config-security/config-security-keycloak.xml
  web/src/main/webapp/WEB-INF/config-security/keycloak.json
Labels: backport-3.12.x

#6131 Fix the cron expression for the INSPIRE ATOM harvester
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v300/migrate-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v406/migrate-default.sql
Labels: backport-3.12.x

#6143 Use typeNames in the WFS URL when version is >= "2.0.0"
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
  web-ui/src/main/resources/catalog/components/viewer/wfs/WfsService.js
Labels: bug, backport-3.12.x
