Repository geonetwork/core-geonetwork, pull requests merged in 2022-09, with the labels that each got.

#6515 Remove unused izpack-standalone-compiler dependency
  pom.xml
Labels: backport-3.12.x

#6525 Fix links not generated properly in schema docs
  docs/schema-doc/src/main/resources/config-editor-to-rst.xsl
Labels: backport-3.12.x

#6526 [a11y] `TAB` order of the row tools on the search page
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/views/default/templates/results.html
Labels: backport-3.12.x

#6507 Support for a process to update the metadata content when creating a duplicate
  core/src/main/java/org/fao/geonet/constants/Geonet.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
  core/src/test/java/org/fao/geonet/kernel/datamanager/BaseMetadataManagerTest.java
  core/src/test/resources/org/fao/geonet/kernel/doi-metadata.iso19139.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/duplicate-metadata.xsl
  schemas/iso19139/src/main/plugin/iso19139/duplicate-metadata.xsl
Labels: schema plugin change, backport-3.12.x

#6472 Update DOI manager with multilingual exceptions
  doi/src/main/java/org/fao/geonet/doi/client/DoiClientException.java
  doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/schematron-rules-datacite.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/schematron-rules-datacite.xml
  services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport-3.12.x

#6531 Upgrade keycloak dependency to 18.0.2
  core/pom.xml
Labels: backport-3.12.x

#6532 Add Message.properties files to core tests to avoid the failure of test that use code retrieving messages from that files
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
Labels: backport-3.12.x

#6524 Fix typos in metadata schema element labels and descriptions
  schemas/iso19110/src/main/plugin/iso19110/loc/eng/codelists.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/tur/labels.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/codelists.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/codelists.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ara/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ara/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/chi/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/chi/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/dut/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/dut/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ita/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/nor/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/nor/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/por/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/rus/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/rus/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/swe/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/tur/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/schema/resources/Codelist/gmxCodelists.xml
  schemas/iso19139/src/main/plugin/iso19139/schema2007/resources/Codelist/gmxCodelists.xml
Labels: backport-3.12.x

#6537 Update Threads API
  healthmonitor/src/main/java/org/fao/geonet/monitor/service/Threads.java
Labels: backport-3.12.x, backport-4.0.x

#6536 Remove duplicated dependencies declaration
  workers/pom.xml
Labels: dependencies

#6511 Add validation status to cmis store and configuration
  core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
  core/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
  core/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
  core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
  core/src/main/java/org/fao/geonet/resources/CMISUtils.java
  core/src/main/resources/config-store/config-cmis-overrides.properties
  core/src/main/resources/config-store/config-cmis.xml
  domain/src/main/java/org/fao/geonet/domain/MetadataResourceExternalManagementProperties.java
  web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
  web-ui/src/main/resources/catalog/style/gn.less
Labels: backport-3.12.x

#6534 Display successful test mail sent message
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
Labels: backport-3.12.x

#6293 Adjust side bar thickness to 12px
  web-ui/src/main/resources/catalog/style/gn.less
Labels: backport-3.12.x

#6558 Remove non-needed code since multi-node support is not available
  core/src/main/java/jeeves/config/springutil/JeevesDelegatingFilterProxy.java
  web/src/main/webResources/WEB-INF/web.xml
Labels: backport-3.12.x

#6474 Metadata workflow - Bulk metadata submit
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
  services/src/main/java/org/fao/geonet/api/records/model/MetadataBatchSubmitParameter.java
  services/src/test/java/org/fao/geonet/api/records/MetadataWorkflowApiTest.java
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
  web-ui/src/main/resources/catalog/components/metadataactions/partials/batchsubmit.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html
  web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/locales/en-search.json
Labels: backport-3.12.x

#6457 Configuration to notify by mail about metadata publication / unpublication
  core/src/main/java/org/fao/geonet/kernel/WatchListNotifier.java
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
  core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
  core/src/main/java/org/fao/geonet/util/MailUtil.java
  domain/src/main/java/org/fao/geonet/domain/StatusValueNotificationLevel.java
  domain/src/main/java/org/fao/geonet/repository/specification/GroupSpecs.java
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
  services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v421/migrate-default.sql
Labels: backport-3.12.x, backport-4.0.x

#6569 Update Site API
  services/src/main/java/org/fao/geonet/api/site/SiteApi.java
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
Labels: backport-3.12.x

#6570 Remove HttpOnly for session timeout cookies, otherwise can't be processed in the UI code
  core/src/main/java/org/geonetwork/http/SessionTimeoutCookieFilter.java
Labels: backport-3.12.x
