Repository geonetwork/core-geonetwork, pull requests merged in 2022-04, with the labels that each got.

#6231 Harvester of type Geonetwork using MEF format doesn't update the server in the online resource links for uploaded files/thumbnails
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
Labels: backport-3.12.x

#6181 Fix list filtering (ex. users / groups lists) to reset the paginationto the first page when the filtered results have less results than the ones needed to be displayed the current page
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Labels: backport-3.12.x

#6262 Metadata editor / Fix initialise the default configuration to handle WMS resources, when it's not defined in the schema configuration.
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Labels: backport-3.12.x

#6263 Add Heritrix to the list of bots that shouldn't create a session
  services/src/main/java/org/fao/geonet/api/AllRequestsInterceptor.java
Labels: enhancement, backport-3.12.x

#6264 Fix search suggestions output when a suggestion contains the character \
  web/src/main/webapp/xslt/services/suggestions.xsl
Labels: bug

#6266 Fix tests that started failing on passwords BP
  services/src/test/java/org/fao/geonet/api/site/SiteApiTest.java
  services/src/test/java/org/fao/geonet/api/users/UsersApiTest.java
Labels: bug

#6270 Ensure that keycloak login redirects only go the the current server.
  core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakAuthenticationProcessingFilter.java
  core/src/main/java/org/fao/geonet/kernel/security/keycloak/keycloakPreAuthActionsLoginFilter.java
Labels: backport-3.12.x

#6267 check content type for runtime exception
  services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
Labels: backport-3.12.x

#6274 Cancelling from import or add new record results in a blank editor board
  web-ui/src/main/resources/catalog/components/utility/UtilityService.js
  web-ui/src/main/resources/catalog/js/edit/ImportController.js
  web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
  web-ui/src/main/resources/catalog/templates/editor/import.html
  web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html
  web-ui/src/main/resources/catalog/templates/editor/new-metadata-vertical.html
Labels: backport-3.12.x
