Repository geonetwork/core-geonetwork, pull requests merged in 2022-02, with the labels that each got.

#6144 Update transfer ownership to handle when the metadata workflow is enabled the approved version of the metadata with a working copy
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Labels: backport-3.12.x

#6142 Metadata detail page - fix trigger metadata tab selection
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedObserverDirective.js
Labels: backport-3.12.x

#6141 Metadata publish - check if the metadata owner group has the workflow enabled
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Labels: backport-3.12.x

#6132 Fix bug with Keycloak backchannel logout not working due to CSRF issue.
  core/src/main/java/org/fao/geonet/kernel/security/keycloak/keycloakPreAuthActionsLoginFilter.java
  web/src/main/webapp/WEB-INF/config-security/config-security-keycloak.xml
Labels: backport-3.12.x

#6149 Metadata status dialog - disable button until receiving the current metadata status value
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
  web-ui/src/main/resources/catalog/components/metadataactions/partials/statusupdater.html
Labels: backport-3.12.x

#6159 Add German translations for Datacite schematron rules
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/ger/schematron-rules-datacite.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ger/schematron-rules-datacite.xml
Labels: enhancement, backport-3.12.x

#6140 Users form - add button to toggle password fields visibility
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/components/utility/partials/hideshowpassword.html
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: backport-3.12.x

#6165 Bump hibernate deps from 5.4.24.Final to 5.4.33.Final
  inspire-atom/pom.xml
  pom.xml
Labels: dependencies, java

#6163 Configure HttpOnly for session timeout cookies and fix the cookie path. Fixes #6151
  core/src/main/java/org/geonetwork/http/SessionTimeoutCookieFilter.java
Labels: backport-3.12.x

#6173 Configure HttpOnly for language cookie and fix the cookie path. Fixes #6151
  core/src/main/java/jeeves/server/sources/http/JeevesServlet.java
Labels: backport-3.12.x

#5817 Fix authentication type property name in user form
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: backport-3.10.x, backport-3.12.x
