Repository geonetwork/core-geonetwork, pull requests merged in 2022-05, with the labels that each got.

#6279 NumberFormatException handling
  services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
Labels: backport-3.12.x

#6288 Remote ATOM feeds: fix atom describe output to remove a wrong empty namespace in some elements.
  web/src/main/webapp/xslt/services/inspire-atom/describe.xsl
Labels: backport-3.12.x

#6286 Update the harvester setting repository to remove the hierarchical delete of the harvester settings.
  core/src/main/java/org/fao/geonet/kernel/setting/HarvesterSettingsManager.java
  domain/src/main/java/org/fao/geonet/repository/GeonetRepositoryFactoryBean.java
  domain/src/main/java/org/fao/geonet/repository/HarvesterSettingRepositoryImpl.java
Labels: bug

#6300 Remote ATOM feeds: fix atom describe output to remove a wrong empty namespace in some elements - handle additional namespaces.
  web/src/main/webapp/xslt/services/inspire-atom/describe.xsl
Labels: backport-3.12.x

#6295 Metadata workflow: cancelling the metadata editor when editing a working copy always removes the working copy
  core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
Labels: backport-3.12.x

#6299 Metadata workflow: metadata save and submit was displaying the metadata in a wrong status.
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
Labels: backport-3.12.x

#6297 Update multicombiner directive to allow to configure the number of suggestions for the elements that use the thesaurus keyWord picker component
  web-ui/src/main/resources/catalog/components/edit/multientrycombiner/MultiEntryCombiner.js
  web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner.html
Labels: backport-3.12.x

#6315 Use SAXBuilder in XslUtil method to retrieve the xml content from an URL
  core/src/main/java/org/fao/geonet/util/XslUtil.java
Labels: backport-3.12.x

#6313 Metadata workflow: fix save and approve action in the metadata editor, that wasn't replacing the approved version with the working copy changes
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
Labels: backport-3.12.x

#6317 Metadata workflow: cancelling the metadata editor when editing a working copy always removes the working copy - related issue when the working copy was saved clicking 'Save & close' only.
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
Labels: backport-3.12.x

#6319 Make consistent the date set in metadata status change date.
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataStatus.java
Labels: bug, backport-3.12.x

#6322 Fix ESAPI Logger configuration
  web/src/main/webapp/WEB-INF/classes/ESAPI.properties
Labels: bug

#6305 Harvester / Logo may not be a png.
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
  core/src/main/java/org/fao/geonet/resources/Resources.java
  core/src/main/java/org/fao/geonet/util/XslUtil.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
Labels: backport-4.0.x
