Repository geonetwork/core-geonetwork, pull requests merged in 2022-06, with the labels that each got.

#6338 Fix DOI publication task enabling after publishing the metadata
  web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
Labels: backport-3.12.x, backport-4.0.x

#6334 Use multilingual texts in metadata sharing API exceptions
  core/src/main/java/org/fao/geonet/kernel/AccessManager.java
  core/src/main/resources/org/fao/geonet/api/Messages.properties
  core/src/main/resources/org/fao/geonet/api/Messages_fre.properties
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Labels: backport-3.12.x, backport-4.0.x

#6345 Use parent element to retrieve labels in the schemas that use the context attribute
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Labels: backport-3.12.x, backport-4.0.x

#6341 Add inline messages for the Add Feedback form
  web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
  web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js
  web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbacknew.html
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/views/default/less/gn_feedback_default.less
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
Labels: backport-3.12.x, backport-4.0.x

#6356 Externalise the configuration of targetUri property
  web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
Labels: enhancement

#6353 Update locale parsing from keycloak token to support different formats.
  core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakAuthenticationProcessingFilter.java
Labels: backport-3.12.x, backport-4.0.x

#6343 Switch from itext to openpdf for PDF map rendering
  common/pom.xml
  common/src/main/java/org/fao/geonet/utils/Diff.java
  core/pom.xml
  core/src/main/java/org/fao/geonet/kernel/thumbnail/ThumbnailMaker.java
  pom.xml
  schemas/dublin-core/pom.xml
  services/pom.xml
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/ImageReplacedElementFactory.java
  web/pom.xml
Labels: dependencies, backport-3.12.x

#6367 Disable the DOI publication in the metadata editor for metadata using the metadata workflow
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
Labels: backport-3.12.x, backport-4.0.x

#6392 [BP] Switch from iText to OpenPDF for PDF map rendering
  core/pom.xml
  core/src/main/java/org/fao/geonet/kernel/thumbnail/ThumbnailMaker.java
  pom.xml
  services/pom.xml
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/ImageReplacedElementFactory.java
  services/src/main/java/org/fao/geonet/api/standards/StandardsApi.java
  web/pom.xml
Labels: dependencies, backport-3.12.x

#6401 Webdav harvester - add the number of files to harvest in INFO log level and remote duplicated log entry
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
Labels: backport-3.12.x, backport-4.0.x

#6405 Change some of the CMIS private methods to protected
  core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
  core/src/main/java/org/fao/geonet/resources/CMISResources.java
Labels: backport-3.12.x

#6394 Update datepicker widget to configure the display of the date mode selector
  web-ui/src/main/resources/catalog/components/edit/datepicker/DatePickerDirective.js
  web-ui/src/main/resources/catalog/components/edit/datepicker/partials/datepicker.html
  web-ui/src/main/resources/catalog/style/gn_editor.less
Labels: backport-3.12.x, backport-4.0.x

#6416 Harvesters / GeoNetwork harvester / Re-add exiting files when re-harvesting
  core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
  core/src/test/java/org/fao/geonet/api/records/attachments/FilesystemStoreTest.java
  core/src/test/resources/org/fao/geonet/api/records/attachments/existingResource.jpg
Labels: bug, backport-3.12.x, backport-4.0.x

#6427 Fix slovenian language code for INSPIRE Registry thesaurus
  web-ui/src/main/resources/catalog/components/admin/registry/RegistryService.js
Labels: backport-3.12.x, backport-4.0.x
