Repository geonetwork/core-geonetwork, pull requests merged in 2023-08, with the labels that each got.

#7254 Use http proxy in DOI client
  doi/src/main/java/org/fao/geonet/doi/client/BaseDoiClient.java
  doi/src/main/java/org/fao/geonet/doi/client/DoiDataciteClient.java
  doi/src/main/java/org/fao/geonet/doi/client/DoiSettings.java
  web/src/main/webapp/WEB-INF/classes/log4j2-dev.xml
  web/src/main/webapp/WEB-INF/classes/log4j2-index.xml
  web/src/main/webapp/WEB-INF/classes/log4j2.xml
Labels: backport-4.2.x

#7277 Fix directive to display the most popular records, to display the most popular first
  web-ui/src/main/resources/catalog/views/default/module.js
Labels: backport-4.2.x

#7241 Add XmlTransient annotation to ISODate.getDateAndTimeUtc
  domain/src/main/java/org/fao/geonet/domain/ISODate.java
Labels: backport-4.2.x

#7278 Standard / ISO19115-3 / Processing / Metadata contact lost.
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/add-wms-and-legend-from-esrirest.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/create-featurecatalogue-from-wfs.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/spatineo-registration.xsl
Labels: backport-4.2.x

#7275 Fix error that would occur when there were duplicate languages.
  web-ui/src/main/resources/catalog/views/default/templates/recordView/metadata.html
Labels: bug, backport-4.2.x

#7280 WMS time dimension - basic support for time intervals
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
Labels: backport-4.2.x

#7282 Full view on working copy fails
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
  web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
Labels: backport-4.2.x

#7266 Metadata editor / display metadata uuid for remote resources if the metadata title is not available
  web-ui/src/main/resources/catalog/components/metadataactions/partials/relatedEditorList.html
Labels: backport-4.2.x

#7269 Metadata index set of records - index the approved and working copies when the workflow is enabled
  core/src/main/java/org/fao/geonet/kernel/search/index/OverviewIndexFieldUpdater.java
  services/src/main/java/org/fao/geonet/api/records/MetadataIndexApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataTagApi.java
Labels: backport-4.2.x

#7287 API / Attachements / Stream files to servlet response
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: backport-4.2.x

#7281 Use resource files for messages
  core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport-3.12.x, backport-4.2.x

#7256 fix multi entry combiner ui formatting issue when adding online resource
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
Labels: backport-3.12.x, backport-4.2.x

#7240 Update GeonetHttpRequestFactory to use system proxy defined in JAVA_OPTS
  common/src/main/java/org/fao/geonet/utils/AbstractHttpRequest.java
  common/src/main/java/org/fao/geonet/utils/GeonetHttpRequestFactory.java
Labels: backport-4.2.x

#7250 Metadata tooltips - improve the check method to try to find a match a standard default with no context defined, if there is no entry with the element context
  core/src/main/java/org/fao/geonet/api/standards/StandardsUtils.java
Labels: backport-3.12.x, backport-4.2.x

#7258 ISO19139 / ISO19115-3.2018 / Don't index resource identifiers with empty code
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
Labels: backport-4.2.x

#7244 Set html emails as utf-8
  core/src/main/java/org/fao/geonet/util/MailUtil.java
Labels: backport-3.12.x, backport-4.2.x

#7289 Do not break link in the middle of a word.
  web-ui/src/main/resources/catalog/style/gn.less
Labels: backport-4.2.x

#7290 Search / Aggregation on organisation in Dutch
  web/src/main/webResources/WEB-INF/data/config/index/records.json
Labels: index structure change, backport-4.2.x

#7293 WMS tile images - if HEAD request fails, default to OL image src set
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
Labels: backport-4.2.x

#7232 Metadata editor / recommended values for fields show an empty value.
  web-ui/src/main/resources/catalog/components/edit/editorhelper/EditorHelperDirective.js
  web-ui/src/main/resources/catalog/components/edit/editorhelper/partials/editorhelper.html
Labels: backport-4.2.x

#7295 Notifications / Errors / Fix message on group creation
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
Labels: backport-4.2.x

#6869 Extend ElasticSearch proxy to filter out elements defined in the schema filters configurations
  core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
  core/src/main/java/org/fao/geonet/kernel/XmlSerializer.java
  core/src/main/java/org/fao/geonet/kernel/mef/ExportFormat.java
  core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchema.java
  core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchemaOperationFilter.java
  core/src/test/java/org/fao/geonet/kernel/XmlSerializerIntegrationTest.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/link-utility.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema-ident.xml
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml
  services/pom.xml
  services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
  web/src/main/webapp/xml/validation/schemaPlugins/schema-ident.xsd
Labels: index structure change

#7297 Fix metadata editor tooltips close button when using the icon mode
  web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
Labels: backport-4.2.x

#7307 Fix the check to display the Transfer ownership option in the metadata detail page
  web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
Labels: backport-4.2.x
