Repository geonetwork/core-geonetwork, pull requests merged in 2023-10, with the labels that each got.

#7375 Update MkDocs configuration to publish to gh-pages branch
  docs/manual/README.md
  docs/manual/mkdocs.yml
Labels: backport-3.12.x, backport-4.2.x

#7279 [BP] Fix working copy display so that links go to working copy
  services/src/main/java/org/fao/geonet/api/ApiUtils.java
  services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
  services/src/main/java/org/fao/geonet/api/related/Related.java
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
  web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
  web-ui/src/main/resources/catalog/components/search/resultsview/gridRelated.js
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Labels: bug

#7276 Make samples loading fail if uuid already exists
  services/src/main/java/org/fao/geonet/api/records/MetadataSampleApi.java
Labels: backport-3.12.x, backport-4.2.x

#7407 Fixed typos in code_quality readme
  code_quality/README.md
Labels: backport-4.2.x

#7401 Doc / Fix list layout on the website
  docs/manual/docs/overview/change-log/version-4.2.6.md
Labels: backport-4.2.x

#7402 Record view / fix double approved parameter in the metadata working copy page, for the buttons in the online resources panel.
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
Labels: bug, backport-4.2.x

#7419 Update the CONTRIBUTING guide to detail the steps, before merging the…
  CONTRIBUTING.md
Labels: backport-4.2.x

#7418 Fixed typos and updated SearchManager to EsSearchManager in core readme
  core/README.md
Labels: backport-4.2.x

#7422 Change the url the icon in the homepage is linking to
  docs/manual/mkdocs.yml
Labels: backport-3.12.x, backport-4.2.x

#7417 Reset user password dialog - don't display the field to request the old password for administrators
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: backport-3.12.x, backport-4.2.x

#7413 Site information / manage Elasticsearch exceptions when trying to retrieve the index information
  index/src/main/java/org/fao/geonet/index/es/EsRestClient.java
  services/src/main/java/org/fao/geonet/api/site/SiteInformation.java
Labels: backport-4.2.x

#7428 Metadata editor / ISO19115-3.2008 / Filter out metadata templates inthe online resources dialog
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/config/associated-panel/default.json
Labels: backport-4.2.x

#7424 Sort the portals by label, not by name (identifier)
  web-ui/src/main/resources/catalog/components/usersearches/UserSearchesDirective.js
  web-ui/src/main/resources/catalog/components/usersearches/partials/portalswitcher.html
Labels: backport-4.2.x

#7404 Rename ElasticSearch to Elasticsearch
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  core/src/test/java/org/fao/geonet/kernel/ElasticsearchIndexingTest.java
  csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2Es.java
  csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2EsTest.java
  csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswSortBy2EsTest.java
  csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/EsJsonHelper.java
  docs/manual/docs/install-guide/installing-from-war-file.md
  docs/manual/docs/maintainer-guide/statistics/index.md
  docs/manual/docs/maintainer-guide/statistics/setup-elasticsearch.md
  docs/manual/docs/maintainer-guide/statistics/setup-geonetwork.md
  services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/components/viewer/heatmap/HeatmapDirective.js
  web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterService.js
  web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web/src/main/webapp/xml/validation/schemaPlugins/schema-ident.xsd
Labels: backport-4.2.x

#6978 Fix exception handling from schematron validation so that it flags the metadata as invalid if there is an exception
  core/src/main/java/org/fao/geonet/kernel/AbstractSchematronValidator.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
Labels: backport-3.12.x, backport-4.2.x

#7432 Transifex updates
  web-ui/src/main/resources/catalog/locales/ca-admin.json
  web-ui/src/main/resources/catalog/locales/ca-core.json
  web-ui/src/main/resources/catalog/locales/cs-admin.json
  web-ui/src/main/resources/catalog/locales/cs-core.json
  web-ui/src/main/resources/catalog/locales/cs-editor.json
  web-ui/src/main/resources/catalog/locales/cs-v4.json
  web-ui/src/main/resources/catalog/locales/da-admin.json
  web-ui/src/main/resources/catalog/locales/da-core.json
  web-ui/src/main/resources/catalog/locales/de-admin.json
  web-ui/src/main/resources/catalog/locales/de-core.json
  web-ui/src/main/resources/catalog/locales/es-admin.json
  web-ui/src/main/resources/catalog/locales/es-core.json
  web-ui/src/main/resources/catalog/locales/fi-admin.json
  web-ui/src/main/resources/catalog/locales/fi-core.json
  web-ui/src/main/resources/catalog/locales/fr-admin.json
  web-ui/src/main/resources/catalog/locales/fr-core.json
  web-ui/src/main/resources/catalog/locales/is-admin.json
  web-ui/src/main/resources/catalog/locales/is-core.json
  web-ui/src/main/resources/catalog/locales/it-admin.json
  web-ui/src/main/resources/catalog/locales/it-core.json
  web-ui/src/main/resources/catalog/locales/ko-admin.json
  web-ui/src/main/resources/catalog/locales/ko-core.json
  web-ui/src/main/resources/catalog/locales/nl-admin.json
  web-ui/src/main/resources/catalog/locales/nl-core.json
  web-ui/src/main/resources/catalog/locales/nl-v4.json
  web-ui/src/main/resources/catalog/locales/pt-admin.json
  web-ui/src/main/resources/catalog/locales/pt-core.json
  web-ui/src/main/resources/catalog/locales/ru-admin.json
  web-ui/src/main/resources/catalog/locales/ru-core.json
  web-ui/src/main/resources/catalog/locales/sk-admin.json
  web-ui/src/main/resources/catalog/locales/sk-core.json
  web-ui/src/main/resources/catalog/locales/sv-admin.json
  web-ui/src/main/resources/catalog/locales/sv-core.json
  web-ui/src/main/resources/catalog/locales/zh-admin.json
  web-ui/src/main/resources/catalog/locales/zh-core.json
Labels: backport-4.2.x

#7373 Fix issue with canViewRecord when calling related api
  services/src/main/java/org/fao/geonet/api/ApiUtils.java
  services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataAssociatedApi.java
  services/src/main/java/org/fao/geonet/api/related/Related.java
Labels: backport-4.2.x

#7430 Fixed typos, formatting and numbering
  domain/README.md
  domain/Readme.md
Labels: backport-4.2.x

#7441 Remove the `Download metadata` button on the Metadata page
  web-ui/src/main/resources/catalog/views/default/templates/recordView/metadata.html
Labels: backport-4.2.x

#7440 Standard / Feature catalogues / Do not index empty codelist value
  schemas/iso19110/src/main/plugin/iso19110/index-fields/index.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
Labels: backport-4.2.x

#7439 Search results / Fix button size
  web-ui/src/main/resources/catalog/components/common/savedselections/partials/action.html
Labels: backport-4.2.x

#7446 Fix path for serverTime / sessionExpiry when GeoNetwork runs in / It creates these cookies per each path.
  core/src/main/java/org/geonetwork/http/SessionTimeoutCookieFilter.java
Labels: backport-3.12.x, backport-4.2.x

#7437 Indexing / Add related record title to the full text search
  web/src/main/webResources/WEB-INF/data/config/index/records.json
Labels: index structure change

#7442 List styling for related records
  web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
  web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
Labels: backport-4.2.x

#6977 Remove exception class name from the error message
  services/src/main/java/org/fao/geonet/api/ApiError.java
  services/src/test/java/org/fao/geonet/api/groups/GroupsApiTest.java
  services/src/test/java/org/fao/geonet/api/identifiers/IdentifiersApiTest.java
  services/src/test/java/org/fao/geonet/api/records/MetadataValidateApiTest.java
  services/src/test/java/org/fao/geonet/api/users/UsersApiTest.java
  services/src/test/java/org/fao/geonet/services/metadata/BatchEditsServiceTest.java
Labels: backport-3.12.x, backport-4.2.x
