Repository geonetwork/core-geonetwork, pull requests merged in 2023-11, with the labels that each got.

#7463 API / Batch editing / XPath / Add support for attribute with namespace.
  core/src/main/java/org/fao/geonet/kernel/EditLib.java
  services/src/test/java/org/fao/geonet/services/metadata/BatchEditsServiceTest.java
Labels: backport-4.2.x

#7467 change label to "Access to the catalogue"
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/chi/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/swe/strings.xml
Labels: backport-4.2.x

#7454 Add node identifier parameter for xlst processing. Required in skin.xsl
  services/src/main/java/org/fao/geonet/guiapi/search/XsltResponseWriter.java
Labels: backport-3.12.x, backport-4.2.x

#7438 Editor / Remove extra space on mandatory add action
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: backport-4.2.x

#7471 Fixed broken links and formatting in BUILDING.md
  software_development/BUILDING.md
Labels: backport-4.2.x

#7464 Batch edit access level for editor role
  core/src/main/java/org/fao/geonet/util/UserUtil.java
  services/src/main/java/org/fao/geonet/api/processing/DatabaseProcessApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
  services/src/main/java/org/fao/geonet/api/records/editing/BatchEditsApi.java
  services/src/main/java/org/fao/geonet/api/standards/StandardsApi.java
  web-ui/src/main/resources/catalog/templates/editor/editorboard.html
Labels: backport-3.12.x, backport-4.2.x

#7483 Fix url link in full view. bracket ") " could be included in link
  web/src/main/webapp/xslt/common/utility-tpl.xsl
Labels: bug, backport-3.12.x, backport-4.2.x

#7429 Change the structure of the MkDocs Assets
  docs/manual/help.yml
  docs/manual/mkdocs.yml
  docs/manual/overrides/assets/images/geonetwork-logo.png
  docs/manual/overrides/assets/images/geonetwork-logo.svg
  docs/manual/overrides/assets/stylesheets/extra.css
Labels: backport-3.12.x, backport-4.2.x

#7487 Update manual links to use https://docs.geonetwork-opensource.org/
  web-ui/src/main/resources/catalog/components/common/needhelp/NeedHelpDirective.js
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html
  web/src/main/webapp/WEB-INF/data/data/resources/config/manual.json
Labels: backport-3.12.x, backport-4.2.x

#7403 Add more db information to the site information page.
  services/src/main/java/org/fao/geonet/api/site/SiteInformation.java
  web-ui/src/main/resources/catalog/locales/en-admin.json
Labels: backport-4.2.x

#7496 Check http links in documentation
  docs/manual/docs/administrator-guide/configuring-the-catalog/inspire-configuration.md
  docs/manual/docs/administrator-guide/configuring-the-catalog/map-server-configuration.md
  docs/manual/docs/administrator-guide/configuring-the-catalog/system-configuration.md
  docs/manual/docs/administrator-guide/managing-classification-systems/managing-categories.md
  docs/manual/docs/administrator-guide/managing-users-and-groups/authentication-mode.md
  docs/manual/docs/annexes/standards/iso19115-3.2018.md
  docs/manual/docs/help/index.md
  docs/manual/docs/install-guide/configuring-database.md
  docs/manual/docs/install-guide/installing-from-source-code.md
  docs/manual/docs/install-guide/installing-from-war-file.md
  docs/manual/docs/overview/change-log/version-3.0.1.md
  docs/manual/docs/overview/change-log/version-3.2.0.md
  docs/manual/docs/overview/change-log/version-4.2.0.md
  docs/manual/docs/overview/index.md
  docs/manual/docs/tutorials/inspire/download-atom.md
  docs/manual/docs/tutorials/inspire/download-geoserver.md
  docs/manual/docs/tutorials/inspire/index.md
  docs/manual/docs/tutorials/inspire/view-geoserver.md
  docs/manual/docs/tutorials/inspire/view-mapserver.md
  docs/manual/docs/user-guide/associating-resources/linking-online-resources.md
  docs/manual/docs/user-guide/describing-information/index.md
  docs/manual/docs/user-guide/describing-information/inspire-editing.md
  docs/manual/docs/user-guide/harvesting/index.md
  docs/manual/docs/user-guide/workflow/batchupdate-from-admin.md
Labels: backport-4.2.x

#7501 Security / Jolokia update.
  pom.xml
  web/src/main/resources/jolokia-access.xml
  web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
Labels: backport-3.12.x, backport-4.2.x

#7507 Docs / Fix the mike version to 2.0.0 and change the parameter --no-redirect to --alias-type=copy (changed in mike 2.0.0)
  .github/workflows/docs.yml
  docs/manual/requirements.txt
Labels: backport-4.2.x

#7494 CSW Harvester / Don't set a default search filter field
  web-ui/src/main/resources/catalog/components/admin/harvester/HarvesterDirective.js
Labels: backport-4.2.x

#7368 Elasticsearch / Update to 7.17.15
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  index/src/main/java/org/fao/geonet/index/es/EsRestClient.java
  pom.xml
  workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
Labels: backport-4.2.x

#7517 Fix some cases that were not considering both message and description when displaying errors.
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
  web-ui/src/main/resources/catalog/components/search/resultsview/SelectionDirective.js
  web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js
Labels: bug, backport-3.12.x, backport-4.2.x

#7516 When getting locale message, default locale to LocaleContextHolder when locale is null
  core/src/main/java/org/fao/geonet/languages/LocaleMessages.java
Labels: backport-3.12.x, backport-4.2.x

#7495 Fix language for region picker directives
  web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/components/utility/partials/regionpicker.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
Labels: backport-4.2.x
