Repository geonetwork/core-geonetwork, pull requests merged in 2023-12, with the labels that each got.

#7491 Remote INSPIRE Atom Feeds harvester - Remove duplicates by dataset identifier
  inspire-atom/src/main/java/org/fao/geonet/inspireatom/harvester/InspireAtomHarvester.java
Labels: backport-3.12.x, backport-4.2.x

#7492 INSPIRE Atom Search - add missing filter by feed dataset identifiers
  inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomSearch.java
Labels: backport-4.2.x

#7503 Metadata workflow / Record view / reload the page with the approved version when cancelling a working copy
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
  web-ui/src/main/resources/catalog/locales/ca-core.json
  web-ui/src/main/resources/catalog/locales/cs-core.json
  web-ui/src/main/resources/catalog/locales/da-core.json
  web-ui/src/main/resources/catalog/locales/de-core.json
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/locales/es-core.json
  web-ui/src/main/resources/catalog/locales/fi-core.json
  web-ui/src/main/resources/catalog/locales/fr-core.json
  web-ui/src/main/resources/catalog/locales/is-core.json
  web-ui/src/main/resources/catalog/locales/it-core.json
  web-ui/src/main/resources/catalog/locales/ko-core.json
  web-ui/src/main/resources/catalog/locales/nl-core.json
  web-ui/src/main/resources/catalog/locales/pt-core.json
  web-ui/src/main/resources/catalog/locales/ru-core.json
  web-ui/src/main/resources/catalog/locales/sk-core.json
  web-ui/src/main/resources/catalog/locales/sv-core.json
  web-ui/src/main/resources/catalog/locales/zh-core.json
  web-ui/src/main/resources/catalog/views/default/templates/recordView/recordView.html
Labels: backport-4.2.x

#7510 Reset user password dialog - don't display the field to request the old password for administrators - unify UI check with backend check
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: backport-4.2.x

#7449 Admin console / Improve form checks
  domain/src/main/java/org/fao/geonet/domain/Group.java
  web-ui/src/main/resources/catalog/js/admin/CategoriesController.js
  web-ui/src/main/resources/catalog/js/admin/SourcesController.js
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/templates/admin/classification/categories.html
  web-ui/src/main/resources/catalog/templates/admin/report/report-filedownload-metadata.html
  web-ui/src/main/resources/catalog/templates/admin/report/report-fileupload-metadata.html
  web-ui/src/main/resources/catalog/templates/admin/report/report-internal-metadata.html
  web-ui/src/main/resources/catalog/templates/admin/report/report-updated-metadata.html
  web-ui/src/main/resources/catalog/templates/admin/report/report-users.html
  web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
  web-ui/src/main/resources/catalog/templates/admin/settings/static-pages.html
  web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v441/migrate-default.sql
Labels: db change, backport-4.2.x

#7535 Fix check to verify if a group has enabled the workflow, checking if the workflow is also enabled
  core/src/main/java/org/fao/geonet/util/WorkflowUtil.java
  core/src/test/java/org/fao/geonet/util/WorkflowUtilTest.java
Labels: backport-4.2.x

#7445 OpenId / Use the user profile configured locally if the configuration option OPENIDCONNECT_USERPROFILEUPDATEENABLED is disabled
  core/src/main/java/org/fao/geonet/kernel/security/openidconnect/GeonetworkOidcUserService.java
  core/src/main/java/org/fao/geonet/kernel/security/openidconnect/OidcUser2GeonetworkUser.java
Labels: backport-4.2.x

#7525 Use Apache Commons Text library to escape JSON content in xslt processing
  core/src/main/java/org/fao/geonet/util/XslUtil.java
  schemas/dublin-core/src/main/plugin/dublin-core/index-fields/index.xsl
  schemas/iso19110/src/main/plugin/iso19110/index-fields/index.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/jsonld/iso19115-3.2018-to-jsonld.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index-subtemplate.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/utility-tpl.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl.xsl
  services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
  web/src/main/webapp/xslt/common/index-utils.xsl
Labels: backport-4.2.x

#7532 Don't display header menu and footer in single metadata PDF export
  web/src/main/webapp/xslt/skin/default/skin.xsl
Labels: bug, backport-3.12.x, backport-4.2.x

#7547 Add ownerId to geonet:info
  core/src/main/java/org/fao/geonet/constants/Edit.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
Labels: backport-3.12.x, backport-4.2.x

#7537 Elasticsearch index creation - log the exception when a parsing error of the index configuration file occurs
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
Labels: backport-4.2.x

#7538 Metadata indexing - create an organisation name field that tracks the organisations of the different types of contacts
  web/src/main/webResources/WEB-INF/data/config/index/records.json
Labels: index structure change, backport-4.2.x

#7555 Documentation / Update Elasticsearch installation page typos and remove the old elastic search documentation.
  docs/manual/docs/install-guide/installing-index.md
  docs/manual/docs/maintainer-guide/index.md
  docs/manual/docs/maintainer-guide/statistics/img/content-indexing.png
  docs/manual/docs/maintainer-guide/statistics/img/kibana-index-1.png
  docs/manual/docs/maintainer-guide/statistics/img/kibana-index-2.png
  docs/manual/docs/maintainer-guide/statistics/img/search-statistics-dashboards.png
  docs/manual/docs/maintainer-guide/statistics/img/search-statistics.png
  docs/manual/docs/maintainer-guide/statistics/index.md
  docs/manual/docs/maintainer-guide/statistics/setup-elasticsearch.md
  docs/manual/docs/maintainer-guide/statistics/setup-geonetwork.md
  docs/manual/docs/maintainer-guide/statistics/setup-kibana.md
  docs/manual/mkdocs.yml
Labels: backport-4.2.x, Documentation

#7546 Visual fix for icon text circles (firefox)
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Labels: backport-4.2.x

#7539 Harvesters without owner > cryptic parse exception
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet20/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
Labels: backport-4.2.x

#7558 Update iso19139 csw-full.xsl
  schemas/iso19139/src/main/plugin/iso19139/present/csw/csw-full.xsl
Labels: backport-3.12.x, backport-4.2.x

#7564 Remove ?debug from link to admin dashboard.
  web-ui/src/main/resources/catalog/components/utility/partials/indexerrorpanel.html
Labels: backport-4.2.x

#7566 Add German codelist translations for scope code
  schemas/iso19139/src/main/plugin/iso19139/loc/ger/codelists.xml
Labels: backport-4.2.x

#7568 Fix for absent language leading to spurious comma
  web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
Labels: backport-4.2.x

#7556 Overview not shown in PDF export when the overview image is stored in GeoNetwork and requires authentication to access it.
  services/src/main/java/org/fao/geonet/api/records/formatters/ImageReplacedElementFactory.java
Labels: backport-4.2.x
