Repository geonetwork/core-geonetwork, pull requests merged in 2023-07, with the labels that each got.

#7189 Remote INSPIRE ATOM Feed / code cleanup and optimisations for ATOM describe service
  domain/src/main/java/org/fao/geonet/domain/InspireAtomFeed.java
  domain/src/main/java/org/fao/geonet/repository/InspireAtomFeedRepository.java
  inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomServiceDescription.java
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
Labels: backport-3.12.x

#7178 API / Import record / Overwrite mode improvement.
  core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
  core/src/main/java/org/fao/geonet/kernel/mef/MEFLib.java
Labels: api change

#7182 Standard / ISO19110 / Add cardinality in default view
  schemas/iso19110/src/main/plugin/iso19110/index-fields/index.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/locales/nl-core.json
  web-ui/src/main/resources/catalog/style/gn_metadata.less
  web-ui/src/main/resources/catalog/views/default/directives/directive.js
  web-ui/src/main/resources/catalog/views/default/directives/partials/attributetable.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView/featurecatalogue.html
  web/src/main/webResources/WEB-INF/data/config/index/records.json
Labels: index structure change

#7216 ArcSDE harvester / If the metadata stored in ArcSDE is matched against a known metadata schema, harvest the record as it is.
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/arcsde/ArcSDEHarvester.java
Labels: backport-3.12.x

#7224 Use Apache Commons StringUtils to join keywords in atom service description
  inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomServiceDescription.java
Labels: backport-4.2.x

#7130 Update status emails to contain link to metadata which does not contain in anchor
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport-3.12.x, backport-4.2.x

#7062 Add support for OL Attributions
  web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
  web-ui/src/main/resources/catalog/js/jsonix/OWC_0_3_1.js
  web-ui/src/main/resources/catalog/style/gn_viewer.less
  web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
  web/src/main/webapp/WEB-INF/data/data/resources/map/config-viewer.xml
Labels: backport-3.12.x, backport-4.2.x

#7229 Map viewer / 'Default map' javascript error
  web-ui/src/main/resources/catalog/components/common/map/wmsQueue.js
Labels: backport-4.2.x

#7165 When authenticating user, only update the usergroups in the database if they have changed
  core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakUserUtils.java
  core/src/main/java/org/fao/geonet/kernel/security/openidconnect/OidcUser2GeonetworkUser.java
  core/src/main/java/org/fao/geonet/kernel/security/shibboleth/ShibbolethUserUtils.java
  domain/src/main/java/org/fao/geonet/domain/UserGroup.java
  domain/src/main/java/org/fao/geonet/repository/UserGroupRepositoryCustom.java
  domain/src/main/java/org/fao/geonet/repository/UserGroupRepositoryCustomImpl.java
  domain/src/test/java/org/fao/geonet/repository/UserGroupRepositoryTest.java
Labels: backport-3.12.x, backport-4.2.x

#7233 Fix wmsQueue clear method logic
  web-ui/src/main/resources/catalog/components/common/map/wmsQueue.js
Labels: backport-4.2.x

#7015 Update skin.xsl so that it works better in nojs mode.
  core/src/main/java/org/fao/geonet/kernel/setting/SettingManager.java
  core/src/main/java/org/fao/geonet/util/XslUtil.java
  services/src/main/java/org/fao/geonet/api/records/formatters/XsltFormatter.java
  web/src/main/webapp/xslt/common/render-html.xsl
  web/src/main/webapp/xslt/skin/default/skin.xsl
Labels: backport-3.12.x, backport-4.2.x

#7237 Escape {{ to avoid error parsing argument.
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
Labels: backport-3.12.x, backport-4.2.x

#7245 Fix German typo of the label for 'otherRestrictions'
  schemas/iso19139/src/main/plugin/iso19139/loc/ger/codelists.xml
Labels: backport-3.12.x, backport-4.2.x

#7249 Fix record history parameter name. Related to #7074
  web-ui/src/main/resources/catalog/components/history/GnHistoryService.js
Labels: backport-3.12.x, backport-4.2.x
