Repository geonetwork/core-geonetwork, pull requests merged in 2023-05, with the labels that each got.

#7045 disable link to parent button to use ng-disabled
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linkServiceToDataset.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linkToMd.html
Labels: backport-3.12.x

#7005 Add migration for static pages
  web/src/main/webResources/WEB-INF/config-db/database_migration.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v424/migrate-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v424/migrate-db-mysql.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v424/migrate-db-oracle.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v424/migrate-db-sqlserver.sql
Labels: db change

#7092 Metadata workflow / send mail notifications for metadata status change to DRAFT when doing a rejection, not when creating a working copy
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
Labels: backport-3.12.x

#7105 Update sortby-combo directive to use the field name and the sort order information.
  web-ui/src/main/resources/catalog/components/search/formfields/partials/sortByCombo.html
  web-ui/src/main/resources/catalog/locales/ca-core.json
  web-ui/src/main/resources/catalog/locales/ca-v4.json
  web-ui/src/main/resources/catalog/locales/cs-core.json
  web-ui/src/main/resources/catalog/locales/cs-v4.json
  web-ui/src/main/resources/catalog/locales/da-core.json
  web-ui/src/main/resources/catalog/locales/da-v4.json
  web-ui/src/main/resources/catalog/locales/de-core.json
  web-ui/src/main/resources/catalog/locales/de-v4.json
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/locales/en-v4.json
  web-ui/src/main/resources/catalog/locales/es-core.json
  web-ui/src/main/resources/catalog/locales/es-v4.json
  web-ui/src/main/resources/catalog/locales/fi-core.json
  web-ui/src/main/resources/catalog/locales/fi-v4.json
  web-ui/src/main/resources/catalog/locales/fr-core.json
  web-ui/src/main/resources/catalog/locales/fr-v4.json
  web-ui/src/main/resources/catalog/locales/is-core.json
  web-ui/src/main/resources/catalog/locales/is-v4.json
  web-ui/src/main/resources/catalog/locales/it-core.json
  web-ui/src/main/resources/catalog/locales/it-v4.json
  web-ui/src/main/resources/catalog/locales/ko-core.json
  web-ui/src/main/resources/catalog/locales/ko-v4.json
  web-ui/src/main/resources/catalog/locales/nl-core.json
  web-ui/src/main/resources/catalog/locales/nl-v4.json
  web-ui/src/main/resources/catalog/locales/pt-core.json
  web-ui/src/main/resources/catalog/locales/pt-v4.json
  web-ui/src/main/resources/catalog/locales/ru-core.json
  web-ui/src/main/resources/catalog/locales/ru-v4.json
  web-ui/src/main/resources/catalog/locales/sk-core.json
  web-ui/src/main/resources/catalog/locales/sk-v4.json
  web-ui/src/main/resources/catalog/locales/sv-core.json
  web-ui/src/main/resources/catalog/locales/sv-v4.json
  web-ui/src/main/resources/catalog/locales/zh-core.json
  web-ui/src/main/resources/catalog/locales/zh-v4.json
Labels: translation key change

#7118 Index configuration / define dynamic template for conformTo_* fields pattern
  web/src/main/webResources/WEB-INF/data/config/index/records.json
Labels: index structure change

#7116 Update link type protocol values for map layers
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/views/api/index_debug.html
Labels: bug, update-release-notes
