Repository geonetwork/core-geonetwork, pull requests merged in 2023-01, with the labels that each got.

#6711 Allow for null passwords when creating user via api.
  core/src/main/java/org/fao/geonet/kernel/security/GeonetworkAuthenticationProvider.java
  services/src/main/java/org/fao/geonet/api/users/UsersApi.java
  services/src/main/java/org/fao/geonet/api/users/validation/UserDtoValidator.java
Labels: backport-3.12.x

#6752 Map / Profile directive / remove goog calls
  web-ui/src/main/resources/catalog/components/common/openlayers/olProfileDirective.js
  web-ui/src/main/resources/catalog/components/common/openlayers/olProfileService.js
Labels: backport-3.12.x

#6722 Report file download - check if related file upload is available
  services/src/main/java/org/fao/geonet/api/reports/ReportDownloads.java
Labels: backport-3.12.x

#6686 Improve temporary file management
  common/src/main/java/org/fao/geonet/utils/IO.java
  core/src/main/java/org/fao/geonet/kernel/backup/ArchiveAllMetadataJob.java
  core/src/main/java/org/fao/geonet/kernel/mef/MEF2Exporter.java
  core/src/main/java/org/fao/geonet/kernel/mef/MEFExporter.java
  core/src/main/java/org/fao/geonet/resources/S3Resources.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/Harvester.java
  services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsActionsApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterAdminApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/PDF.java
  services/src/main/java/org/fao/geonet/guiapi/search/XsltResponseWriter.java
  services/src/main/java/org/fao/geonet/services/rdf/GetPublicMetadataAsRdf.java
  services/src/main/java/org/fao/geonet/services/resources/DownloadArchive.java
Labels: bug

#6750 create resource folder if missing during metadata loading.
  core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
Labels: backport-3.12.x

#6712 Update userapi so that it will allow administrators to pre-create/update user profile information when using service provider
  services/src/main/java/org/fao/geonet/api/users/UsersApi.java
Labels: backport-3.12.x

#6588 Search / Multilingual support for contact, links and overview description (indexing and aggregations)
  schemas/dublin-core/src/main/plugin/dublin-core/index-fields/index.xsl
  schemas/iso19115-3.2018/src/main/java/org/fao/geonet/schema/iso19115_3_2018/ISO19115_3_2018SchemaPlugin.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/config/associated-panel/default.json
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/link-utility.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/utility-fn.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/dq-report-add.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/fcats-file-add.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/legend-add.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/onlinesrc-add.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/elasticsearch/EsClient.js
  web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
  web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
  web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
  web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/views/default/templates/recordView/thumbnails.html
  web/src/main/webResources/WEB-INF/data/config/index/records.json
  web/src/main/webapp/xslt/common/index-utils.xsl
Labels: schema plugin change, index structure change

#6756 Metadata status change: don't execute mail notification logic if there are no users to notify
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
Labels: backport-3.12.x
