Repository geonetwork/core-geonetwork, pull requests merged in 2024-11, with the labels that each got.

#8466 getResourceInternal implementation for cmis and jcloud
  core/src/main/java/org/fao/geonet/util/XslUtil.java
  datastorages/cmis/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
  datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
Labels: backport 4.2.x

#8416 Configuration to display an application banner
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/style/gn_search.less
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
  web-ui/src/main/resources/catalog/views/default/directives/directive.js
  web-ui/src/main/resources/catalog/views/default/directives/partials/applicationBanner.html
  web-ui/src/main/resources/catalog/views/default/templates/index.html
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v446/migrate-default.sql
Labels: backport 4.2.x

#8485 GeoTools 32.0 update and JTS 1.20.0 update
  pom.xml
Labels: backport 4.2.x, changelog

#7707 Enhance static page with group user accessibility
  domain/src/main/java/org/fao/geonet/domain/page/Page.java
  domain/src/main/java/org/fao/geonet/repository/page/PageRepository.java
  services/src/main/java/org/fao/geonet/api/groups/GroupsApi.java
  services/src/main/java/org/fao/geonet/api/pages/PageProperties.java
  services/src/main/java/org/fao/geonet/api/pages/PagesAPI.java
  web-ui/src/main/resources/catalog/js/admin/StaticPagesController.js
  web-ui/src/main/resources/catalog/locales/en-v4.json
  web-ui/src/main/resources/catalog/templates/admin/settings/static-pages.html
Labels: enhancement, backport 4.2.x

#8376 Change icon for the layer tools in the layer manager panel on the map page
  web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
  web-ui/src/main/resources/catalog/style/gn_viewer.less
Labels: backport 4.2.x

#8479 Metadata editor / Fix display of multiple choice elements with custom label
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: backport 4.2.x

#8497 Metadata publication notifications / allow to configure the mail format
  docs/manual/docs/administrator-guide/configuring-the-catalog/img/feedback-email.png
  docs/manual/docs/administrator-guide/configuring-the-catalog/img/feedback-multilingual.png
  docs/manual/docs/administrator-guide/configuring-the-catalog/system-configuration.md
  services/src/main/java/org/fao/geonet/util/MetadataPublicationMailNotifier.java
  web/src/main/webResources/WEB-INF/config.properties
Labels: backport 4.2.x

#8478 Sort groups alphabetically on the new account and report pages
  web-ui/src/main/resources/catalog/components/utility/UtilityService.js
  web-ui/src/main/resources/catalog/js/LoginController.js
  web-ui/src/main/resources/catalog/js/admin/ReportController.js
Labels: backport 4.2.x

#8508 Metadata editor / Regions picker display empty entry form the metadata regions dao
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Labels: backport 4.2.x

#8427 Update file upload so that it has better error support.
  core/src/main/java/org/fao/geonet/api/exception/GeonetMaxUploadSizeExceededException.java
  core/src/main/java/org/fao/geonet/util/FileUtil.java
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
  web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
  web-ui/src/main/resources/catalog/locales/en-v4.json
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: bug, backport 4.2.x

#8513 [Backport 4.2.x] Update file upload so that it has better error support.
  core/src/main/java/org/fao/geonet/api/exception/GeonetMaxUploadSizeExceededException.java
  core/src/main/java/org/fao/geonet/util/FileUtil.java
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
  web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
  web-ui/src/main/resources/catalog/locales/en-v4.json
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: bug

#8482 Directory entries / Fix parsing of sorting configuration
  web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
  web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
Labels: bug, backport 4.2.x

#6984 Component to allow checking duplicated metadata values for title, alternative title and resource identifier in the metadata editor and display a message to the user
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
  services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
  web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
  web-ui/src/main/resources/catalog/locales/en-editor.json
Labels: backport 4.2.x

#8518 Remove usage of ECMASCRIPT6 const keyword
  web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
Labels: backport 4.2.x

#8512 Add better Jcloud versioning supports
  core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
  datastorages/cmis/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
  datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
  datastorages/jcloud/src/main/java/org/fao/geonet/resources/JCloudConfiguration.java
  datastorages/jcloud/src/main/resources/config-store/config-jcloud-overrides.properties
  datastorages/jcloud/src/main/resources/config-store/config-jcloud.xml
  datastorages/s3/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
Labels: backport 4.2.x

#8522 Change ESAPI logger to SLF4J using log4j2
  web/src/main/webapp/WEB-INF/classes/ESAPI.properties
Labels: backport 4.2.x

#8492 Batch selection is not in sync between search results and record view.
  core/src/main/java/org/fao/geonet/kernel/SelectionManager.java
  services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
Labels: backport 4.2.x

#8523 Use case insensitive username for login and reset password
  docs/manual/docs/administrator-guide/managing-users-and-groups/creating-user.md
  docs/manual/docs/administrator-guide/managing-users-and-groups/img/password-forgot.png
  docs/manual/docs/administrator-guide/managing-users-and-groups/img/selfregistration-start.png
  docs/manual/docs/administrator-guide/managing-users-and-groups/index.md
  docs/manual/docs/administrator-guide/managing-users-and-groups/user-reset-password.md
  docs/manual/docs/administrator-guide/managing-users-and-groups/user-self-registration.md
  docs/manual/mkdocs.yml
  domain/src/main/java/org/fao/geonet/repository/UserRepository.java
  domain/src/main/java/org/fao/geonet/repository/UserRepositoryCustom.java
  domain/src/main/java/org/fao/geonet/repository/UserRepositoryCustomImpl.java
  domain/src/test/java/org/fao/geonet/repository/UserRepositoryTest.java
  services/src/main/java/org/fao/geonet/api/users/PasswordApi.java
  web-ui/src/main/resources/catalog/js/LoginController.js
Labels: backport 4.2.x
