Repository geonetwork/core-geonetwork, pull requests merged in 2024-03, with the labels that each got.

#7743 Update lodash to version 4.17.21
  web-ui/src/main/resources/catalog/lib/lodash/lodash.min.js
Labels: backport 4.2.x

#7776 Doc / Editor configuration improvements
  schemas/config-editor.xsd
Labels: backport 3.12.x, backport 4.2.x

#7765 Harvesters / Reset harvester history pagination when selecting a harvester
  web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
Labels: backport 3.12.x, backport 4.2.x

#7791 Record view / ISO19139 / ISO19115-3.2008 display the unit part in @uom attribute, not the full url
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
Labels: backport 4.2.x

#7660 Harvester / Localfilesystem / Log properly to harvester log file.
  common/src/main/java/org/fao/geonet/Logger.java
  common/src/main/java/org/fao/geonet/utils/Log.java
  core/src/main/java/jeeves/server/context/BasicContext.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/BaseAligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/privileges.html
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/UpdateMetadataStatus.java
Labels: backport 4.2.x

#7756 INSPIRE / Add testsuite for IACS
  web/src/main/webapp/WEB-INF/config-etf-validator.xml
  web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl
Labels: backport 4.2.x

#7755 Standards / Formatter / Citation / Pick latest date
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/base.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/citation/base.xsl
Labels: backport 4.2.x

#7577 GeoNetwork harvester / Check if a resource exists to save it, instead of trying to retrieve the file details, to avoid confusing NoSuchFileException exception
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
Labels: backport 3.12.x, backport 4.2.x

#7648 Documentation / GeoNetwork 4.4 doing a release fixes
  docs/manual/docs/contributing/doing-a-release.md
Labels: Documentation

#7456 Extend http proxy to support urls with a duplicated parameter with different values
  web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
Labels: bug, backport 4.2.x

#7854 [Backport 4.2.x] Extend proxy to manage duplicated parameters
  web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
Labels: enhancement

#7647 Documentation / GeoNetwork 4.2 doing a release fixes
  docs/manual/docs/contributing/doing-a-release.md
Labels: Documentation

#7798 ISO19139 / Index online resources application profile element encoded as anchor
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
Labels: backport 4.2.x

#7858 Fix startup error. Follow up #7456
  web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
Labels: bug, backport 4.2.x

#7852 Documentation / GeoNetwork 3.12 doing a release fixes
  docs/manual/docs/contributing/doing-a-release.md
Labels: Documentation

#7810 OpenID / Cleaning up cached tokens
  core/src/main/java/org/fao/geonet/kernel/security/openidconnect/bearer/UserInfoCache.java
  core/src/test/java/org/fao/geonet/kernel/security/openidconnect/bearer/UserInfoCacheTest.java
Labels: backport 4.2.x

#7453 Optimise query used to retrieve metadata links results
  domain/src/main/java/org/fao/geonet/repository/specification/LinkSpecs.java
Labels: backport 3.12.x, backport 4.2.x

#7880 Map / Extent API / Background image failure if matrixset is not SRS code
  services/src/main/java/org/fao/geonet/api/records/extent/WMTSBaseMapRenderer.java
Labels: backport 4.2.x

#7879 Fill in 4.2.x releases for maintenance page
  docs/manual/docs/overview/change-log/maintenance/index.md
Labels: backport 4.2.x

#7881 Editor / GeoNames search failing with space
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Labels: backport 4.2.x

#7882 Indexing / Improve geometry indexing and display
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  services/src/main/java/org/fao/geonet/api/records/extent/MapRenderer.java
  web-ui/src/main/resources/catalog/views/default/config.js
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
Labels: backport 4.2.x

#7431 Passing key into update/remove process xslt for iso 19139 to fix issue with updating/deleting resources with same url
  schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl
  services/src/main/java/org/fao/geonet/api/records/model/related/RelatedItem.java
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
Labels: bug, index structure change

#7740 [Backport 4.2.x] Passing key into update/remove process xslt for iso 19139 to fix issue with updating/deleting resources with same url
  schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-add.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-remove.xsl
  services/src/main/java/org/fao/geonet/api/records/model/related/RelatedItem.java
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
Labels: bug, backport 3.12.x

#7875 Feedback / Fix email to multiple recipients
  services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
Labels: bug, backport 4.2.x

#6840 fix bug where LocalFileSystemHarvester does not update metadata
  domain/src/main/java/org/fao/geonet/repository/GeonetRepositoryImpl.java
Labels: backport 4.2.x

#7892 Fix typo in Messages.properties for metadata_approved_published_record_text
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
Labels: backport 4.2.x

#7896 Configure harvesters log to avoid application log duplicated in harvester_default.log file.
  web/src/main/webapp/WEB-INF/classes/log4j2-dev.xml
  web/src/main/webapp/WEB-INF/classes/log4j2-index.xml
  web/src/main/webapp/WEB-INF/classes/log4j2.xml
Labels: backport 4.2.x

#7596 Upgrade springdoc to 1.7.0
  pom.xml
  services/src/main/java/org/fao/geonet/api/OpenApiController.java
Labels: backport 4.2.x

#7864 Send email notification after workflow events have been processed
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
Labels: bug, backport 3.12.x, backport 4.2.x

#7514 Fix issue with saving metadata status causes indexing of metadata which causes issues for db rollbacks
  core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataStatus.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataStatus.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
  core/src/main/java/org/fao/geonet/kernel/metadata/StatusActions.java
  listeners/src/main/java/org/fao/geonet/listener/metadata/draft/ApprovePublishedRecord.java
  listeners/src/main/java/org/fao/geonet/listener/metadata/draft/ApproveRecord.java
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
Labels: bug, backport 3.12.x, backport 4.2.x

#7703 API / Import does not overwrite metadata if any validation status
  domain/src/main/java/org/fao/geonet/repository/MetadataValidationRepositoryCustom.java
Labels: backport 4.2.x

#7912 Search / May fail with random_score depending on ES config
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Labels: backport 4.2.x
