Repository geonetwork/core-geonetwork, pull requests merged in 2024-12, with the labels that each got.

#8530 Use the copyBlob to copy the resource with updated metadata
  datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
Labels: bug, backport 4.2.x

#8533 [Backport 4.2.x] Use the copyBlob to copy the resource with updated metadata
  core/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
Labels: bug

#8529 Update index to use a key with translations defined for map resource types
  docs/manual/docs/annexes/standards/iso19115-3.2018.md
  docs/manual/docs/annexes/standards/iso19139.md
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/codelists.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/codelists.xml
  schemas/iso19115-3.2018/src/test/resources/metadata-for-editing-light.xml
  schemas/iso19115-3.2018/src/test/resources/metadata-for-editing.xml
  schemas/iso19115-3.2018/src/test/resources/metadata-iso19139-for-editing.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ara/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/cat/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/chi/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/dut/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fin/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ger/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ita/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/nor/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/pol/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/por/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/rus/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/slo/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/spa/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/tur/codelists.xml
  web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
  web-ui/src/main/resources/catalog/locales/az-core.json
  web-ui/src/main/resources/catalog/locales/ca-core.json
  web-ui/src/main/resources/catalog/locales/cs-core.json
  web-ui/src/main/resources/catalog/locales/cy-core.json
  web-ui/src/main/resources/catalog/locales/da-core.json
  web-ui/src/main/resources/catalog/locales/de-core.json
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/locales/es-core.json
  web-ui/src/main/resources/catalog/locales/fi-core.json
  web-ui/src/main/resources/catalog/locales/fr-core.json
  web-ui/src/main/resources/catalog/locales/hy-core.json
  web-ui/src/main/resources/catalog/locales/is-core.json
  web-ui/src/main/resources/catalog/locales/it-core.json
  web-ui/src/main/resources/catalog/locales/ka-core.json
  web-ui/src/main/resources/catalog/locales/ko-core.json
  web-ui/src/main/resources/catalog/locales/nl-core.json
  web-ui/src/main/resources/catalog/locales/pt-core.json
  web-ui/src/main/resources/catalog/locales/ro-core.json
  web-ui/src/main/resources/catalog/locales/ru-core.json
  web-ui/src/main/resources/catalog/locales/sk-core.json
  web-ui/src/main/resources/catalog/locales/sv-core.json
  web-ui/src/main/resources/catalog/locales/uk-core.json
  web-ui/src/main/resources/catalog/locales/zh-core.json
  web-ui/src/main/resources/catalog/style/gn_icons.less
Labels: bug, backport 4.2.x

#8539 ISO19115.3-2008 / Fix typo in facsimile codelist value
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/codelists.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/codelists.xml
Labels: backport 4.2.x

#8514 Update db search and replace to support working copies
  core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataUtils.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
  domain/src/main/java/org/fao/geonet/repository/MetadataDraftRepository.java
  domain/src/main/java/org/fao/geonet/repository/MetadataRepository.java
  services/src/main/java/org/fao/geonet/api/processing/DatabaseProcessApi.java
  services/src/main/java/org/fao/geonet/api/processing/DatabaseProcessUtils.java
Labels: bug, backport 4.2.x

#8511 Restrict setting privileges on groups
  core/src/main/java/jeeves/component/ProfileManager.java
  core/src/main/java/org/fao/geonet/kernel/AccessManager.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataOperations.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java
  core/src/test/java/jeeves/interfaces/ProfileTest.java
  docs/manual/docs/administrator-guide/managing-users-and-groups/creating-group.md
  domain/src/main/java/org/fao/geonet/domain/Group.java
  domain/src/main/java/org/fao/geonet/domain/Profile.java
  domain/src/main/java/org/fao/geonet/repository/GroupRepository.java
  domain/src/main/java/org/fao/geonet/repository/specification/UserGroupSpecs.java
  domain/src/test/java/org/fao/geonet/repository/GroupRepositoryTest.java
  domain/src/test/java/org/fao/geonet/repository/specification/UserGroupSpecsTest.java
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
  services/src/main/java/org/fao/geonet/api/records/model/GroupPrivilege.java
  services/src/main/java/org/fao/geonet/api/users/UsersApi.java
  services/src/main/java/org/fao/geonet/api/users/transfer/OwnershipUtils.java
  web-ui/src/main/resources/catalog/components/common/share/ShareService.js
  web-ui/src/main/resources/catalog/components/common/share/partials/panel.html
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
Labels: backport 4.2.x

#8470 Attachments API use filename from Content-Disposition before url
  core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: backport 4.2.x

#8540 Editor / Improve support of schema having sibling elements for translation
  core/src/main/java/org/fao/geonet/kernel/EditLib.java
  schemas/iso19115-3.2018/src/main/java/org/fao/geonet/schema/iso19115_3_2018/ISO19115_3_2018SchemaPlugin.java
  schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java
  schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/MultilingualSchemaPlugin.java
  services/src/main/java/org/fao/geonet/api/records/editing/AjaxEditUtils.java
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
Labels: schema plugin change

#8268 Editor / Add keywords even if thesaurus not available in record languages
  core/src/main/java/org/fao/geonet/kernel/search/KeywordsSearcher.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields-keywords.xsl
  services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
  services/src/main/java/org/fao/geonet/services/thesaurus/GetKeywordByIdAsConcept.java
  services/src/main/java/org/fao/geonet/services/thesaurus/GetTopConcept.java
  web-ui/src/main/resources/catalog/components/ng-skos/templates/skos-concept.html
  web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusService.js
  web/src/main/webapp/xslt/services/thesaurus/to-jskos.xsl
Labels: api change

#8289 Restyled `default` address block
  web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html
  web-ui/src/main/resources/catalog/components/search/mdview/partials/individual.html
  web-ui/src/main/resources/catalog/locales/en-v4.json
  web-ui/src/main/resources/catalog/style/gn_metadata.less
  web-ui/src/main/resources/catalog/style/gn_variables.less
  web-ui/src/main/resources/catalog/views/default/less/gn_print_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_view.less
Labels: backport 4.2.x

#8556 Attachments API / Set content-length and close input stream when retrieving a metadata resource
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: backport 4.2.x

#8494 support section variable in manual url
  web-ui/src/main/resources/catalog/components/common/needhelp/NeedHelpDirective.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
Labels: backport 4.2.x

#8235 Formatters / Properly detect URL ending in 1,2,3 or 5
  web/src/main/webapp/xslt/common/utility-tpl.xsl
Labels: backport 4.2.x

#8041 Feature catalogue / Add table of content of feature types
  core/src/main/java/org/fao/geonet/util/XslUtil.java
  schemas/config-editor.xsd
  schemas/dublin-core/src/main/plugin/dublin-core/layout/evaluate.xsl
  schemas/iso19110/src/main/plugin/iso19110/formatter/iso19115-3.2018/view.xsl
  schemas/iso19110/src/main/plugin/iso19110/layout/config-editor.xml
  schemas/iso19110/src/main/plugin/iso19110/layout/evaluate.xsl
  schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
  schemas/iso19110/src/main/plugin/iso19110/loc/ara/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/cat/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/chi/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/dut/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/eng/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/fin/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/fre/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/ger/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/ita/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/nor/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/por/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/rus/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/slo/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/spa/strings.xml
  schemas/iso19110/src/main/plugin/iso19110/loc/tur/strings.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/mapping/core.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/evaluate.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-feature-catalogue.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/strings.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/strings.xml
  schemas/iso19139/src/main/plugin/iso19139/layout/evaluate.xsl
  web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
  web-ui/src/main/resources/catalog/js/edit/EditorController.js
  web/src/main/webapp/xslt/common/base-variables.xsl
  web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
Labels: changelog

#8568 [Backport 4.2.x] Update index to use a key with translations defined for map resource types
  docs/manual/docs/annexes/standards/iso19115-3.2018.md
  docs/manual/docs/annexes/standards/iso19139.md
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/codelists.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/codelists.xml
  schemas/iso19115-3.2018/src/test/resources/metadata-for-editing-light.xml
  schemas/iso19115-3.2018/src/test/resources/metadata-for-editing.xml
  schemas/iso19115-3.2018/src/test/resources/metadata-iso19139-for-editing.xml
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/loc/ara/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/cat/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/chi/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/dut/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/eng/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fin/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ger/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ita/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/nor/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/pol/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/por/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/rus/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/slo/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/spa/codelists.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/tur/codelists.xml
  web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
  web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextDirective.js
  web-ui/src/main/resources/catalog/components/viewer/searchlayerformap/SearchLayerForMapDirective.js
  web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
  web-ui/src/main/resources/catalog/locales/ca-core.json
  web-ui/src/main/resources/catalog/locales/cs-core.json
  web-ui/src/main/resources/catalog/locales/da-core.json
  web-ui/src/main/resources/catalog/locales/de-core.json
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/locales/es-core.json
  web-ui/src/main/resources/catalog/locales/fi-core.json
  web-ui/src/main/resources/catalog/locales/fr-core.json
  web-ui/src/main/resources/catalog/locales/is-core.json
  web-ui/src/main/resources/catalog/locales/it-core.json
  web-ui/src/main/resources/catalog/locales/ko-core.json
  web-ui/src/main/resources/catalog/locales/nl-core.json
  web-ui/src/main/resources/catalog/locales/pt-core.json
  web-ui/src/main/resources/catalog/locales/ru-core.json
  web-ui/src/main/resources/catalog/locales/sk-core.json
  web-ui/src/main/resources/catalog/locales/sv-core.json
  web-ui/src/main/resources/catalog/locales/zh-core.json
  web-ui/src/main/resources/catalog/style/gn_icons.less
  web-ui/src/main/resources/catalog/views/default/module.js
Labels: changelog

#8569 Admin / Schematron / Fix icon in rules
  web-ui/src/main/resources/catalog/components/admin/schematron/partials/criteria-viewer.html
Labels: backport 4.2.x

#8575 ISO19115-3.2008 - Add URL check schematron
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/schematron-rules-url-check.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/schematron-rules-url-check.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/ger/schematron-rules-url-check.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schematron/schematron-rules-url-check.sch
Labels: backport 4.2.x

#8561 [Backport 4.2.x] Move datastorage providers to maven modules and include them in the build on demand
  core/pom.xml
  core/src/main/resources/config-spring-geonetwork.xml
  datastorages/README.md
  datastorages/cmis/README.md
  datastorages/cmis/pom.xml
  datastorages/cmis/src/main/assembly/README.md
  datastorages/cmis/src/main/assembly/assembly.xml
  datastorages/cmis/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
  datastorages/cmis/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
  datastorages/cmis/src/main/java/org/fao/geonet/resources/CMISResources.java
  datastorages/cmis/src/main/java/org/fao/geonet/resources/CMISUtils.java
  datastorages/cmis/src/main/resources/config-store/config-cmis-overrides.properties
  datastorages/cmis/src/main/resources/config-store/config-cmis.xml
  datastorages/jcloud/README.md
  datastorages/jcloud/pom.xml
  datastorages/jcloud/src/main/assembly/README.md
  datastorages/jcloud/src/main/assembly/assembly.xml
  datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
  datastorages/jcloud/src/main/java/org/fao/geonet/resources/JCloudConfiguration.java
  datastorages/jcloud/src/main/java/org/fao/geonet/resources/JCloudMetadataNameValidator.java
  datastorages/jcloud/src/main/java/org/fao/geonet/resources/JCloudResources.java
  datastorages/jcloud/src/main/resources/config-store/config-jcloud-overrides.properties
  datastorages/jcloud/src/main/resources/config-store/config-jcloud.xml
  datastorages/jcloud/src/test/java/org/fao/geonet/api/records/attachments/JCloudStoreTest.java
  datastorages/pom.xml
  datastorages/s3/README.md
  datastorages/s3/pom.xml
  datastorages/s3/src/main/assembly/README.md
  datastorages/s3/src/main/assembly/assembly.xml
  datastorages/s3/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
  datastorages/s3/src/main/java/org/fao/geonet/resources/S3Credentials.java
  datastorages/s3/src/main/java/org/fao/geonet/resources/S3Resources.java
  datastorages/s3/src/main/resources/config-s3.xml
  datastorages/s3/src/test/java/org/fao/geonet/api/records/attachments/S3StoreTest.java
  pom.xml
  release/README.md
  release/src/markdown/html/footer.html
  release/src/markdown/html/header.html
  software_development/BUILDING.md
  web/pom.xml
Labels: changelog

#8579 Return xml inside JSON status
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
Labels: backport 4.2.x
