Repository geonetwork/core-geonetwork, pull requests merged in 2024-04, with the labels that each got.

#7915 Standard / ISO19115-3 / Editor / Uom encoding support
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl
Labels: backport 4.2.x

#7916 [Backport 3.12.x] Send email notification after workflow events have been processed #7864
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
Labels: bug

#7898 Hide the typeahead search suggestions when hitting the ENTER key in the search field without selecting a suggested value
  web-ui/src/main/resources/catalog/js/search/SearchController.js
  web-ui/src/main/resources/catalog/templates/editor/batchedit.html
  web-ui/src/main/resources/catalog/templates/editor/editorboard.html
  web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Labels: backport 4.2.x

#7450 metadata history viewing with user profile level
  core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
  docs/manual/docs/administrator-guide/configuring-the-catalog/img/metadata_history.png
  docs/manual/docs/administrator-guide/configuring-the-catalog/img/metadata_history_config.png
  docs/manual/docs/administrator-guide/configuring-the-catalog/system-configuration.md
  listeners/src/main/java/org/fao/geonet/listener/history/GenericMetadataEventListener.java
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
  services/src/main/java/org/fao/geonet/api/records/editing/BatchEditsApi.java
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/locales/ca-admin.json
  web-ui/src/main/resources/catalog/locales/cs-admin.json
  web-ui/src/main/resources/catalog/locales/da-admin.json
  web-ui/src/main/resources/catalog/locales/de-admin.json
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/locales/es-admin.json
  web-ui/src/main/resources/catalog/locales/fi-admin.json
  web-ui/src/main/resources/catalog/locales/fr-admin.json
  web-ui/src/main/resources/catalog/locales/is-admin.json
  web-ui/src/main/resources/catalog/locales/it-admin.json
  web-ui/src/main/resources/catalog/locales/ko-admin.json
  web-ui/src/main/resources/catalog/locales/nl-admin.json
  web-ui/src/main/resources/catalog/locales/pt-admin.json
  web-ui/src/main/resources/catalog/locales/ru-admin.json
  web-ui/src/main/resources/catalog/locales/sk-admin.json
  web-ui/src/main/resources/catalog/locales/sv-admin.json
  web-ui/src/main/resources/catalog/locales/zh-admin.json
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView/footer.html
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v444/migrate-default.sql
Labels: backport 3.12.x, backport 4.2.x

#7890 CSW server / Use portal filter in GetRecordById requests
  csw-server/src/main/java/org/fao/geonet/component/csw/GetRecordById.java
  csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
Labels: backport 4.2.x

#7946 Fix harvester URIMapper to handle local metadata
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/UriMapper.java
Labels: bug, backport 3.12.x, backport 4.2.x

#7927 Search Export CSV - Escape double-quotes with double-quotes instead of backslash
  web/src/main/webapp/xslt/services/csv/csv-search.xsl
Labels: backport 4.2.x

#7951 [Backport 3.12.x] Search Export CSV - Escape double-quotes with double-quotes instead of backslash
  web/src/main/webapp/xslt/services/csv/csv-search.xsl
Labels: bug

#7947 Remove q service, used to query in previous versions that used Lucene…
  services/src/main/java/org/fao/geonet/services/main/XmlSearch.java
  services/src/test/java/org/fao/geonet/services/main/XmlSearchTest.java
  web/src/main/webapp/WEB-INF/config/config-service-dcat-rdf.xml
  web/src/main/webapp/WEB-INF/config/config-service-search.xml
Labels: backport 4.2.x

#7956 Fix sql syntax for migrate to 4.4.4 script
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v444/migrate-default.sql
Labels: backport 4.2.x

#7918 [Backport 3.12.x] Passing key into update/remove process xslt for iso 19139 to fix issue with updating/deleting resources with same url
  schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-add.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-remove.xsl
  services/src/main/java/org/fao/geonet/api/records/model/related/RelatedItem.java
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
Labels: bug

#7905 Update springdoc to 1.8.0 and fix springdocs HashMap mapping in /db/translations
  pom.xml
  services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java
Labels: bug, backport 4.2.x

#7944 Doc / Editor configuration / Subtemplate insert mode
  schemas/config-editor.xsd
Labels: backport 4.2.x

#7910 Editor board / Use metadata database change date instead of the metadata dateStamp (xml)
  web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/locales/ca-core.json
  web-ui/src/main/resources/catalog/locales/cs-core.json
  web-ui/src/main/resources/catalog/locales/cy-core.json
  web-ui/src/main/resources/catalog/locales/da-core.json
  web-ui/src/main/resources/catalog/locales/de-core.json
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/locales/es-core.json
  web-ui/src/main/resources/catalog/locales/fi-core.json
  web-ui/src/main/resources/catalog/locales/fr-core.json
  web-ui/src/main/resources/catalog/locales/is-core.json
  web-ui/src/main/resources/catalog/locales/it-core.json
  web-ui/src/main/resources/catalog/locales/ko-core.json
  web-ui/src/main/resources/catalog/locales/nl-core.json
  web-ui/src/main/resources/catalog/locales/pt-core.json
  web-ui/src/main/resources/catalog/locales/ru-core.json
  web-ui/src/main/resources/catalog/locales/sk-core.json
  web-ui/src/main/resources/catalog/locales/sv-core.json
  web-ui/src/main/resources/catalog/locales/zh-core.json
Labels: backport 4.2.x

#7902 Update sort by fields configuration with language placeholder, to support sort by multilingual fields
  web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
  web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
Labels: backport 4.2.x

#7747 Support additional metadata processing when publishing / un-publishing metadata.
  services/src/main/java/org/fao/geonet/api/processing/report/MetadataProcessingReport.java
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
  services/src/main/java/org/fao/geonet/config/IPublicationConfig.java
  web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
Labels: backport 4.2.x

#7477 Workflow / Editor board / Add search configuration to display draft, approved record or both
  services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
  web-ui/src/main/resources/catalog/components/utility/DraftValidationWidget.js
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/components/utility/partials/draftvalidationwidget.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/locales/en-core.json
Labels: changelog

#7929 API / XSL / Use XSL output configuration (formatter, editor).
  common/src/main/java/org/fao/geonet/utils/Xml.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/common.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/view.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/citation/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/XsltFormatter.java
  services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-citation-html.html
  services/src/test/resources/org/fao/geonet/api/records/formatters/iso19139-citation-html.html
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
  web/src/main/webapp/xslt/base-layout.xsl
  web/src/main/webapp/xslt/common/render-html.xsl
  web/src/main/webapp/xslt/ui-metadata/edit/edit-embedded.xsl
  web/src/main/webapp/xslt/ui-metadata/form-builder-xml.xsl
  web/src/main/webapp/xslt/ui-metadata/menu-builder.xsl
Labels: schema plugin change, backport 4.2.x

#7989 Update the default sort field name in editor board and batch editor.
  web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
  web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
Labels: backport 4.2.x

#7977 fix for nextrecord in csw getrecords response when using pagination
  csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
Labels: backport 4.2.x

#7926 Report users - Display profile for Administrator / Guest profiles that are not related to groups
  services/src/main/java/org/fao/geonet/api/reports/ReportUsers.java
Labels: backport 4.2.x

#7893 Remove unused JeevesDelegatingFilterProxy servlet parameter 'loginService' configuration
  web/src/main/webResources/WEB-INF/web.xml
Labels: backport 4.2.x

#7974 French translation update for metadata_approved_published_record_text
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport 4.2.x

#7993 Test / Fix formatter test.
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/common.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/citation/view.xsl
  web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
Labels: backport 4.2.x

#7940 Standards / ISO19115-3 / Cleanup project specific template
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
Labels: backport 4.2.x

#7960 Standard / ISO19115-3 / Ensure dqm namespace is on top of the document
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/utility/create19115-3Namespaces.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/evaluate.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl
Labels: backport 4.2.x

#7919 Standard / ISO19115-3 / Feature catalogue improvements
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/evaluate.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml
Labels: backport 4.2.x
