Repository geonetwork/core-geonetwork, pull requests merged in 2024-06, with the labels that each got.

#8121 Remove link from admin-guide to schematron details as inappropriate
  docs/manual/docs/administrator-guide/managing-metadata-standards/configure-validation.md
Labels: backport 4.2.x

#8106 Update DOI exceptions to be multilingual exceptions
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  doi/src/main/java/org/fao/geonet/doi/client/BaseDoiClient.java
  doi/src/main/java/org/fao/geonet/doi/client/DoiDataciteClient.java
  doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
  doi/src/main/java/org/fao/geonet/doi/client/DoiMedraClient.java
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport 4.2.x

#8113 Indexing / ISO19115-3 / Avoir error on multiple contact website
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
Labels: backport 4.2.x

#7592 Harvesters / remove unused groupsCopyPolicy property
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/arcsde.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geoPREST.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork20.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.js
Labels: backport 4.2.x

#8091 Map / WPS / Add message for no recent process.
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
  web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
  web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
  web-ui/src/main/resources/catalog/components/viewer/wps/partials/recentprocesses.html
  web-ui/src/main/resources/catalog/locales/en-search.json
Labels: backport 4.2.x

#8033 update last changed date when restore metadata
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
Labels: bug, backport 4.2.x

#8086 Fix copy xsd files from metadata schemas to the web application
  core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
Labels: backport 3.12.x, backport 4.2.x

#7849 Support for translation providers in harvesters
  core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/BaseAligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractParams.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
  pom.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/translate.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/suggest.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/translate.xsl
  services/pom.xml
  services/src/main/java/org/fao/geonet/api/translationproviders/TranslationProvidersApi.java
  translationproviders/pom.xml
  translationproviders/src/main/java/org/fao/geonet/translations/ITranslationService.java
  translationproviders/src/main/java/org/fao/geonet/translations/TranslationFactory.java
  translationproviders/src/main/java/org/fao/geonet/translations/TranslationUtil.java
  translationproviders/src/main/java/org/fao/geonet/translations/googletranslate/GoogleTranslateClient.java
  translationproviders/src/main/java/org/fao/geonet/translations/googletranslate/GoogleTranslateClientException.java
  translationproviders/src/main/java/org/fao/geonet/translations/googletranslate/GoogleTranslateService.java
  translationproviders/src/main/java/org/fao/geonet/translations/libretranslate/LibreTranslateClient.java
  translationproviders/src/main/java/org/fao/geonet/translations/libretranslate/LibreTranslateClientException.java
  translationproviders/src/main/java/org/fao/geonet/translations/libretranslate/LibreTranslateErrorResponse.java
  translationproviders/src/main/java/org/fao/geonet/translations/libretranslate/LibreTranslateResponse.java
  translationproviders/src/main/java/org/fao/geonet/translations/libretranslate/LibreTranslateService.java
  translationproviders/src/main/resources/config-spring-geonetwork.xml
  web-ui/src/main/resources/catalog/components/admin/harvester/HarvesterDirective.js
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/translate.html
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/components/utility/UtilityService.js
  web-ui/src/main/resources/catalog/components/utility/partials/batchedit-example-selector.html
  web-ui/src/main/resources/catalog/components/utility/partials/dataselector.html
  web-ui/src/main/resources/catalog/js/admin/HarvestController.js
  web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/simpleurl.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/simpleurl.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.js
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
  web/pom.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v445/migrate-default.sql
  web/src/main/webapp/xsl/xml/harvesting/common.xsl
Labels: schema plugin change, backport 4.2.x, changelog

#8134 Transfer ownership / fix translation key for Save button
  web-ui/src/main/resources/catalog/components/metadataactions/partials/transferownership.html
Labels: backport 4.2.x

#8125 Metadata workflow API / Update security exceptions to use translations
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport 4.2.x

#8118 Editor / Keywords / Add option to configure keyword encoding for a view.
  schemas/config-editor.xsd
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields-keywords.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
  schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
  web/src/main/webapp/xslt/common/base-variables-metadata-editor.xsl
Labels: schema plugin change

#8099 Fix issues with category icons in search results list view
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/views/default/less/gn_card_default.less
  web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
Labels: bug, backport 4.2.x

#8147 [Backport 4.2.x] Delete draft resource at the end of draft util transaction.
  core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
  core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
  core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
  core/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
  core/src/main/java/org/fao/geonet/api/records/attachments/ResourceLoggerStore.java
  core/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
  core/src/main/java/org/fao/geonet/api/records/attachments/Store.java
  listeners/src/main/java/org/fao/geonet/listener/metadata/draft/DraftUtilities.java
Labels: bug

#8146 Map / Feature table / Missing translation
  web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesTable.js
Labels: backport 4.2.x

#8148 [Backport 4.2.x] Map / Feature table / Missing translation
  web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesTable.js
Labels: bug

#8049 Editor / Remove wrong ERROR log message on multilingual records
  services/src/main/java/org/fao/geonet/api/records/editing/AjaxEditUtils.java
Labels: backport 4.2.x

#7931 fix #geonetwork/core-geonetwork/issues/7930
  web/src/main/webResources/WEB-INF/config-db/jdbc.properties
  web/src/main/webResources/WEB-INF/config-db/oracle.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3103/migrate-oracle.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/migrate-oracle.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v400/migrate-oracle.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v402/migrate-oracle.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v406/migrate-oracle.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v407/migrate-oracle.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v425/migrate-db-oracle.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v441/migrate-oracle.sql
Labels: backport 4.2.x

#8122 Improve tooltips for facet filter items
  services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
  web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
  web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-cards.html
  web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
  web-ui/src/main/resources/catalog/components/utility/UtilityService.js
  web-ui/src/main/resources/catalog/js/CatController.js
Labels: api change, backport 4.2.x

#7313 Analytics services integration
  core/src/main/java/org/fao/geonet/analytics/WebAnalyticsConfiguration.java
  core/src/main/java/org/fao/geonet/util/XslUtil.java
  core/src/test/resources/core-repository-test-context.xml
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
  web-ui/src/main/resources/catalog/components/utility/UtilityService.js
  web-ui/src/main/resources/catalog/views/default/module.js
  web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
  web/src/main/webResources/WEB-INF/config.properties
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
  web/src/main/webapp/xslt/base-layout.xsl
  web/src/main/webapp/xslt/common/render-html.xsl
Labels: changelog

#8149 Fix issue with Map Attribution not being toggled correctly in data preview.
  web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
Labels: bug, backport 4.2.x

#8165 [Backport 4.2.x] Fix issue with Map Attribution not being toggled correctly in data preview.
  web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
Labels: bug

#8162 Record view / display WMS resources button label to open the link when the map viewer is not enabled
  web-ui/src/main/resources/catalog/components/metadataactions/partials/recordLinkButton.html
Labels: backport 4.2.x

#8163 Record view / don't display the add to map button for WFS resources when the map viewer is disabled.
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
  web-ui/src/main/resources/catalog/views/default/module.js
Labels: backport 4.2.x

#8175 Map viewer / Add layer with styles from a metadata doesn't show the styles selector
  web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
Labels: backport 4.2.x

#8170 [4.2.x] Documentation / Release notes 4.2.10
  docs/changes/changes4.2.10-0.txt
  docs/changes/changes4.2.6-0.txt
  docs/changes/changes4.2.7-0.txt
  docs/manual/docs/overview/change-log/version-4.2.1.md
  docs/manual/docs/overview/change-log/version-4.2.10.md
  docs/manual/docs/overview/change-log/version-4.2.2.md
  docs/manual/docs/overview/change-log/version-4.2.3.md
  docs/manual/docs/overview/change-log/version-4.2.4.md
  docs/manual/docs/overview/change-log/version-4.2.5.md
  docs/manual/docs/overview/change-log/version-4.2.6.md
  docs/manual/docs/overview/change-log/version-4.2.7.md
  docs/manual/docs/overview/change-log/version-4.2.8.md
  docs/manual/docs/overview/change-log/version-4.2.9.md
  docs/manual/mkdocs.yml
Labels: Documentation

#8191 Metadata extents API - fix service for metadata with working copy
  services/src/main/java/org/fao/geonet/api/records/extent/MetadataExtentApi.java
  services/src/main/java/org/fao/geonet/api/regions/metadata/MetadataRegionSearchRequest.java
Labels: bug, api change, backport 4.2.x

#8176 Register user / allow to select the group where the user wants to register
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  docs/manual/docs/administrator-guide/managing-users-and-groups/img/selfregistration-form.png
  docs/manual/docs/administrator-guide/managing-users-and-groups/user-self-registration.md
  services/pom.xml
  services/src/main/java/org/fao/geonet/api/users/RegisterApi.java
  services/src/main/java/org/fao/geonet/api/users/model/UserRegisterDto.java
  services/src/test/java/org/fao/geonet/api/users/RegisterApiTest.java
  web-ui/src/main/resources/catalog/js/LoginController.js
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/templates/new-account.html
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport 4.2.x, changelog

#8198 Cleaning / Remove transifex converting tools
  transifex/convertFromTransifex.sh
  transifex/convertToTransifex.sh
  transifex/translation_converter.exe
Labels: backport 4.2.x

#7938 docs: fix image links in change-log(version-3.8.0.md and 4.0.0-alpha.1
  docs/manual/docs/overview/change-log/version-3.8.0.md
  docs/manual/docs/overview/change-log/version-4.0.0-alpha.1.md
Labels: backport 4.2.x

#8186 Register user / allow to configured allowed email domains
  core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  docs/manual/docs/administrator-guide/configuring-the-catalog/system-configuration.md
  services/src/main/java/org/fao/geonet/api/users/RegisterApi.java
  services/src/main/java/org/fao/geonet/api/users/validation/UserRegisterDtoValidator.java
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v446/migrate-default.sql
Labels: backport 4.2.x, changelog

#8172 Update SECURITY.md
  SECURITY.md
Labels: backport 4.2.x

#7769 Fix user application feedback
  docs/manual/docs/administrator-guide/configuring-the-catalog/img/application-feedback-link.png
  docs/manual/docs/administrator-guide/configuring-the-catalog/img/application-feedback.png
  docs/manual/docs/administrator-guide/configuring-the-catalog/system-configuration.md
  services/src/main/java/org/fao/geonet/api/site/SiteApi.java
  web-ui/src/main/resources/catalog/components/contactus/ContactUsDirective.js
  web-ui/src/main/resources/catalog/components/contactus/partials/contactusform.html
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/js/ContactUsController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/views/default/less/gn_contact_us_default.less
  web-ui/src/main/resources/catalog/views/default/templates/footer.html
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
  web/src/main/webapp/xslt/common/base-variables.xsl
Labels: backport 4.2.x

#7265 Fix presence of duplicated or missing geonet elements after partial metadata updates
  core/src/main/java/org/fao/geonet/kernel/EditLib.java
  services/src/main/java/org/fao/geonet/api/records/editing/AjaxEditUtils.java
Labels: backport 4.2.x

#8205 [BP] Bump actions/setup-java from 4.1.0 to 4.2.1
  .github/workflows/linux.yml
Labels: github_actions

#8206 [BP] Bump actions/setup-java from 4.1.0 to 4.2.1
  .github/workflows/codeql-analysis.yml
  .github/workflows/linux.yml
  .github/workflows/mvn-dep-tree.yml
  .github/workflows/sonarcloud.yml
Labels: github_actions

#8154 Add support for multilingual thesaurus titles in the index
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
  web-ui/src/main/resources/catalog/components/search/mdview/partials/keywordBadges.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
  web/src/main/webapp/xslt/common/index-utils.xsl
Labels: bug, backport 4.2.x

#8044 Multilingual Emails
  core/src/main/java/org/fao/geonet/kernel/WatchListNotifier.java
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
  core/src/main/java/org/fao/geonet/kernel/setting/SettingManager.java
  core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
  core/src/main/java/org/fao/geonet/languages/FeedbackLanguages.java
  core/src/main/java/org/fao/geonet/util/LocalizedEmail.java
  core/src/main/java/org/fao/geonet/util/LocalizedEmailComponent.java
  core/src/main/java/org/fao/geonet/util/LocalizedEmailParameter.java
  core/src/main/resources/config-spring-geonetwork.xml
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
  services/src/main/java/org/fao/geonet/api/tools/mail/MailApi.java
  services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
  services/src/main/java/org/fao/geonet/api/users/PasswordApi.java
  services/src/main/java/org/fao/geonet/api/users/RegisterApi.java
  services/src/main/java/org/fao/geonet/util/MetadataPublicationMailNotifier.java
  web-ui/src/main/resources/catalog/components/userfeedback/partials/mdFeedback.html
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v445/migrate-default.sql
  workers/camelPeriodicProducer/src/test/resources/domain-repository-test-context.xml
Labels: enhancement, backport 4.2.x

#8210 [Backport 4.2.x] Multilingual Emails (#8044)
  core/src/main/java/org/fao/geonet/kernel/WatchListNotifier.java
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
  core/src/main/java/org/fao/geonet/kernel/setting/SettingManager.java
  core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
  core/src/main/java/org/fao/geonet/languages/FeedbackLanguages.java
  core/src/main/java/org/fao/geonet/util/LocalizedEmail.java
  core/src/main/java/org/fao/geonet/util/LocalizedEmailComponent.java
  core/src/main/java/org/fao/geonet/util/LocalizedEmailParameter.java
  core/src/main/resources/config-spring-geonetwork.xml
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
  services/src/main/java/org/fao/geonet/api/tools/mail/MailApi.java
  services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
  services/src/main/java/org/fao/geonet/api/users/PasswordApi.java
  services/src/main/java/org/fao/geonet/api/users/RegisterApi.java
  services/src/main/java/org/fao/geonet/util/MetadataPublicationMailNotifier.java
  web-ui/src/main/resources/catalog/components/userfeedback/partials/mdFeedback.html
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v4211/migrate-default.sql
  workers/camelPeriodicProducer/src/test/resources/domain-repository-test-context.xml
Labels: enhancement

#8152 Fix canViewRecord function so that it returned the workflow record.
  services/src/main/java/org/fao/geonet/api/ApiUtils.java
Labels: bug, backport 4.2.x

#8213 [Backport 4.2.x] Fix canViewRecord function so that it returned the workflow record.
  services/src/main/java/org/fao/geonet/api/ApiUtils.java
Labels: bug

#8209 Double translation can lead to infinite stack
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/extras.html
  web-ui/src/main/resources/catalog/components/metadataactions/partials/associatedResourcesContainer.html
  web-ui/src/main/resources/catalog/components/metadataactions/partials/distributionResourcesContainer.html
  web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
Labels: backport 4.2.x

#8190 [Backport 4.2.x] Support for translation providers in harvesters
  core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/BaseAligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractParams.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
  pom.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/translate.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/suggest.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/translate.xsl
  services/pom.xml
  services/src/main/java/org/fao/geonet/api/translationproviders/TranslationProvidersApi.java
  translationproviders/pom.xml
  translationproviders/src/main/java/org/fao/geonet/translations/ITranslationService.java
  translationproviders/src/main/java/org/fao/geonet/translations/TranslationFactory.java
  translationproviders/src/main/java/org/fao/geonet/translations/TranslationUtil.java
  translationproviders/src/main/java/org/fao/geonet/translations/googletranslate/GoogleTranslateClient.java
  translationproviders/src/main/java/org/fao/geonet/translations/googletranslate/GoogleTranslateClientException.java
  translationproviders/src/main/java/org/fao/geonet/translations/googletranslate/GoogleTranslateService.java
  translationproviders/src/main/java/org/fao/geonet/translations/libretranslate/LibreTranslateClient.java
  translationproviders/src/main/java/org/fao/geonet/translations/libretranslate/LibreTranslateClientException.java
  translationproviders/src/main/java/org/fao/geonet/translations/libretranslate/LibreTranslateErrorResponse.java
  translationproviders/src/main/java/org/fao/geonet/translations/libretranslate/LibreTranslateResponse.java
  translationproviders/src/main/java/org/fao/geonet/translations/libretranslate/LibreTranslateService.java
  translationproviders/src/main/resources/config-spring-geonetwork.xml
  web-ui/src/main/resources/catalog/components/admin/harvester/HarvesterDirective.js
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/translate.html
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/components/utility/UtilityService.js
  web-ui/src/main/resources/catalog/components/utility/partials/batchedit-example-selector.html
  web-ui/src/main/resources/catalog/components/utility/partials/dataselector.html
  web-ui/src/main/resources/catalog/js/admin/HarvestController.js
  web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/simpleurl.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/simpleurl.js
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.js
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
  web/pom.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v4211/migrate-default.sql
  web/src/main/webapp/xsl/xml/harvesting/common.xsl
Labels: schema plugin change, changelog

#8178 Add info logs to make transaction of working copy merge more traceable
  core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
  datastorages/cmis/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
  datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
  datastorages/s3/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
  listeners/src/main/java/org/fao/geonet/listener/metadata/draft/DraftUtilities.java
Labels: backport 4.2.x

#7943 GeoNetwork 4.2.x minor versions library updates
  pom.xml
Labels: dependencies

#8230 Editor / Bounding polygon not saved
  web-ui/src/main/resources/catalog/components/edit/bounding/partials/boundingpolygon.html
Labels: backport 4.2.x
