Repository geonetwork/core-geonetwork, pull requests merged in 2024-02, with the labels that each got.

#7667 Fix pdf link issue
  web/src/main/webapp/xslt/skin/default/skin.xsl
Labels: bug, backport 3.12.x, backport 4.2.x

#7607 Metadata editor / Fix javascript error when editing a metadata
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Labels: backport 4.2.x

#7615 Fix javascript error accessing the metadata detail page in gnMetadataSocialLink directive
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
Labels: backport 4.2.x, failed backport

#7678 Add configuration to filter out Elasticsearch fields when download or dynamic privileges are not set
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema-ident.xml
  schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml
  services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
Labels: backport 4.2.x, changelog

#7683 Editor / Fix add element attribute
  web/src/main/webapp/xslt/ui-metadata/edit/edit-embedded.xsl
Labels: backport 4.2.x

#7611 Update Springdoc so that it supports Map objects in the request parameters.
  services/src/main/java/org/fao/geonet/api/OpenApiConfig.java
Labels: backport 4.2.x

#7670 Fix springdoc so that enums names are used instead of toString
  services/src/main/java/org/fao/geonet/api/OpenApiController.java
Labels: bug, api change, backport 4.2.x

#7617 Fix spring doc for attachment and keyword to better identify files resources being returned.
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
  services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
Labels: backport 4.2.x

#7692 Remove empty class SourcesLib and deprecated/unused methods in ResourceLib / Sonarlint improvements
  core/src/main/java/org/fao/geonet/lib/DbLib.java
  core/src/main/java/org/fao/geonet/lib/ElementLib.java
  core/src/main/java/org/fao/geonet/lib/Lib.java
  core/src/main/java/org/fao/geonet/lib/NetLib.java
  core/src/main/java/org/fao/geonet/lib/ResourceLib.java
  core/src/main/java/org/fao/geonet/lib/SourcesLib.java
  core/src/main/java/org/fao/geonet/lib/TextLib.java
Labels: backport 4.2.x

#7696 Addressing docs translation glitch #7687- fixes adding-static-pages and configuring-search-fields
  docs/manual/docs/customizing-application/adding-static-pages.md
  docs/manual/docs/customizing-application/configuring-search-fields.md
  docs/manual/docs/customizing-application/editor-ui/creating-custom-editor.md
Labels: backport 4.2.x

#7686 Add a role and feature matrix to the GeoNetwork documentation
  docs/manual/docs/administrator-guide/managing-users-and-groups/index.md
Labels: backport 4.2.x, Documentation

#7706 CSW / Enable preemptive for csw requests with credentials (#5497)
  csw-server/src/main/java/org/fao/geonet/csw/common/requests/CatalogRequest.java
Labels: backport 4.2.x

#7724 [Backport 4.2.x] Bump org.json:json from 20140107 to 20240205
  common/pom.xml
  pom.xml
  web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
Labels: dependencies, java

#7723 [Backport 3.12.x] Bump org.json:json from 20140107 to 20240205
  common/pom.xml
  pom.xml
Labels: dependencies, java

#7725 Remove unused jslint-maven-plugin
  pom.xml
  web-ui/pom.xml
Labels: dependencies, backport 3.12.x, backport 4.2.x

#7714 Use the generated metadata UUID for resource links when importing metadata with the option 'Generate UUID'
  core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
Labels: backport 3.12.x, backport 4.2.x

#7715 Map viewer / Remove Stamen background layers - no longer available
  docs/manual/docs/administrator-guide/configuring-the-catalog/user-interface-configuration.md
  docs/manual/docs/help/map/index.md
  docs/manual/docs/tutorials/customui/search/defaultview.md
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
  web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
  web-ui/src/main/resources/catalog/locales/ca-admin.json
  web-ui/src/main/resources/catalog/locales/cs-admin.json
  web-ui/src/main/resources/catalog/locales/da-admin.json
  web-ui/src/main/resources/catalog/locales/de-admin.json
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/locales/es-admin.json
  web-ui/src/main/resources/catalog/locales/fi-admin.json
  web-ui/src/main/resources/catalog/locales/fr-admin.json
  web-ui/src/main/resources/catalog/locales/is-admin.json
  web-ui/src/main/resources/catalog/locales/it-admin.json
  web-ui/src/main/resources/catalog/locales/ko-admin.json
  web-ui/src/main/resources/catalog/locales/nl-admin.json
  web-ui/src/main/resources/catalog/locales/pt-admin.json
  web-ui/src/main/resources/catalog/locales/ru-admin.json
  web-ui/src/main/resources/catalog/locales/sk-admin.json
  web-ui/src/main/resources/catalog/locales/sv-admin.json
  web-ui/src/main/resources/catalog/locales/zh-admin.json
  web/src/main/webapp/WEB-INF/data/data/resources/map/config-viewer.xml
Labels: backport 3.12.x, backport 4.2.x

#7728 Separate docs for _search and _msearch
  services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
Labels: backport 4.2.x

#7722 Documentation / Elasticsearch query endpoint - query samples
  docs/manual/docs/api/img/swagger-search-endpoint.png
  docs/manual/docs/api/search.md
Labels: backport 4.2.x, Documentation

#7697 Index / Add danish language.
  docs/manual/docs/customizing-application/configuring-search-fields.md
  web/src/main/webResources/WEB-INF/data/config/index/records.json
Labels: index structure change

#7674 Thesaurus / Add support for thesaurus described using OWL format
  services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
  services/src/test/java/org/fao/geonet/api/registries/vocabularies/KeywordsApiTest.java
  services/src/test/resources/mobility-theme.owl
  web/src/main/webapp/xslt/services/thesaurus/owl-to-skos.xsl
Labels: api change

#7736 [Backport 4.2.x] Index / Add danish language.
  docs/manual/docs/customizing-application/configuring-search-fields.md
  web/src/main/webResources/WEB-INF/data/config/index/records.json
Labels: index structure change

#7679 Create a metadata / Add dynamic and download privileges to the users in the same group
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java
Labels: backport 4.2.x, changelog

#7742 Reports / Fix extract user groups for non-admin users
  web-ui/src/main/resources/catalog/js/admin/ReportController.js
Labels: backport 4.2.x

#7748 [Backport 3.12.x] Create a metadata / Add dynamic and download privileges to the users in the same group
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java
Labels: changelog

#7759 Remove handlebars.js v2.0.0
  web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
  web-ui/src/main/resources/catalog/components/timezoneselector/TimeZoneSelectorDirective.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/typeahead.js/handlebars-v2.0.0.js
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
Labels: dependencies, backport 3.12.x, backport 4.2.x

#7762 [Backport 3.12.x] Remove handlebars.js v2.0.0
  web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
  web-ui/src/main/resources/catalog/components/timezoneselector/TimeZoneSelectorDirective.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/typeahead.js/handlebars-v2.0.0.js
  web-ui/src/main/resources/catalog/views/api/index_debug.html
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
Labels: dependencies

#7761 Fix ISO19139 German labels
  schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml
Labels: backport 4.2.x

#7764 Fix HTML syntax in users.html
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: bug, backport 3.12.x, backport 4.2.x

#7773 [Backport 4.2.x] Fix HTML syntax in users.html
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Labels: bug

#7587 Fix duplicate GET operation on /{portal}/api/sources and missing /subportal endpoint
  services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
Labels: bug, api change, backport 4.2.x

#7627 Fix missing MetadataStatusResponse and MetadataWorkflowStatusResponse in open api spec
  services/src/main/java/org/fao/geonet/api/records/model/MetadataStatusDto.java
  services/src/main/java/org/fao/geonet/api/records/model/MetadataStatusResponse.java
  services/src/main/java/org/fao/geonet/api/records/model/MetadataWorkflowStatusResponse.java
Labels: bug, backport 4.2.x

#7572 Removed @RequestHeader for "Accept" headers as it is not supported by openAPI specification
  services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
  services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
  web-ui/src/main/resources/catalog/views/default/templates/recordView/summary.html
Labels: backport 4.2.x

#7778 Additional ISO19139 German translations
  schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/ger/strings.xml
Labels: backport 4.2.x

#7789 Fix wrong manual links
  web/src/main/webapp/WEB-INF/data/data/resources/config/manual.json
Labels: backport 4.2.x

#7793 [Backport 4.2.x] Fix wrong manual links
  web/src/main/webapp/WEB-INF/data/data/resources/config/manual.json
Labels: bug

#7795 Record view / Don't add the associated resources in the metadata static page, this page doesn't include JS libs
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
Labels: backport 4.2.x

#7782 System setting for documentation url
  web-ui/src/main/resources/catalog/components/common/needhelp/NeedHelpDirective.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v443/migrate-default.sql
Labels: backport 4.2.x

#7799 Docs custom editor minor typo fixes
  docs/manual/docs/customizing-application/editor-ui/creating-custom-editor.md
Labels: backport 4.2.x

#7531 Translated the index warnings / errors.
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  core/src/test/java/org/fao/geonet/kernel/search/EsSearchManagerTest.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
  web-ui/src/main/resources/catalog/js/admin/DashboardStatusController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/templates/admin/dashboard/status.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView/footer.html
  web/src/main/webResources/WEB-INF/data/config/index/records.json
  web/src/main/webapp/xslt/common/index-utils.xsl
Labels: schema plugin change

#7816 [Backport 3.12.x] Bump actions/setup-java from 4.0.0 to 4.1.0
  .github/workflows/linux.yml
Labels: github_actions
