Repository geonetwork/core-geonetwork, pull requests merged in 2024-07, with the labels that each got.

#8232 Fix wrong HTML self closing tags
  web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-temporalrange.html
  web-ui/src/main/resources/catalog/components/ng-skos/templates/skos-concept-thesaurus.html
  web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
  web-ui/src/main/resources/catalog/templates/formatter-viewer.html
  web-ui/src/main/resources/catalog/views/default/directives/partials/attributetable.html
Labels: backport 4.2.x

#8229 Standard / ISO19139 / Formatter / Do not display extent if none available
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Labels: backport 4.2.x

#8212 broadcasting error when delete record
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
  web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
Labels: bug, backport 4.2.x

#8249 Fix infinite "Please wait" message on error
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
Labels: bug, backport 4.2.x

#8250 [Backport 4.2.x] Fix infinite "Please wait" message on error
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
Labels: bug

#8244 Editor / Configuration / Improve deletion in forEach section
  schemas/config-editor.xsd
  web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
Labels: backport 4.2.x

#8223 Standard / ISO19115-3 / Formatter / Fix namespace declaration
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/iso19139/view.xsl
Labels: backport 4.2.x

#8224 Standard / ISO19115-3 / Formatters / ISO19139 / Fix scope code
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/toISO19139.xsl
Labels: backport 4.2.x

#8265 Fix issue with working copy not being returned from getRecordAS api
  services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
Labels: bug, backport 4.2.x

#8262 Use UI language for metadata selection export to CSV / PDF.
  services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
  services/src/main/java/org/fao/geonet/guiapi/search/XsltResponseWriter.java
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
Labels: api change, backport 4.2.x, changelog

#8274 [Backport 4.2.x] Use UI language for metadata selection export to CSV/PDF
  services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
  services/src/main/java/org/fao/geonet/guiapi/search/XsltResponseWriter.java
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
Labels: api change, changelog

#8267 Zoom to map popup remains active on non-map pages.
  web-ui/src/main/resources/catalog/components/common/alert/AlertDirective.js
  web-ui/src/main/resources/catalog/components/common/map/mapService.js
  web-ui/src/main/resources/catalog/components/search/resultsview/SelectionDirective.js
  web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
  web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
  web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
  web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
  web-ui/src/main/resources/catalog/views/default/module.js
Labels: backport 4.2.x

#8285 Fix a problem with recaptcha not shown sometimes
  web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js
  web-ui/src/main/resources/catalog/components/userfeedback/GnmdFeedbackDirective.js
  web-ui/src/main/resources/catalog/js/LoginController.js
Labels: bug, backport 3.12.x, backport 4.2.x

#8286 [Backport 4.2.x] Fix a problem with recaptcha not shown sometimes
  web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js
  web-ui/src/main/resources/catalog/components/userfeedback/GnmdFeedbackDirective.js
  web-ui/src/main/resources/catalog/js/LoginController.js
Labels: bug

#8287 [Backport 3.12.x] Fix a problem with recaptcha not shown sometimes
  web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js
  web-ui/src/main/resources/catalog/components/userfeedback/GnmdFeedbackDirective.js
  web-ui/src/main/resources/catalog/js/LoginController.js
Labels: bug
