Repository geonetwork/core-geonetwork, pull requests merged in 2024-01, with the labels that each got.

#7573 Fix duplicate SpringDoc tags.
  services/src/main/java/org/fao/geonet/api/ApiParams.java
  services/src/main/java/org/fao/geonet/api/records/DoiApi.java
  services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsActionsApi.java
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/CacheApi.java
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterAdminApi.java
  services/src/main/java/org/fao/geonet/api/sld/SldApi.java
  services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java
  services/src/main/java/org/fao/geonet/api/tools/mail/MailApi.java
  services/src/main/java/org/fao/geonet/api/tools/migration/MigrationApi.java
Labels: bug, backport-4.2.x

#7575 Fix initialization of SpringDoc so that it does not use null servername and null version
  services/src/main/java/org/fao/geonet/api/OpenApiConfig.java
  services/src/main/java/org/fao/geonet/api/site/SiteApi.java
Labels: bug, backport-4.2.x

#7584 Spring doc API for index should return a structured object instead of JSONObject
  services/src/main/java/org/fao/geonet/api/records/MetadataIndexApi.java
Labels: backport-4.2.x

#7590 Add missing apiResponse for group and map api
  services/src/main/java/org/fao/geonet/api/groups/GroupsApi.java
  services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java
Labels: bug, backport-4.2.x

#7574 Update SpringDoc json/yaml generator to make the results more deterministic.
  services/src/main/java/org/fao/geonet/api/OpenApiController.java
Labels: backport-4.2.x

#7585 Spring doc API for link api should accept a structured object instead of JSONObject
  services/src/main/java/org/fao/geonet/api/links/LinksApi.java
Labels: backport-4.2.x

#7560 Metadata extents API / Make configurable to display the metadata bboxes using geodesic extents for local projections.
  core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
  services/src/main/java/org/fao/geonet/api/records/extent/MapRenderer.java
  services/src/test/java/org/fao/geonet/api/records/extent/MapRendererTest.java
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v442/migrate-default.sql
Labels: backport-4.2.x

#7569 Home page / sort topic categories and INSPIRE themes facets alphabetically
  web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
  web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-cards.html
  web-ui/src/main/resources/catalog/js/CatController.js
Labels: backport-4.2.x

#7553 Record view / Invalid timezone shift for years outside moment's 10 years range
  web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
  web-ui/src/main/resources/catalog/lib/moment-timezone-with-data-10-year-range.min.js
  web-ui/src/main/resources/catalog/lib/moment-timezone-with-data-1970-2030.min.js
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
Labels: backport-4.2.x

#7591 Fix add element attribute in the metadata editor
  web/src/main/webapp/xslt/ui-metadata/edit/edit-embedded.xsl
Labels: backport-4.2.x

#7565 INSPIRE Atom feeds / Fix link to atom search endpoint
  web/src/main/webResources/WEB-INF/urlrewrite.xml
  web/src/main/webapp/xslt/services/inspire-atom/opensearch.xsl
  web/src/main/webapp/xslt/services/inspire-atom/opensearchdescription.xsl
Labels: backport-4.2.x

#7400 Build info improvements.
  .gitignore
  services/src/main/java/org/fao/geonet/api/site/SiteInformation.java
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web/pom.xml
  web/src/main/webapp/WEB-INF/server.prop
Labels: backport-4.2.x

#7586 Fix duplicate operation id caused by use of 2 methods GET/POST method from getKeywordById api
  services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
Labels: api change, backport-4.2.x

#7376 Search results / Configure related records type depending on template.
  web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
  web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
  web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
  web-ui/src/main/resources/catalog/components/search/resultsview/ResultsviewDirective.js
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/templateswitcher.html
  web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
  web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextDirective.js
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
  web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
  web-ui/src/main/resources/catalog/js/search/SearchController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/views/default/module.js
Labels: backport-4.2.x, changelog

#7326 Configuration to restrict the hosts and ports accessible by the http proxy servlet
  pom.xml
  web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
  web/src/main/webResources/WEB-INF/web.xml
Labels: backport-4.2.x, changelog

#7597 Add missing swagger icons that were referenced in the index.html file.
  web/src/main/webapp/doc/api/favicon-16x16.png
  web/src/main/webapp/doc/api/favicon-32x32.png
Labels: bug, backport-4.2.x

#7595 Spring doc - Set API enum as ref
  services/src/main/java/org/fao/geonet/api/records/model/related/RelatedItemType.java
  services/src/main/java/org/fao/geonet/config/PublicationOption.java
Labels: backport-4.2.x

#7588 Fix issue with @ResponseStatus and @ApiResponse being out of sync.
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataProcessApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataTagApi.java
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
  services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
Labels: bug, backport-4.2.x

#7608 Update files with Prettier formatting
  web-ui/src/main/resources/catalog/components/common/openlayers/olMapDirective.js
  web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html
Labels: backport-4.2.x

#7581 Fix duplicate API endpoint /feeds
  inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomSearch.java
Labels: bug, api change, backport-4.2.x

#7580 Fix SpringDoc duplicate OperationId
  services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
  services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
  services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
  services/src/main/java/org/fao/geonet/api/site/SiteApi.java
  services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java
Labels: bug, backport-4.2.x

#7594 Add missing @ApiResponse status for successful api search response.
  services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
Labels: bug, backport-4.2.x

#7616 Cleanup consumes section from metadata insert api.
  services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Labels: backport-4.2.x

#7609 Remove default response from open api specification.
  services/src/main/java/org/fao/geonet/api/OpenApiController.java
Labels: backport-4.2.x

#7619 release module build workflow improvements / fixes
  .github/workflows/codeql-analysis.yml
  .github/workflows/linux.yml
  docs/manual/pom.xml
  pom.xml
  release/README.md
  release/build.xml
  release/pom.xml
  web/pom.xml
Labels: backport-3.12.x, backport-4.2.x

#7622 Use Java 21 for Sonarcloud plugin
  .github/workflows/sonarcloud.yml
Labels: github_actions

#7626 Record view / Display WFS downloads for WFS online resources without a name defined
  web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Labels: backport-4.2.x

#7621 Fix error on edit page: elements with non-unique id #gnRemoteRecordUrl
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/remote-record-selector.html
Labels: bug, backport-4.2.x

#7559 Fix the grid on the homepage of the documentation
  docs/manual/docs/index.fr.md
  docs/manual/docs/index.md
  docs/manual/overrides/assets/stylesheets/extra.css
  docs/manual/requirements.txt
Labels: backport-3.12.x, backport-4.2.x

#7457 unpack schema sample data into folders, produce mef files at build time
  schemas/dublin-core/pom.xml
  schemas/dublin-core/src/assembly/schema-plugin.xml
  schemas/dublin-core/src/main/plugin/dublin-core/sample-data/dublin-core.mef
  schemas/dublin-core/src/main/plugin/dublin-core/sample-data/natural_polar_ecosystems/info.xml
  schemas/dublin-core/src/main/plugin/dublin-core/sample-data/natural_polar_ecosystems/metadata.xml
  schemas/dublin-core/src/main/plugin/dublin-core/sample-data/natural_polar_ecosystems/private/.keepme
  schemas/dublin-core/src/main/plugin/dublin-core/sample-data/natural_polar_ecosystems/public/.keepme
  schemas/iso19115-3.2018/pom.xml
  schemas/iso19115-3.2018/src/assembly/schema-plugin.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/sample-data/0dbac056-cd5a-4c9c-bbec-564e47c4507c.zip
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/sample-data/service_record/info.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/sample-data/service_record/metadata.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/sample-data/service_record/metadata/.keepme
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/sample-data/service_record/private/.keepme
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/sample-data/service_record/public/.keepme
  schemas/iso19139/pom.xml
  schemas/iso19139/src/assembly/schema-plugin.xml
  schemas/iso19139/src/main/plugin/iso19139/sample-data/basins_in_africa/info.xml
  schemas/iso19139/src/main/plugin/iso19139/sample-data/basins_in_africa/metadata.xml
  schemas/iso19139/src/main/plugin/iso19139/sample-data/basins_in_africa/private/.keepme
  schemas/iso19139/src/main/plugin/iso19139/sample-data/basins_in_africa/private/basins.zip
  schemas/iso19139/src/main/plugin/iso19139/sample-data/basins_in_africa/public/.keepme
  schemas/iso19139/src/main/plugin/iso19139/sample-data/basins_in_africa/public/thumbnail.gif
  schemas/iso19139/src/main/plugin/iso19139/sample-data/basins_in_africa/public/thumbnail_s.gif
  schemas/iso19139/src/main/plugin/iso19139/sample-data/iso-19139-basins-in-africa.mef
  schemas/iso19139/src/main/plugin/iso19139/sample-data/iso-19139-physiographic.mef
  schemas/iso19139/src/main/plugin/iso19139/sample-data/locality_polygons_comprehensive.mef
  schemas/iso19139/src/main/plugin/iso19139/sample-data/locality_polygons_comprehensive/info.xml
  schemas/iso19139/src/main/plugin/iso19139/sample-data/locality_polygons_comprehensive/metadata.xml
  schemas/iso19139/src/main/plugin/iso19139/sample-data/photographic_session.mef
  schemas/iso19139/src/main/plugin/iso19139/sample-data/photographic_session/info.xml
  schemas/iso19139/src/main/plugin/iso19139/sample-data/photographic_session/metadata.xml
  schemas/iso19139/src/main/plugin/iso19139/sample-data/physiographic/info.xml
  schemas/iso19139/src/main/plugin/iso19139/sample-data/physiographic/metadata.xml
  schemas/iso19139/src/main/plugin/iso19139/sample-data/physiographic/private/phy.zip
  schemas/iso19139/src/main/plugin/iso19139/sample-data/physiographic/public/phy.gif
  schemas/iso19139/src/main/plugin/iso19139/sample-data/physiographic/public/phy_s.gif
  schemas/iso19139/src/main/plugin/iso19139/sample-data/z3950-server-sample.mef
  schemas/iso19139/src/main/plugin/iso19139/sample-data/z3950_server/info.xml
  schemas/iso19139/src/main/plugin/iso19139/sample-data/z3950_server/metadata.xml
Labels: backport 4.2.x

#7412 build release procedure updates to include docs in release tag
  .gitignore
  docs/README.md
  docs/changes/changes2.1.x.txt
  docs/changes/changes2.10.x.txt
  docs/changes/changes2.2.x.txt
  docs/changes/changes2.4.x.txt
  docs/changes/changes2.6.x.txt
  docs/changes/changes2.8.x.txt
  docs/changes/changes3.0.0-0.txt
  docs/changes/changes3.0.1-0.txt
  docs/changes/changes3.0.2-0.txt
  docs/changes/changes3.0.3-0.txt
  docs/changes/changes3.0.4-0.txt
  docs/changes/changes3.0.5-0.txt
  docs/changes/changes3.10.0-0.txt
  docs/changes/changes3.10.1-0.txt
  docs/changes/changes3.10.2-0.txt
  docs/changes/changes3.10.3-0.txt
  docs/changes/changes3.10.4-0.txt
  docs/changes/changes3.10.5-0.txt
  docs/changes/changes3.10.6-0.txt
  docs/changes/changes3.12.0-0.txt
  docs/changes/changes3.2.0-0.txt
  docs/changes/changes3.2.1-0.txt
  docs/changes/changes3.2.2-0.txt
  docs/changes/changes3.4.0-0.txt
  docs/changes/changes3.4.1-0.txt
  docs/changes/changes3.4.2-0.txt
  docs/changes/changes3.6.0-0.txt
  docs/changes/changes3.8.0-0.txt
  docs/changes/changes3.8.1-0.txt
  docs/changes/changes3.8.2-0.txt
  docs/changes/changes3.8.3-0.txt
  docs/changes/changes4.0.0-0.txt
  docs/changes/changes4.0.0-alpha.1.txt
  docs/changes/changes4.0.0-alpha.2.txt
  docs/changes/changes4.0.1-0.txt
  docs/changes/changes4.0.2-0.txt
  docs/changes/changes4.0.3-0.txt
  docs/changes/changes4.0.4-0.txt
  docs/changes/changes4.0.5-0.txt
  docs/changes/changes4.0.6-0.txt
  docs/changes/changes4.2.0-0.txt
  docs/changes/changes4.2.1-0.txt
  docs/changes/changes4.2.2-0.txt
  docs/changes/changes4.2.3-0.txt
  docs/changes/changes4.2.4-0.txt
  docs/changes/changes4.2.5-0.txt
  docs/changes/changes4.4.0-0.txt
  docs/changes/changes4.4.1-0.txt
  docs/manual/docs/contributing/doing-a-release.md
  pom.xml
Labels: backport 4.2.x

#7630 Move Direction as an reference object in the open api specification.
  services/src/main/java/org/fao/geonet/api/records/model/Direction.java
Labels: backport 4.2.x

#7640 [Backport 4.2.x] Move Direction as a reference object in the open api specification.
  services/src/main/java/org/fao/geonet/api/records/model/Direction.java
Labels: enhancement

#7642 [Backport 4.2.x] Miscellaneous code cleanup with MetadataStatus and RelatedResponse
  domain/src/main/java/org/fao/geonet/domain/MetadataStatus.java
  services/src/main/java/org/fao/geonet/api/records/model/related/RelatedResponse.java
Labels: enhancement

#7612 Remove unused Jeeves classes
  core/src/main/java/jeeves/guiservices/profiles/Get.java
  core/src/main/java/jeeves/services/Ping.java
  core/src/main/java/jeeves/services/RegExpReplace.java
  core/src/main/java/jeeves/services/db/Select.java
  core/src/main/java/jeeves/services/http/Get.java
  core/src/main/java/jeeves/services/session/Put.java
  web/src/main/webapp/WEB-INF/config.xml
Labels: backport 4.2.x

#7644 Upgrade guidance for geonetwork 3 users
  docs/manual/docs/api/csw.md
  docs/manual/docs/api/img/admin-console-api.png
  docs/manual/docs/api/img/geonetwork-api-document.png
  docs/manual/docs/api/img/geonetwork-api-html.png
  docs/manual/docs/api/img/geonetwork-api-test.png
  docs/manual/docs/api/img/opensearch-in-browser.png
  docs/manual/docs/api/img/opensearch.png
  docs/manual/docs/api/index.md
  docs/manual/docs/api/inspire_atom.md
  docs/manual/docs/api/oai-pmh.md
  docs/manual/docs/api/opensearch.md
  docs/manual/docs/api/q-search.md
  docs/manual/docs/api/rdf-dcat.md
  docs/manual/docs/api/search.md
  docs/manual/docs/api/the-geonetwork-api.md
  docs/manual/docs/api/z39-50.md
  docs/manual/docs/help/search/index.md
  docs/manual/docs/install-guide/index.md
  docs/manual/docs/install-guide/installing-index.md
  docs/manual/docs/maintainer-guide/updating/index.md
  docs/manual/docs/overview/change-log/version-4.0.0.md
  docs/manual/docs/user-guide/quick-start/index.md
  docs/manual/help.yml
  docs/manual/mkdocs.yml
  docs/manual/pom.xml
Labels: backport 4.2.x

#7641 Formatter / Withheld element not always hidden.
  core/src/main/java/org/fao/geonet/kernel/XmlSerializer.java
  core/src/test/java/org/fao/geonet/kernel/XmlSerializerIntegrationTest.java
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
  services/src/main/java/org/fao/geonet/guiservices/util/Env.java
  services/src/test/java/org/fao/geonet/api/records/formatters/AbstractFormatterTest.java
  services/src/test/java/org/fao/geonet/api/records/formatters/FormatterApiIntegrationTest.java
  web/src/main/java/org/fao/geonet/Geonetwork.java
Labels: api change

#7662 [Backport 4.2.x] Bump github/codeql-action from 2 to 3
  .github/workflows/codeql-analysis.yml
Labels: dependencies, github_actions

#7663 Docs / Update copyright year
  docs/manual/mkdocs.yml
Labels: backport 3.12.x, backport 4.2.x, Documentation

#7664 [Backport 3.12.x] Docs / Update copyright year
  docs/manual/mkdocs.yml
Labels: Documentation

#7665 [Backport 4.2.x] Docs / Update copyright year
  docs/manual/mkdocs.yml
Labels: Documentation

#7671 Fix MIME-types on attachments as some were incorrect
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: bug, backport 3.12.x, backport 4.2.x

#7468 Editor / Distribution improvements
  schemas/dublin-core/src/main/plugin/dublin-core/layout/config-editor.xml
  schemas/dublin-core/src/main/plugin/dublin-core/process/thumbnail-add.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/config/associated-panel/default.json
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/add-info-from-wms.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/create-featurecatalogue-from-wfs.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
  schemas/iso19139/src/main/plugin/iso19139/process/add-info-from-wms.xsl
  web-ui/src/main/resources/catalog/components/doi/DoiService.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/remote-record-selector.html
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/urlValidator.html
  web-ui/src/main/resources/catalog/components/edit/suggestion/SuggestionDirective.js
  web-ui/src/main/resources/catalog/components/edit/suggestion/partials/list.html
  web-ui/src/main/resources/catalog/components/edit/suggestion/partials/suggestbutton.html
  web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
  web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
  web-ui/src/main/resources/catalog/components/metadataactions/partials/distributionResourcesContainer.html
  web-ui/src/main/resources/catalog/components/metadataactions/partials/distributionResourcesPanel.html
  web-ui/src/main/resources/catalog/components/metadataactions/partials/relatedDistribution.html
  web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/js/edit/EditorController.js
  web-ui/src/main/resources/catalog/locales/en-core.json
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/locales/en-v4.json
  web-ui/src/main/resources/catalog/style/gn.less
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
  web-ui/src/main/resources/catalog/views/default/templates/recordView/downloads.html
Labels: schema plugin change, changelog

#7675 [Backport 4.2.x] Fix MIME-types on attachments as some were incorrect
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: bug

#7676 [Backport 3.12.x] Fix MIME-types on attachments as some were incorrect
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: bug
