Repository geonetwork/core-geonetwork, pull requests merged in 2024-08, with the labels that each got.

#8281 Standard / ISO19139 / Fix removal of online source when multiple transfer options block are used.
  schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl
Labels: bug, backport 4.2.x

#8297 [Backport 4.2.x] Standard / ISO19139 / Fix removal of online source when multiple transfer options block are used.
  schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
  schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl
Labels: bug

#8292 Update batch PDF export to skip working copies
  services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
Labels: bug, backport 4.2.x

#8293 Index / Add maintenance details.
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  web-ui/src/main/resources/catalog/locales/en-v4.json
  web-ui/src/main/resources/catalog/views/default/templates/recordView/maintenance.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
Labels: index structure change

#8298 Standard / ISO19139 / i18n / Missing french translation
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/labels.xml
Labels: backport 4.2.x

#8303 harvesting CSW: changed loglevel for invalid metadata to info
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
Labels: backport 4.2.x

#8312 Modify record not found message to hide sign in link if already signed in
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/views/default/templates/recordView/recordView.html
Labels: bug, backport 4.2.x

#8315 [Backport 4.2.x] Modify record not found message to hide sign in link if already signed in
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/views/default/templates/recordView/recordView.html
Labels: bug

#8317 Repository Citation.cff metadata for DOI registration with Zenodo
  CITATION.cff
Labels: enhancement, backport 4.2.x
