Repository geonetwork/core-geonetwork, pull requests merged in 2024-10, with the labels that each got.

#8098 Support multiple DOI servers
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  docs/manual/docs/user-guide/associating-resources/doi.md
  docs/manual/docs/user-guide/associating-resources/img/doi-create-server.png
  doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
  domain/src/main/java/org/fao/geonet/domain/DoiServer.java
  domain/src/main/java/org/fao/geonet/entitylistener/DoiServerEntityListenerManager.java
  domain/src/main/java/org/fao/geonet/repository/DoiServerRepository.java
  domain/src/test/java/org/fao/geonet/repository/DoiServerRepositoryTest.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/datacite/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/datacite/view.xsl
  services/src/main/java/org/fao/geonet/api/doiservers/DoiServersApi.java
  services/src/main/java/org/fao/geonet/api/doiservers/model/AnonymousDoiServer.java
  services/src/main/java/org/fao/geonet/api/doiservers/model/DoiServerDto.java
  services/src/main/java/org/fao/geonet/api/records/DoiApi.java
  services/src/main/java/org/fao/geonet/api/site/SiteApi.java
  services/src/test/java/org/fao/geonet/api/doiservers/DoiServersApiTest.java
  web-ui/src/main/resources/catalog/components/doi/DoiDirective.js
  web-ui/src/main/resources/catalog/components/doi/DoiService.js
  web-ui/src/main/resources/catalog/components/doi/partials/doiwidget.html
  web-ui/src/main/resources/catalog/components/history/partials/historyStep.html
  web-ui/src/main/resources/catalog/components/metadataactions/partials/relatedDistribution.html
  web-ui/src/main/resources/catalog/js/admin/DoiServerController.js
  web-ui/src/main/resources/catalog/js/admin/SettingsController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/style/gn_admin.less
  web-ui/src/main/resources/catalog/templates/admin/settings/doiservers.html
  web-ui/src/main/resources/catalog/views/default/directives/directive.js
  web/src/main/webResources/WEB-INF/config-db/database_migration.xml
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
  web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v445/DoiServerDatabaseMigration.java
Labels: enhancement, api change, changelog

#8133 Don't capitalize the labels for the facet filter values
  web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
  web-ui/src/main/resources/catalog/components/search/mdview/partials/keywordBadges.html
Labels: backport 4.2.x

#8395 Metadata editor / validation report improvements
  web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
  web-ui/src/main/resources/catalog/locales/en-editor.json
  web-ui/src/main/resources/catalog/style/gn_editor.less
Labels: backport 4.2.x

#8400 Metadata editor / Add required indicator to keyword selector and fix the required indicator for the field duration directive
  web-ui/src/main/resources/catalog/components/edit/fieldduration/partials/fieldduration.html
  web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
  web-ui/src/main/resources/catalog/components/thesaurus/partials/keywordselector.html
Labels: backport 4.2.x

#8398 Fixed spurious whitespace for gn-comma-list
  web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
  web-ui/src/main/resources/catalog/views/default/templates/recordView/metadata.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView/spatial.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
Labels: backport 4.2.x

#8412 Metadata indexing / ISO19139 / ISO19115-3.2018 / Escape graphic overview file name for JSON
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
Labels: backport 4.2.x

#8156 Harvester / ISO19115-3 / Better support missing metadata date info
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/extract-date-modified.xsl
Labels: backport 4.2.x

#8357 Add support for external management named properties in JCloud
  core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
  datastorages/cmis/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
  datastorages/cmis/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
  datastorages/cmis/src/main/resources/config-store/config-cmis-overrides.properties
  datastorages/cmis/src/main/resources/config-store/config-cmis.xml
  datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
  datastorages/jcloud/src/main/java/org/fao/geonet/resources/JCloudConfiguration.java
  datastorages/jcloud/src/main/java/org/fao/geonet/resources/JCloudMetadataNameValidator.java
  datastorages/jcloud/src/main/resources/config-store/config-jcloud-overrides.properties
  datastorages/jcloud/src/main/resources/config-store/config-jcloud.xml
  pom.xml
Labels: backport 4.2.x

#8217 CSW / Fix parsing date values for filters
  csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2Es.java
  csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2EsTest.java
  csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/EsJsonHelper.java
Labels: bug, backport 4.2.x

#8140 Standard / ISO19115-3 / Only search for associated record with UUID
  schemas/iso19115-3.2018/src/main/java/org/fao/geonet/schema/iso19115_3_2018/ISO19115_3_2018SchemaPlugin.java
Labels: backport 4.2.x

#8408 Update list of metadata import restrictions so that it will work even it there are spaces in the list.
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
  web-ui/src/main/resources/catalog/locales/en-admin.json
Labels: backport 4.2.x

#8407 Formatter / Datacite / Default resource type
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/datacite/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/datacite/view.xsl
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport 4.2.x

#8243 WebDav harvester / Add support for XSLT filter process
  docs/manual/docs/user-guide/harvesting/harvesting-csw.md
  docs/manual/docs/user-guide/harvesting/harvesting-filesystem.md
  docs/manual/docs/user-guide/harvesting/harvesting-geonetwork-2.md
  docs/manual/docs/user-guide/harvesting/harvesting-geonetwork.md
  docs/manual/docs/user-guide/harvesting/harvesting-geoportal.md
  docs/manual/docs/user-guide/harvesting/harvesting-oaipmh.md
  docs/manual/docs/user-guide/harvesting/harvesting-ogcwxs.md
  docs/manual/docs/user-guide/harvesting/harvesting-sde.md
  docs/manual/docs/user-guide/harvesting/harvesting-simpleurl.md
  docs/manual/docs/user-guide/harvesting/harvesting-thredds.md
  docs/manual/docs/user-guide/harvesting/harvesting-webdav.md
  docs/manual/docs/user-guide/harvesting/harvesting-wfs-features.md
  docs/manual/docs/user-guide/harvesting/harvesting-z3950.md
  docs/manual/docs/user-guide/harvesting/img/add-arcsde-harvester.png
  docs/manual/docs/user-guide/harvesting/img/add-csw-harvester.png
  docs/manual/docs/user-guide/harvesting/img/add-filesystem-harvester.png
  docs/manual/docs/user-guide/harvesting/img/add-geonetwork-3-harvester.png
  docs/manual/docs/user-guide/harvesting/img/add-geoportalrest-harvester.png
  docs/manual/docs/user-guide/harvesting/img/add-harvester.png
  docs/manual/docs/user-guide/harvesting/img/add-oaipmh-harvester.png
  docs/manual/docs/user-guide/harvesting/img/add-ogcwebservices-harvester.png
  docs/manual/docs/user-guide/harvesting/img/add-simpleurl-harvester.png
  docs/manual/docs/user-guide/harvesting/img/add-threddscatalog-harvester.png
  docs/manual/docs/user-guide/harvesting/img/add-webdav-harvester.png
  docs/manual/docs/user-guide/harvesting/img/add-wfsgetfeature-harvester.png
  docs/manual/docs/user-guide/harvesting/img/harvester-history.png
  docs/manual/docs/user-guide/harvesting/img/harvester-statistics.png
  docs/manual/docs/user-guide/harvesting/img/harvesters.png
  docs/manual/docs/user-guide/harvesting/index.md
  docs/manual/mkdocs.yml
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/HarvesterUtil.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/WebDavHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/WebDavParams.java
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.js
  web/src/main/webapp/xsl/xml/harvesting/webdav.xsl
Labels: enhancement, backport 4.2.x, changelog, Documentation

#8421 Elasticsearch / API / Allow ndjson for _msearch endpoint
  services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
Labels: backport 4.2.x

#8436 Allow removal of empty graphic overviews
  schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-remove.xsl
Labels: bug, backport 4.2.x

#8337 Elasticsearch / Update to 8.14.3.
  docs/manual/docs/install-guide/installing-index.md
  es/README.md
  es/docker-compose.yml
  es/es-dashboards/README.md
  pom.xml
  web/src/main/webResources/WEB-INF/data/config/index/records.json
Labels: changelog

#8432 Harvester / Simple URL / Fix multiple URL alignement
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Harvester.java
Labels: backport 4.2.x

#8439 Fix saving UI settings without changes
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
Labels: backport 4.2.x

#8430 Add better logging when resources are deleted to make it clear what metadata record the resource was deleted from
  core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
  datastorages/cmis/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
  datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
  datastorages/s3/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
Labels: backport 4.2.x

#8444 Add bootstrap datepicker language files for supported UI languages
  web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.az.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.ca.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.cs.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.cy.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.da.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.de.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.es.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.fi.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.hy.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.is.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.it.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.ka.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.ko.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.pt.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.ro.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.ru.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.sk.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.sv.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.uk.min.js
  web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.zh.min.js
  web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
Labels: backport 4.2.x

#8446 Avoid duplicate validation message when trying to register a user with existing email
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  services/src/main/java/org/fao/geonet/api/users/validation/UserRegisterDtoValidator.java
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport 4.2.x

#8426 Update home page "browse by" to display facet as label if there is only one
  web-ui/src/main/resources/catalog/views/default/templates/home.html
Labels: backport 4.2.x

#8454 Delete date not being copied causing duplicate
  core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
Labels: bug, backport 4.2.x

#8453 Metadata status changes notification mails improvements
  core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
Labels: backport 4.2.x

#8471 Documentation / Update managing privileges page
  docs/manual/docs/user-guide/publishing/managing-privileges.md
Labels: backport 4.2.x

#8294 option to force xsd schema check for required field
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: backport 4.2.x

#8473 Documentation / Metadata workflow improvements
  docs/manual/docs/user-guide/workflow/life-cycle.md
Labels: backport 4.2.x

#8401 Add option to mock a dropdown for keywordPickers
  schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
  web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner.html
  web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner_onlineresourcesdescription.html
  web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Labels: backport 4.2.x
