Repository geonetwork/core-geonetwork, pull requests merged in 2025-07, with the labels that each got.

#8664 Metadata editor / Avoid displaying the tooltip icon next to buttons to add new elements, when the toolstip mode is icon
  web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Labels: backport 4.2.x

#8907 Validation report / Show schema validation after optional rules
  web-ui/src/main/resources/catalog/components/edit/validationreport/ValidationReportDirective.js
Labels: backport 4.2.x

#8849 Record page / restrict formatters to view / export metadata to those supported by the metadata schema
  services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
  web-ui/src/main/resources/catalog/views/default/directives/directive.js
Labels: api change

#8918 Fix user appears logged out in ratings panel
  web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js
Labels: bug, backport 4.2.x

#8933 [Backport 4.2.x] Delete resources when a new working copy is cancelled
  core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
Labels: bug

#8932 [Backport 4.2.x] Fix url is not multilingual in rating email
  services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
Labels: bug

#8942 [Backport 4.2.x] Fix image modal style for small images
  web-ui/src/main/resources/catalog/style/gn.less
Labels: enhancement

#8943 Settings / Fix INSPIRE Atom type setting value selected
  web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
Labels: backport 4.2.x

#8951 [Backport 4.2.x] Resume attachment downloads
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: enhancement

#8952 Simple URL harvester / Index the metadata when updated
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Aligner.java
Labels: bug, backport 4.2.x

#8672 SFTP harvester
  common/pom.xml
  docs/manual/docs/user-guide/harvesting/harvesting-sftp.md
  docs/manual/docs/user-guide/harvesting/img/add-sftp-harvester.png
  docs/manual/docs/user-guide/harvesting/index.md
  docs/manual/mkdocs.yml
  harvesters/pom.xml
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/sftp/Aligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/sftp/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/sftp/SftpHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/sftp/SftpHarvesterUtil.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/sftp/SftpParams.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/sftp/client/KeyPairGeneratorUtil.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/sftp/client/SftpClient.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/sftp/client/SftpFileInfo.java
  harvesters/src/main/resources/config-spring-geonetwork.xml
  pom.xml
  web-ui/src/main/resources/catalog/components/admin/harvester/partials/extras.html
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/sftp.html
  web-ui/src/main/resources/catalog/templates/admin/harvest/type/sftp.js
  web/src/main/webapp/xsl/xml/harvesting/sftp.xsl
Labels: backport 4.2.x, changelog, Documentation
