Repository geonetwork/core-geonetwork, pull requests merged in 2025-09, with the labels that each got.

#9008 Add key "dan" for "Dansk" (Danish)
  web-ui/src/main/resources/catalog/locales/en-core.json
Labels: backport 4.2.x

#9000 Record page / Update metadata full view formatter to Use context information with xpath from labels.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/common.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
  services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java
  services/src/test/java/org/fao/geonet/api/records/formatters/SchemaLocalizationsIntegrationTest.java
  services/src/test/java/org/fao/geonet/api/records/formatters/SchemaLocalizationsTest.java
  web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
Labels: backport 4.2.x

#9031 Corrected the formatting on validation log messages.
  core/src/main/java/org/fao/geonet/kernel/SchematronValidatorExternalMd.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
Labels: bug, backport 4.2.x

#9041 [Backport 4.2.x] Corrected the formatting on validation log messages.
  core/src/main/java/org/fao/geonet/kernel/SchematronValidatorExternalMd.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
Labels: bug

#8930 Database harvester / support qualified table names (schema.table) and improve sanitize of table / field names
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseHarvesterAligner.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseHarvesterParams.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseHarvesterUtil.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseMetadataRetriever.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseMetadataRetrieverFactory.java
  harvesters/src/test/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseHarvesterUtilTest.java
  web-ui/src/main/resources/catalog/locales/en-admin.json
Labels: backport 4.2.x

#8726 Update batch privileges dialog texts
  web-ui/src/main/resources/catalog/locales/ca-search.json
  web-ui/src/main/resources/catalog/locales/ca-v4.json
  web-ui/src/main/resources/catalog/locales/cy-search.json
  web-ui/src/main/resources/catalog/locales/cy-v4.json
  web-ui/src/main/resources/catalog/locales/en-search.json
  web-ui/src/main/resources/catalog/locales/en-v4.json
  web-ui/src/main/resources/catalog/locales/es-search.json
  web-ui/src/main/resources/catalog/locales/fi-search.json
  web-ui/src/main/resources/catalog/locales/fi-v4.json
  web-ui/src/main/resources/catalog/locales/is-search.json
  web-ui/src/main/resources/catalog/locales/is-v4.json
  web-ui/src/main/resources/catalog/locales/it-search.json
  web-ui/src/main/resources/catalog/locales/it-v4.json
  web-ui/src/main/resources/catalog/locales/ko-search.json
  web-ui/src/main/resources/catalog/locales/ko-v4.json
  web-ui/src/main/resources/catalog/locales/pl-search.json
  web-ui/src/main/resources/catalog/locales/pl-v4.json
  web-ui/src/main/resources/catalog/locales/pt-search.json
  web-ui/src/main/resources/catalog/locales/pt-v4.json
  web-ui/src/main/resources/catalog/locales/ru-search.json
  web-ui/src/main/resources/catalog/locales/ru-v4.json
  web-ui/src/main/resources/catalog/locales/sk-search.json
  web-ui/src/main/resources/catalog/locales/sk-v4.json
  web-ui/src/main/resources/catalog/locales/zh-search.json
  web-ui/src/main/resources/catalog/locales/zh-v4.json
Labels: backport 4.2.x
