Repository geonetwork/core-geonetwork, pull requests merged in 2025-03, with the labels that each got.

#8666 Editor / Keyword dropdown / Sort keywords by label
  web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusService.js
Labels: backport 4.2.x

#8683 Conversion from ISO19139 to ISO19115-3.2018: Manage organisation name with Anchor
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/mapping/CI_ResponsibleParty.xsl
Labels: backport 4.2.x

#8671 Static pages / sort groups alphabetically
  web-ui/src/main/resources/catalog/js/admin/StaticPagesController.js
Labels: backport 4.2.x

#8647 Fix harvesting errors not always being reported
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/IHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/GeoPRESTHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/OaiPmhHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/SimpleUrlHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/ThreddsHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/WebDavHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/WfsFeaturesHarvester.java
  harvesters/src/test/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/HarvesterTest.java
  harvesters/src/test/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/HarvesterTest.java
Labels: backport 4.2.x, changelog

#8521 Update translations for Portuguese in codelists for schema 19139
  schemas/iso19139/src/main/plugin/iso19139/loc/por/codelists.xml
Labels: backport 4.2.x

#8608 Add byte data to metadata summary page for its children thumbnails
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
Labels: backport 4.2.x

#8690 [Backport 4.2.x] Fix harvesting errors not always being reported
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/IHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/GeoPRESTHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/OaiPmhHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/SimpleUrlHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/ThreddsHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/WebDavHarvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/Harvester.java
  harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/WfsFeaturesHarvester.java
  harvesters/src/test/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/HarvesterTest.java
  harvesters/src/test/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/HarvesterTest.java
Labels: changelog

#8644 datahubs per sub-portal
  .gitignore
  core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
  docs/manual/docs/administrator-guide/index.md
  docs/manual/docs/install-guide/img/datahub.png
  docs/manual/docs/install-guide/installing-from-war-file.md
  docs/manual/docs/install-guide/plugins.md
  docs/manual/mkdocs.yml
  domain/src/main/java/org/fao/geonet/domain/Source.java
  plugins/datahub-integration/pom.xml
  plugins/datahub-integration/src/main/java/org/fao/geonet/datahub/DatahubController.java
  plugins/datahub-integration/src/main/java/org/fao/geonet/datahub/FileUtils.java
  pom.xml
  services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
  web-ui/src/main/resources/catalog/js/admin/SourcesController.js
  web-ui/src/main/resources/catalog/locales/en-admin.json
  web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
  web-ui/src/main/resources/catalog/templates/admin/settings/system.html
  web/pom.xml
  web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v447/migrate-default.sql
  web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
Labels: backport 4.2.x
