Repository geonetwork/core-geonetwork, pull requests merged in 2025-06, with the labels that each got.

#8833 Fix metadata feedback email text
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_dut.properties
Labels: bug, backport 4.2.x

#8829 Fix in the metadata selection widget the number of metadata selected
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html
Labels: bug, backport 4.2.x

#8801 Set UTF-8 on sent mails
  core/src/main/java/org/fao/geonet/util/MailUtil.java
Labels: backport 4.2.x

#8874 Lineage / handle process steps with multiple sources
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  web-ui/src/main/resources/catalog/views/default/templates/recordView/processsteps.html
Labels: backport 4.2.x

#8605 Static pages / add support for mail links
  common/src/main/java/org/fao/geonet/utils/EmailUtil.java
  common/src/test/java/org/fao/geonet/utils/EmailUtilTest.java
  docs/manual/docs/customizing-application/adding-static-pages.md
  docs/manual/docs/customizing-application/img/add-static-page.png
  docs/manual/docs/customizing-application/img/pages-api.png
  docs/manual/docs/customizing-application/img/static-page-footer.png
  domain/src/main/java/org/fao/geonet/domain/page/Page.java
  services/src/main/java/org/fao/geonet/api/pages/PagesAPI.java
  services/src/main/java/org/fao/geonet/api/users/validation/UserRegisterDtoValidator.java
  web-ui/src/main/resources/catalog/components/pages/GnStaticPagesDirective.js
  web-ui/src/main/resources/catalog/components/pages/partials/menu-page.html
  web-ui/src/main/resources/catalog/js/admin/StaticPagesController.js
  web-ui/src/main/resources/catalog/locales/en-v4.json
  web-ui/src/main/resources/catalog/templates/admin/settings/static-pages.html
Labels: backport 4.2.x

#8875 Fix issue with oidc invalid session by adding session filter
  core/src/main/java/org/fao/geonet/kernel/security/openidconnect/GeonetworkOidcPreAuthActionsLoginFilter.java
  core/src/main/java/org/fao/geonet/kernel/security/openidconnect/SessionExpirationFilter.java
  web/src/main/webapp/WEB-INF/config-security/config-security-openidconnectbearer.xml
Labels: bug, backport 4.2.x

#8896 [Backport 4.2.x] Fix content type and filename for resized image attachments
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: bug, changelog
