Repository geonetwork/core-geonetwork, pull requests merged in 2025-01, with the labels that each got.

#8581 Url decode the resourceId supplied to store.getResourceInternal to fix filenames containing spaces.
  core/src/main/java/org/fao/geonet/util/XslUtil.java
Labels: bug, backport 4.2.x

#8582 Fix set site settings in swagger_ui so it function correctly.
  services/src/main/java/org/fao/geonet/api/site/SiteApi.java
  services/src/test/java/org/fao/geonet/api/site/SiteApiTest.java
Labels: api change, backport 4.2.x

#8583 Move StatusValue.Events to an enum class
  domain/src/main/java/org/fao/geonet/domain/StatusValue.java
  listeners/src/main/java/org/fao/geonet/listener/history/AttachmentAddedListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/AttachmentDeletedListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/RecordCategoryChangeListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/RecordCreatedListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/RecordDeletedListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/RecordGroupOwnerChangeListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/RecordImportedListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/RecordOwnerChangeListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/RecordPrivilegesChangeListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/RecordProcessingChangeListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/RecordRestoredListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/RecordUpdatedListener.java
  listeners/src/main/java/org/fao/geonet/listener/history/RecordValidationTriggeredListener.java
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
Labels: backport 4.2.x

#8587 [Backport 4.2.x] Url decode the resourceId supplied to store.getResourceInternal to fix filenames containing spaces.
  core/src/main/java/org/fao/geonet/util/XslUtil.java
Labels: bug

#8590 [Backport 4.2.x] Record view / Lineage & Quality section improvements (#7180)
  core/src/main/java/org/fao/geonet/api/tools/i18n/TranslationPackBuilder.java
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
  web-ui/src/main/resources/catalog/components/search/mdview/partials/qualitymeasures.html
  web-ui/src/main/resources/catalog/locales/en-v4.json
  web-ui/src/main/resources/catalog/style/gn_metadata.less
  web-ui/src/main/resources/catalog/style/timeline.less
  web-ui/src/main/resources/catalog/views/default/templates/recordView/measures.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView/processsteps.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView/quality.html
  web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
  web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
  web/src/main/webResources/WEB-INF/data/config/index/records.json
Labels: index structure change, changelog

#8593 [Backport 4.2.x] Record view / DQ / Add measure date information
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
  web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
  web-ui/src/main/resources/catalog/components/search/mdview/partials/qualitymeasures.html
  web-ui/src/main/resources/catalog/locales/en-v4.json
  web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
  web/src/main/webResources/WEB-INF/data/config/index/records.json
Labels: index structure change

#8595 Record view / fix javascript error when a metadata has multiple lineage source descriptions
  core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
  web-ui/src/main/resources/catalog/js/CatController.js
  web-ui/src/main/resources/catalog/views/default/templates/recordView/lineage.html
Labels: backport 4.2.x

#8592 Update creating-group.md
  docs/manual/docs/administrator-guide/managing-users-and-groups/creating-group.md
Labels: backport 4.2.x

#8598 Metadata indexing / parse process steps and measure dates to check that are valid.
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
  schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
Labels: backport 4.2.x

#8562 Enforce upload size limit on putResourceFromUrl api
  core/src/main/java/org/fao/geonet/api/exception/InputStreamLimitExceededException.java
  core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
  core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
  core/src/main/java/org/fao/geonet/util/LimitedInputStream.java
  core/src/test/resources/WEB-INF/config.properties
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
  services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
  services/src/test/java/org/fao/geonet/api/records/attachments/AbstractStoreTest.java
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport 4.2.x

#8600 French translation for user registered message
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport 4.2.x

#8609 Fix privileges cannot be unset
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java
Labels: backport 4.2.x

#8611 [Backport 4.2.x] Fix privileges cannot be unset
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java
Labels: bug

#8153 Update getRecordStatusHistory and getRecordStatusHistoryByType to support getting working copy records history.
  services/src/main/java/org/fao/geonet/api/ApiUtils.java
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
Labels: enhancement, backport 4.2.x

#8620 [Backport 4.2.x] Update getRecordStatusHistory and getRecordStatusHistoryByType to support getting working copy records history.
  services/src/main/java/org/fao/geonet/api/ApiUtils.java
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
Labels: enhancement, api change

#8386 Improve performance of parsing simple dates
  domain/src/main/java/org/fao/geonet/domain/ISODate.java
Labels: enhancement, backport 4.2.x, changelog

#8619 Fix jcloud content length is inaccurate
  core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
  core/src/main/java/org/fao/geonet/util/LimitedInputStream.java
  datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
Labels: backport 4.2.x

#8266 Add get /api/sources/{sourceIdentifier} to be able to get a source by id.
  domain/src/main/java/org/fao/geonet/repository/SourceRepository.java
  services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
  services/src/test/java/org/fao/geonet/api/sources/SourcesApiTest.java
  web-ui/src/main/resources/catalog/components/usersearches/UserSearchesDirective.js
  web-ui/src/main/resources/catalog/components/usersearches/UserSearchesService.js
  web-ui/src/main/resources/catalog/js/admin/CSWTestController.js
Labels: api change, backport 4.2.x

#8629 [Backport 4.2.x] Add get /api/sources/{sourceIdentifier} to be able to get a source by id.
  domain/src/main/java/org/fao/geonet/repository/SourceRepository.java
  services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
  services/src/test/java/org/fao/geonet/api/sources/SourcesApiTest.java
  web-ui/src/main/resources/catalog/components/usersearches/UserSearchesDirective.js
  web-ui/src/main/resources/catalog/components/usersearches/UserSearchesService.js
  web-ui/src/main/resources/catalog/js/admin/CSWTestController.js
Labels: api change

#8632 Sort categories list by translation in the categories and groups pages
  web-ui/src/main/resources/catalog/js/admin/CategoriesController.js
  web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
Labels: backport 4.2.x
