Repository geonetwork/core-geonetwork, pull requests merged in 2025-08, with the labels that each got.

#8842 Update mokito to version 4
  core/pom.xml
  core/src/main/java/org/fao/geonet/arcgis/ArcSDEJdbcConnection.java
  core/src/main/java/org/fao/geonet/kernel/search/index/BatchOpsMetadataReindexer.java
  core/src/test/java/org/fao/geonet/kernel/LocalInvokerMokitoMockFactory.java
  core/src/test/java/org/fao/geonet/kernel/LocalXLinksInMetadataIntegrationTest.java
  core/src/test/java/org/fao/geonet/kernel/LocalXLinksUpdateDeleteTest.java
  core/src/test/java/org/fao/geonet/kernel/XmlSerializerIntegrationTest.java
  core/src/test/java/org/fao/geonet/kernel/security/GeonetworkAuthenticationProviderIntegrationTest.java
  core/src/test/java/org/fao/geonet/kernel/security/jwtheaders/JwtHeadersIntegrationTest.java
  core/src/test/java/org/fao/geonet/kernel/security/jwtheaders/JwtHeadersUserUtilTest.java
  core/src/test/java/org/fao/geonet/kernel/url/UrlAnalyzerTest.java
  core/src/test/java/org/fao/geonet/kernel/url/UrlCheckerTest.java
  core/src/test/resources/mocked-core-repository-test-context.xml
  estest/pom.xml
  harvesters/pom.xml
  harvesters/src/test/java/org/fao/geonet/kernel/search/EsSearchManagerMokitoMockFactory.java
  harvesters/src/test/resources/harvesters-repository-test-context.xml
  inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomPredefinedFeed.java
  pom.xml
  schemas-test/pom.xml
  services/pom.xml
  services/src/test/java/org/fao/geonet/api/links/LinksApiTest.java
  services/src/test/java/org/fao/geonet/api/records/formatters/AlternateLogoForPdfExportTest.java
  services/src/test/java/org/fao/geonet/api/records/formatters/PdfOrHtmlResponseWriterMokitoSpyFactory.java
  services/src/test/java/org/fao/geonet/api/selections/UserSelectionsApiTest.java
  services/src/test/java/org/fao/geonet/services/metadata/BatchOpsMetadatReindexerTest.java
  services/src/test/resources/formatter-test-context.xml
  web/pom.xml
  web/src/test/java/v3110/UpdateUISettingsMigrationTest.java
  web/src/test/java/v343/AdvancedSearchFormMigrationTest.java
  web/src/test/java/v350/UrlComponentsDetectorsRegexMigrationTest.java
  web/src/test/java/v370/HumanizeDatesUiMigrationTest.java
  web/src/test/java/v370/UserCustomSearchesMigrationTest.java
  workers/camelPeriodicProducer/pom.xml
  workers/wfsfeature-harvester/pom.xml
Labels: backport 4.2.x

#8959 Fix attachment caching issue
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: bug, backport 4.2.x

#8968 [Backport 4.2.x] Fix batch validation and editor validation do not output the same result
  core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataManager.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataValidator.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
  core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
Labels: bug

#8975 Facets / Fix removal of values encoded as 0 in facet filter objects
  web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
Labels: backport 4.2.x

#8978 Fix attachment download for jcloud
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: bug, backport 4.2.x

#8983 [Backport 4.2.x] Fix attachment download for jcloud
  services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Labels: bug

#8958 Add service associated resource. Fix add link from service distribution section.
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
  web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
Labels: backport 4.2.x

#8995 Added logs for identity of OIDC login
  core/src/main/java/org/fao/geonet/kernel/security/openidconnect/GeonetworkOAuth2LoginAuthenticationFilter.java
Labels: backport 4.2.x

#8997 Update nonGeographicDataset French translation
  schemas/dublin-core/src/main/plugin/dublin-core/loc/fre/labels.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/codelists.xml
  schemas/iso19115-3.2018/src/test/resources/metadata-for-editing-light.xml
  schemas/iso19115-3.2018/src/test/resources/metadata-for-editing.xml
  schemas/iso19115-3.2018/src/test/resources/metadata-iso19139-for-editing.xml
  schemas/iso19139/src/main/plugin/iso19139/loc/fre/codelists.xml
Labels: backport 4.2.x

#8999 Standard / ISO19115-3 / Fix typos in French codelists descriptions
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/codelists.xml
Labels: backport 4.2.x
