Repository geonetwork/core-geonetwork, pull requests merged in 2025-02, with the labels that each got.

#8628 URL Decode filename for resources uploaded by url
  core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
  core/src/test/java/org/fao/geonet/api/records/attachments/FilesystemStoreTest.java
Labels: bug, backport 4.2.x

#8641 [Backport 4.2.x] URL Decode filename for resources uploaded by url
  core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
  core/src/test/java/org/fao/geonet/api/records/attachments/FilesystemStoreTest.java
Labels: bug

#8646 Standard / 19115-3 / Update labels.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml
Labels: backport 4.2.x

#8607 Metadata citation improvements
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/base.xsl
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/common.xsl
  schemas/iso19139/src/main/plugin/iso19139/formatter/citation/base.xsl
  services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-citation-bibtex.txt
  services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-citation-ris.txt
  services/src/test/resources/org/fao/geonet/api/records/formatters/iso19139-citation-bibtex.txt
  services/src/test/resources/org/fao/geonet/api/records/formatters/iso19139-citation-ris.txt
  web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
  web-ui/src/main/resources/catalog/components/metadataactions/partials/citation.html
  web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
  web-ui/src/main/resources/catalog/locales/en-core.json
Labels: backport 4.2.x

#8639 Pasting text in the metadata editor uploads an image to the catalogue store
  web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
Labels: backport 4.2.x

#8638 Add Dutch translations of the iso19115-3.2018 metadata schema
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/codelists.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/labels.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/schematron-rules-datacite.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/schematron-rules-url-check.xml
  schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/strings.xml
Labels: backport 4.2.x

#8660 Update Github Actions runner images
  .github/workflows/backport.yml
  .github/workflows/linux.yml
Labels: backport 3.12.x, backport 4.0.x, github_actions, backport 4.2.x

#8667 Fix only record owners can access workflow status API
  core/src/test/resources/org/fao/geonet/api/Messages.properties
  core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
  services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_dut.properties
  web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Labels: backport 4.2.x

#8622 Set related children's thumbnail to default 4
  web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
Labels: backport 4.2.x

#8675 Map viewer / Use 8 decimals for the bounding box of map in a metadata.
  web-ui/src/main/resources/catalog/components/common/map/mapDirective.js
Labels: backport 4.2.x

#8633 Search result record abstract parsing improvement
  web-ui/src/main/resources/catalog/components/search/resultsview/ResultsviewDirective.js
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
  web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
Labels: backport 4.2.x
